/*
select * from DASH_MESSAGE_TYPE order by msg_typeid, cust_prod_id;

DELETE FROM DASH_MESSAGE_TYPE
 WHERE MSG_TYPEID IN (1037, 1038)
   AND CUST_PROD_ID <> 5001;
 
*/
ALTER TABLE
   DASH_MESSAGE_TYPE
ENABLE CONSTRAINT
   PK_MESSAGE_TYPE;
   
ALTER TABLE
   DASH_MESSAGE_TYPE
ENABLE CONSTRAINT
   DASH_MESSAGE_TYPE_UNIQUE; 
   
ALTER TABLE
   DASH_MESSAGES
DISABLE CONSTRAINT
   FK_DASH_MESSAGES_3;   
   