CREATE OR REPLACE TYPE MANAGE_MESSAGE_TO_TYPE AS OBJECT
(

  REPORT_ID         NUMBER(10),
  MESSAGE_TYPE_ID   NUMBER(10),
  MESSAGE_TYPE_NAME VARCHAR2(50),
  MESSAGE_TYPE_DESC VARCHAR2(100),
  MESSAGE_TYPE      VARCHAR2(50),
  MESSAGE           CLOB,
  ACTIVATION_STATUS VARCHAR2(3),
  CUST_PROD_ID      NUMBER(10)
);
/
/
