@\PRC_REFRESH_SUB_GRD_OBJ_MAP;
@\PRC_REFRESH_ORG_TP_STRUCTURE;
@\PRC_CREATE_RESULTS_GRT_PARTN.prc;
@\PRC_DELETE_RESCORE_FACT.prc;
@\PRC_MV_REFRESH_UDTR_ROSTER.prc;
@\PRC_REFRESH_PRINCIPAL_USER.prc;
@\SP_CREATE_CTBADMIN.prc;
@\SP_GEN_INVITE_CODE.prc;

