-- Create table
create table STG_ERRF_RESCORE
(
  PROCESS_ID            NUMBER,
  APPSKILLS_IMAGE_ID    VARCHAR2(52),
  CORPORATION_NAME      VARCHAR2(64),
  TEST_MODULE_ID_PEID   VARCHAR2(10),
  ITEM_NUMBER           VARCHAR2(10),
  ITEM_PART             VARCHAR2(5),
  ORIG_SCORE            VARCHAR2(20),
  ORIG_PL               VARCHAR2(20),
  RPT_ITEM_NUMBER       VARCHAR2(10),
  POINTS_POSSIBLE       NUMBER,
  ELIGIBLE_FOR_RESCORE  VARCHAR2(10),
  CONTENT_AREA          VARCHAR2(20),
  TEST_SESSION_NUMBER   NUMBER,
  ORG_TSTG_PGM          VARCHAR2(64),
  STRUCTURE_LEVEL_CORP  VARCHAR2(10),
  ELEMENT_NUMBER_CORP   VARCHAR2(10),
  CORPORATION_NUMBER    VARCHAR2(10),
  STRUCTURE_LEVEL_SCH   VARCHAR2(10),
  ELEMENT_NUMBER_SCH    VARCHAR2(10),
  SCHOOL_NAME           VARCHAR2(64),
  SCHOOL_NUMBER         VARCHAR2(10),
  GRADE                 VARCHAR2(10),
  STRUCTURE_LEVEL       VARCHAR2(10),
  ELEMENT_NUMBER        VARCHAR2(10),
  STUDENT_LAST_NAME     VARCHAR2(32),
  STUDENT_FIRST_NAME    VARCHAR2(32),
  PRIMARY_STUDENT_ID    VARCHAR2(26),
  TEST_NAME             VARCHAR2(10),
  IS_ROW_VALID          VARCHAR2(5),
  DATA_VALIDATION_ERROR VARCHAR2(4000),
  CREATED_DATE_TIME     DATE default SYSDATE
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
