insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'role.not.added','ROLE_CTB,ROLE_SUPER',null);
insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'orglvl.user.not.added','0',null);
insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'orglvl.admin.not.added','4',null);
insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'aws.inors.cacheS3','Cache_Keys/TASC/',null);
insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'hmac.secret.key','WPZguVF49hXaRuZfe9L29ItsC2I','OAS|TASC');
insert into DASH_CONTRACT_PROP(DB_PROPERTYID,DB_PROPERTY_NAME,DB_PROPERY_VALUE,SSO_SOURCE)
values(SEQ_DASH_CONTRACT_PROP.NEXTVAL,'hmac.secret.key','ETCguRF49hEaRuZguVF49hXrc1','eResource|TASC');