-----------------------------------------------------MV_TEST_PROGRAM--------------------------------------------------------
CREATE MATERIALIZED VIEW MV_TEST_PROGRAM
REFRESH COMPLETE ON DEMAND
AS
SELECT LVL2.CUSTOMERID,
       LVL2.NUM_LEVELS,
       CASE
       WHEN LVL2.NUM_LEVELS=1 THEN
            LVL2.LVL_NAME
       ELSE
            SUBSTR(LVL2.LVL_NAME,1, INSTR(LVL2.LVL_NAME,'~',1,1)-1 )
       END AS ORG_LEVEL1_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=2 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,1)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,1))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,1)+1, INSTR(LVL2.LVL_NAME,'~',1,2)-INSTR(LVL2.LVL_NAME,'~',1,1)-1 )
       END AS ORG_LEVEL2_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=3 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,2)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,2))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,2)+1, INSTR(LVL2.LVL_NAME,'~',1,3)-INSTR(LVL2.LVL_NAME,'~',1,2)-1 )
       END AS ORG_LEVEL3_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=4 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,3)+1, LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,3))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,3)+1, INSTR(LVL2.LVL_NAME,'~',1,4)-INSTR(LVL2.LVL_NAME,'~',1,3)-1 )
       END AS ORG_LEVEL4_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=5 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,4)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,4))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,4)+1, INSTR(LVL2.LVL_NAME,'~',1,5)-INSTR(LVL2.LVL_NAME,'~',1,4)-1 )
       END AS ORG_LEVEL5_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=6 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,5)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,5))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,5)+1, INSTR(LVL2.LVL_NAME,'~',1,6)-INSTR(LVL2.LVL_NAME,'~',1,5)-1 )
       END AS ORG_LEVEL6_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=7 THEN
       SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,6)+1, LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,6))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,6)+1, INSTR(LVL2.LVL_NAME,'~',1,7)-INSTR(LVL2.LVL_NAME,'~',1,6)-1 )
       END AS ORG_LEVEL7_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=8 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,7)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,7))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,7)+1, INSTR(LVL2.LVL_NAME,'~',1,8)-INSTR(LVL2.LVL_NAME,'~',1,7)-1 )
       END AS ORG_LEVEL8_TYPE,
       CASE
       WHEN LVL2.NUM_LEVELS=9 THEN
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,8)+1,LENGTH(LVL2.LVL_NAME)-INSTR(LVL2.LVL_NAME,'~',1,8))
       ELSE
            SUBSTR(LVL2.LVL_NAME,INSTR(LVL2.LVL_NAME,'~',1,8)+1,INSTR(LVL2.LVL_NAME,'~',1,8)-INSTR(LVL2.LVL_NAME,'~',1,7)-1 )
       END AS ORG_LEVEL9_TYPE
FROM (SELECT LVL1.CUSTOMERID,LVL1.NUM_LEVELS,LISTAGG (LVL1.ORG_LABEL,'~') WITHIN GROUP (ORDER BY LVL1.ORG_LEVEL) AS LVL_NAME
          FROM (SELECT DISTINCT ORG_SRTUC.ORG_LEVEL ,ORG_SRTUC.ORG_LABEL ,TP.NUM_LEVELS,TP.CUSTOMERID
                  FROM TEST_PROGRAM TP,ORG_TP_STRUCTURE ORG_SRTUC
                   WHERE TP.ACTIVATION_STATUS = 'AC'
                     AND ORG_SRTUC.TP_ID = TP.TP_ID
                     ORDER BY  ORG_SRTUC.ORG_LEVEL)LVL1
                     GROUP BY LVL1.CUSTOMERID,
                              LVL1.NUM_LEVELS)LVL2;
							  
-----------------------------------------------------MV_PROF_LEVEL_SCORE_RANGE--------------------------------------------------------							  
CREATE MATERIALIZED VIEW MV_ORG_TP_STRUCTURE
REFRESH FORCE ON DEMAND
AS
SELECT TP_ID, ORG_LEVEL, ORG_LABEL, DATETIMESTAMP
					/* *******************************************************
                    * This MATERIALIZED VIEW is created as a part of performance
                    * improvemnt for the queries of the manage modules
                    * DATE: Mar-02-2015
                    * AUTHOR: Partha
                    *********************************************************/
  FROM PRISMGLOBAL.ORG_TP_STRUCTURE
 WHERE TP_ID IN (SELECT TP_ID FROM TEST_PROGRAM); 
 
-----------------------------------------------------MV_PROF_LEVEL_SCORE_RANGE--------------------------------------------------------
CREATE MATERIALIZED VIEW MV_PROF_LEVEL_SCORE_RANGE
REFRESH COMPLETE ON DEMAND
AS
SELECT CUTSCORESCALESCOREID,
       CUST_PROD_ID,
       GRADEID,
       LEVELID,
       SUBTESTID,
       PL1_LOW_VAL,
       PL1_HIGH_VAL,
       PL2_LOW_VAL,
       PL2_HIGH_VAL,
       PL3_LOW_VAL,
       PL3_HIGH_VAL,
       PL4_LOW_VAL,
       PL4_HIGH_VAL,
       PL4_HIGH_VAL - PL1_LOW_VAL AS TOTAL_RANGE,
       PL1_HIGH_VAL-PL1_LOW_VAL AS RANGE_BELOW_BASIC,
       PL2_HIGH_VAL-PL1_HIGH_VAL AS RANGE_BASIC,
       PL3_HIGH_VAL-PL2_HIGH_VAL AS RANGE_PROFICIENT,
       PL4_HIGH_VAL-PL3_HIGH_VAL AS RANGE_ADVANCED,
       CREATED_DATETIME,
       UPDATED_DATETIME
FROM(SELECT CUTSCORESCALESCOREID,
       CUST_PROD_ID,
       GRADEID,
       LEVELID,
       SUBTESTID,
       PASS,
       PASSPLUS,
       PL,
       PASS AS PL1_LOW_VAL,
       PASSPLUS AS PL1_HIGH_VAL,
       LEAD(PASS, 1, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL2_LOW_VAL,
       LEAD(PASSPLUS, 1, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL2_HIGH_VAL,
       LEAD(PASS, 2, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL3_LOW_VAL,
       LEAD(PASSPLUS, 2, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL3_HIGH_VAL,
       LEAD(PASS, 3, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL4_LOW_VAL,
       LEAD(PASSPLUS, 3, 0) OVER (PARTITION BY CUST_PROD_ID,GRADEID,LEVELID,SUBTESTID ORDER BY PL  NULLS LAST) PL4_HIGH_VAL,
       SYSDATE AS CREATED_DATETIME,
       SYSDATE AS UPDATED_DATETIME
 FROM CUTSCORESCALESCORE WHERE PL IN (1,2,3,4)
 ORDER BY CUST_PROD_ID,
       GRADEID,
       LEVELID,
       SUBTESTID,
       PL)A
  WHERE  A.PL =1;
  
-----------------------------------------------------MV_RPRT_STUD_DETAILS--------------------------------------------------------
CREATE MATERIALIZED VIEW LOG ON SUBTEST_SCORE_FACT; 
--NOW RUN THE PACKAGE PKG_RPRT_STUD_DETAILS.PCK

/*CREATE MATERIALIZED VIEW MV_RPRT_STUD_DETAILS
REFRESH FAST ON DEMAND
AS
SELECT
SCR.SUBTEST_FACTID,
SCR.STUDENT_BIO_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO',P_ADMINID=>SCR.ADMINID,P_GRADEID=>SCR.GRADEID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'FIRST_NAME') AS FIRST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO',P_ADMINID=>SCR.ADMINID,P_GRADEID=>SCR.GRADEID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'LAST_NAME') AS LAST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO',P_ADMINID=>SCR.ADMINID,P_GRADEID=>SCR.GRADEID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'MIDDLE_NAME') AS MIDDLE_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO',P_ADMINID=>SCR.ADMINID,P_GRADEID=>SCR.GRADEID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'BIRTHDATE') AS BIRTHDATE,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO',P_ADMINID=>SCR.ADMINID,P_GRADEID=>SCR.GRADEID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'EXT_STUDENT_ID') AS EXT_STUDENT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUSTOMER_CODE=>'MO',P_COLUMNTYPE=>'ORG_NODE_CODE') AS DISTRICT_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUSTOMER_CODE=>'MO',P_COLUMNTYPE=>'ORG_NODE_NAME') AS DISTRICT_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUSTOMER_CODE=>'MO',P_COLUMNTYPE=>'ORG_NODE_CODE') AS SCHOOL_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUSTOMER_CODE=>'MO',P_COLUMNTYPE=>'ORG_NODE_NAME') AS SCHOOL_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICTID(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUSTOMER_CODE=>'MO') AS DISTRICT_ORG_NODEID,
SCR.ORG_NODEID AS SCHOOL_ORG_NODEID,
SCR.CUST_PROD_ID,
SCR.ASSESSMENTID,
SCR.CONTENTID,
SCR.SUBTESTID,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_NAME') AS SUBTEST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE') AS SUBTEST_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_SEQ') AS SUBTEST_SEQ,
SCR.GENDERID,
SCR.GRADEID,
SCR.LEVELID,
SCR.FORMID,
SCR.ADMINID,
SCR.SS,
SCR.PL,
SCR.PR,
SCR.NCR,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_LIST( P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID,P_FORMID=>SCR.FORMID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'OBJECTIVEID') AS OBJECTIVEIDS,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_LIST( P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID,P_FORMID=>SCR.FORMID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'PL') AS OBJ_PLS,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL1_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL1_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL1_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL1_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL2_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL2_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL2_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL2_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL3_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL3_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL3_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL3_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL4_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL4_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL4_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL4_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'TOTAL_RANGE', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS TOTAL_RANGE,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_BELOW_BASIC', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_BELOW_BASIC,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_BASIC', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_BASIC,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_PROFICIENT', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_PROFICIENT,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_ADVANCED', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_ADVANCED,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_EXAMINER( P_SUBTESTID=>SCR.SUBTESTID, P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO') AS EXAMINER,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_1',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUSTOMER_CODE=>'MO') AS BRAILLE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_2',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUSTOMER_CODE=>'MO') AS LARGE_PRINT,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE( P_DEMOCODE=>'Teach_Inval',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO') AS TEACHER_INVALIDATION,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Home_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO') AS HOME_SCHOOL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Private_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO') AS PRIVATE_SCHOOL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Race_Ethn',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUSTOMER_CODE=>'MO') AS ETHNICITYID,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_LTSN_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RES_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_CONCEPT_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_PROB_SLV_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_COMM_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_MAT_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_FRC_MTN_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_LVNG_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ECO_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'5', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ERTH_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'6', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_UNIV_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'7', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_SCINQ_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'8', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_IMPCT_PC,
SCR.DATETIMESTAMP
FROM SUBTEST_SCORE_FACT SCR;*/
CREATE MATERIALIZED VIEW MV_RPRT_STUD_DETAILS
REFRESH FAST ON DEMAND
AS
SELECT
SCR.SUBTEST_FACTID,
SCR.STUDENT_BIO_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'FIRST_NAME') AS FIRST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'LAST_NAME') AS LAST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'MIDDLE_NAME') AS MIDDLE_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'BIRTHDATE') AS BIRTHDATE,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'EXT_STUDENT_ID') AS EXT_STUDENT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'ORG_NODE_CODE') AS DISTRICT_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'ORG_NODE_NAME') AS DISTRICT_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'ORG_NODE_CODE') AS SCHOOL_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'ORG_NODE_NAME') AS SCHOOL_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICTID(P_ORG_NODEID =>SCR.ORG_NODEID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS DISTRICT_ORG_NODEID,
SCR.ORG_NODEID AS SCHOOL_ORG_NODEID,
SCR.CUST_PROD_ID,
SCR.ASSESSMENTID,
SCR.CONTENTID,
SCR.SUBTESTID,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_NAME') AS SUBTEST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE') AS SUBTEST_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_SEQ') AS SUBTEST_SEQ,
SCR.GENDERID,
SCR.GRADEID,
SCR.LEVELID,
SCR.FORMID,
SCR.ADMINID,
SCR.SS, --SCALE_SCORE
SCR.PL, --CONTENT_ACHIEVEMENT_LVL
SCR.PR,
SCR.NCR,--TOTAL_RAW_SCORE
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_LIST( P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID,P_FORMID=>SCR.FORMID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'OBJECTIVEID') AS OBJECTIVEIDS,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_LIST( P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID,P_FORMID=>SCR.FORMID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_COLUMNTYPE=>'PL') AS OBJ_PLS,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL1_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL1_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL1_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL1_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL2_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL2_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL2_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL2_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL3_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL3_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL3_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL3_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL4_LOW_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL4_LOW_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'PL4_HIGH_VAL', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS PL4_HIGH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'TOTAL_RANGE', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS TOTAL_RANGE,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_BELOW_BASIC', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_BELOW_BASIC,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_BASIC', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_BASIC,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_PROFICIENT', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_PROFICIENT,
PKG_RPRT_STUD_DETAILS.SF_GET_SCORE_RANGE( P_COLUMNTYPE =>'RANGE_ADVANCED', P_SUBTESTID=>SCR.SUBTESTID,P_GRADEID=>SCR.GRADEID, P_LEVELID=>SCR.LEVELID, P_CUST_PROD_ID=>SCR.CUST_PROD_ID) AS RANGE_ADVANCED,
SCR.EXAMINERID AS EXAMINER,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_1',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS BRAILLE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_2',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS LARGE_PRINT,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE( P_DEMOCODE=>'Teach_Inval',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS TEACHER_INVALIDATION,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Home_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS HOME_SCHOOL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Private_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS PRIVATE_SCHOOL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Race_Ethn',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ETHNICITYID,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_LTSN_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RES_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_CONCEPT_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_PROB_SLV_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_COMM_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_MAT_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_FRC_MTN_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_LVNG_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ECO_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'5', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ERTH_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'6', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_UNIV_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'7', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_SCINQ_PC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'8', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PC',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_IMPCT_PC,
--------------------------new columns added for DAT file generation-----------------------------------------------
PKG_RPRT_STUD_DETAILS.SF_GET_STATE_CODE(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID) AS STATE_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_TEST_TYPE(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID) AS TEST_TYPE,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VAL( P_DEMOCODE=>'City',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS CITY,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VAL( P_DEMOCODE=>'Curr_Sch_Yr',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS CURRENT_SCHOOL_YEAR,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'TEST_ELEMENT_ID') AS DRC_STUDENT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'INT_STUDENT_ID') AS LOCAL_STUDENT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID,P_GENDERID=>SCR.GENDERID,P_COLUMNTYPE=>'SPECIAL_CODES') AS SUFFIX,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'Race_Ethn',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS RACE_ETHNICITY,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'Home_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS HOME_SCH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'Private_Sch',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS PRIVATE_SCH_VAL,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_1',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_1,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_2',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_2,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_3',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_3,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_4',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_4,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_5',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_5,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_6',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_6,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_7',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_7,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_8',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_8,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_9',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_9,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'St_Use_10',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS STATE_USE_10,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'Period',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS PERIOD,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'Content_Form',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS CONTENT_FORM,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'PT_Content_Form',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS PT_CONTENT_FORM,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'Eductr_First_Nm',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS EXAMINER_FIRST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'Eductr_Last_Nm',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS EXAMINER_LAST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'Examiner_Email',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS EXAMINER_EMAIL,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VAL( P_DEMOCODE=>'Content_Exp_Dt',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS CONTENT_EXPORT_DATE_TIME,
SCR.TEST_DATE AS TEST_DATE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Precode_Flag',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS PRECODE_FLAG,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_1',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_1_BRAILLE_EDITION,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_2',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_2_LARGE_PRINT,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_3',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_3_ASL_A051,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_4',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_4_ASL_A052,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_5',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_5_PAPER_BASED,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_6',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_6_SPECIALIZED_CALCULATOR,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_7',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_7_ALTERNATE_RESPONSE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_8',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_8_BILINGUAL_DICTIONARY,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_9',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_9_COLOR_CONTRASTING_TEXT,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_10',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_10_COLOR_CHOOSER,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_11',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_11_COLOR_CONTRAST,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_12',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_12_COLOR_OVERLAY,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_13',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_13_MAGNIFICATION,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_14',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_14_MASKING_S106,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_15',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_15_MASKING_S107,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_16',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_16_READ_ALOUD_S041,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_17',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_17_READ_ALOUD_S042,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_18',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_18_READ_ALOUD_S111,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_19',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_19_SCRIBE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_20',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_20_SEPARATE_SETTING,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_21',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_21_TEST_DIRECTIONS,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_22',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_22_SUPPORT_TRANSLATION,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_23',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_23_SUPPORT_GLOSSARY,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_24',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_24_READ_ALOUD_A041,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_25',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_25_READ_ALOUD_A042,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_26',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_26_READ_ALOUD_A111,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_27',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_27_READ_ALOUD_A043,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_28',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_28_READ_ALOUD_A044,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_29',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_29_READ_ALOUD_A045,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_30',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_30_READ_ALOUD_A112,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_31',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_31_READ_ALOUD_A046,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_32',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_32_USE_OF_SCRIBE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_33',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_33_ABACUS,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_34',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_34_CALCULATOR_A392,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_35',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_35_CALCULATOR_A393,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_36',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_36_MULTIPLICATION_A394,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_37',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_37_MULTIPLICATION_A395,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'Accomm_38',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ACCOM_38_SPECIAL_CASE,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALUE(P_DEMOCODE=>'Absent',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ABSENT,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Item Responses for MC') AS ITEM_RESPONSE_MC,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Item Scores for MC') AS ITEM_SCORE_MC,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Raw Score for MC Items') AS ITEM_RAW_SCORE_MC,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Item Scores CR scores') AS ITEM_SCORE_CR,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Raw Score for CR Items') AS ITEM_RAW_SCORE_CR,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Item score for TE') AS ITEM_SCORE_TE,
PKG_RPRT_STUD_DETAILS.SF_GET_ITEM_SCORE(P_SUBTEST_ID=>SCR.SUBTESTID,P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_ITEMSET_NAME=>'Raw Score for TE Items') AS ITEM_RAW_SCORE_TE,
SCR.PC AS CONTENT_PERCENT_CORRECT,
SCR.STATUS_CODE AS CONTENT_COMPLETION_CRITERIA,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'01',1,NULL) AS OBJ_ELA_RD_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'01',2,NULL) AS OBJ_ELA_WR_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'01',3,NULL) AS OBJ_ELA_LTSN_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_LTSN_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_LTSN_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'01',4,NULL) AS OBJ_ELA_RES_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RES_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RES_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'02',1,NULL) AS OBJ_MA_CONCEPT_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_CONCEPT_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_CONCEPT_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'02',2,NULL) AS OBJ_MA_PROB_SLV_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_PROB_SLV_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_PROB_SLV_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'02',3,NULL) AS OBJ_MA_COMM_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_COMM_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_COMM_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',1,NULL) AS OBJ_SCI_MAT_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_MAT_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'1', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_MAT_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',2,NULL) AS OBJ_SCI_FRC_MTN_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_FRC_MTN_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'2', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_FRC_MTN_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',3,NULL) AS OBJ_SCI_LVNG_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_LVNG_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'3', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_LVNG_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',4,NULL) AS OBJ_SCI_ECO_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ECO_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'4', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ECO_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',5,NULL) AS OBJ_SCI_ERTH_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'5', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ERTH_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'5', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ERTH_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',6,NULL) AS OBJ_SCI_UNIV_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'6', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_UNIV_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'6', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_UNIV_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',7,NULL) AS OBJ_SCI_SCINQ_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'7', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_SCINQ_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'7', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_SCINQ_PL,
DECODE(PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE'),'03',8,NULL) AS OBJ_SCI_IMPCT_CD,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'8', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'NCR',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_IMPCT_NC,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_SCORE(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'8', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_IMPCT_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DEMO_VALUE( P_DEMOCODE=>'App_Ind',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_SUBTESTID=>SCR.SUBTESTID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS APPEAL_INDICATOR,
SCR.DATETIMESTAMP
FROM SUBTEST_SCORE_FACT SCR;

