GRANT SELECT ON ARTICLE_METADATA_SEQ TO PRISMGLOBAL;
GRANT SELECT,INSERT ON ARTICLE_METADATA TO PRISMGLOBAL;
GRANT SELECT,INSERT ON DEMOGRAPHIC TO PRISMGLOBAL;
GRANT SELECT,INSERT ON DEMOGRAPHIC_VALUES TO PRISMGLOBAL;
GRANT SELECT,INSERT ON ORG_NODE_DIM TO PRISMGLOBAL;

GRANT ALTER ON SUBTEST_SCORE_FACT TO PRISMGLOBAL;
GRANT ALTER ON OBJECTIVE_SCORE_FACT TO PRISMGLOBAL;
GRANT EXECUTE ON PKG_REBUILD_INDEXES TO PRISMGLOBAL;
GRANT SELECT ON CUTSCORE_SEQ TO PRISMGLOBAL;
GRANT SELECT,INSERT ON CUTSCORESCALESCORE TO PRISMGLOBAL; 
GRANT EXECUTE ON PRC_MV_REFRESH_SCORE_RANGE TO PRISMGLOBAL;
