-------------------TRIGGERS FOR LOADING PROJECTID FROM UI---------------
----(remember to change the schema name of global schema) 

CREATE OR REPLACE TRIGGER TRG_DASH_REPORTS
INSTEAD OF INSERT
ON DASH_REPORTS   
FOR EACH ROW 
DECLARE
BEGIN

  INSERT INTO prismglobal.DASH_REPORTS
    (DB_REPORTID,
     REPORT_NAME,
     REPORT_DESC,
     REPORT_TYPE,
     REPORT_FOLDER_URI,
     ACTIVATION_STATUS,
     PROJECTID,
     CREATED_DATE_TIME,
     UPDATED_DATE_TIME)
  VALUES
    (:new.DB_REPORTID,
     :new.REPORT_NAME,
     :new.REPORT_DESC,
     :new.REPORT_TYPE,
     :new.REPORT_FOLDER_URI,
     :new.ACTIVATION_STATUS,
     3,
     :new.CREATED_DATE_TIME,
     :new.UPDATED_DATE_TIME);

END;
/

CREATE OR REPLACE TRIGGER TRG_DASH_RPT_ACTION
  INSTEAD OF INSERT ON DASH_RPT_ACTION
  FOR EACH ROW
DECLARE
BEGIN

  INSERT INTO prismglobal.DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME,
     UPDATED_DATE_TIME)
  VALUES
    (:new.DB_ACTIONID,
     :new.ACTION_NAME,
     :new.ACTION_TYPE,
     :new.DESCRIPTION,
     3,
     :new.CREATED_DATE_TIME,
     :new.UPDATED_DATE_TIME);

END;
/ 

CREATE OR REPLACE TRIGGER TRG_DASH_MENU_RPT_ACCESS
  INSTEAD OF INSERT ON DASH_MENU_RPT_ACCESS
  FOR EACH ROW
DECLARE
BEGIN

INSERT INTO prismglobal.DASH_MENU_RPT_ACCESS
  (DB_MENUID,
   DB_REPORTID,
   ROLEID,
   ORG_LEVEL,
   CUST_PROD_ID,
   REPORT_SEQ,
   PROJECTID,
   ACTIVATION_STATUS,
   CREATED_DATE_TIME,
   UPDATED_DATE_TIME)
VALUES
  (:new.DB_MENUID,
   :new.DB_REPORTID,
   :new.ROLEID,
   :new.ORG_LEVEL,
   :new.CUST_PROD_ID,
   :new.REPORT_SEQ,
   3,
   :new.ACTIVATION_STATUS,
   :new.CREATED_DATE_TIME,
   :new.UPDATED_DATE_TIME);

END;

/

CREATE OR REPLACE TRIGGER TRG_DASH_ACTION_ACCESS
  INSTEAD OF INSERT ON DASH_ACTION_ACCESS
  FOR EACH ROW
DECLARE
BEGIN

  INSERT INTO prismglobal.DASH_ACTION_ACCESS
    (DB_ACT_ACCESSID,
     DB_MENUID,
     DB_REPORTID,
     DB_ACTIONID,
     ROLEID,
     ORG_LEVEL,
     CUST_PROD_ID,
     ACTION_SEQ,
     PROJECTID,
     ACTIVATION_STATUS,
     CREATED_DATE_TIME,
     UPDATED_DATE_TIME)
  VALUES
    (:new.DB_ACT_ACCESSID,
     :new.DB_MENUID,
     :new.DB_REPORTID,
     :new.DB_ACTIONID,
     :new.ROLEID,
     :new.ORG_LEVEL,
     :new.CUST_PROD_ID,
     :new.ACTION_SEQ,
     3,
     :new.ACTIVATION_STATUS,
     :new.CREATED_DATE_TIME,
     :new.UPDATED_DATE_TIME);

END;

/

CREATE OR REPLACE TRIGGER TRG_CUSTOMER_INFO
  INSTEAD OF INSERT ON CUSTOMER_INFO
  FOR EACH ROW
DECLARE
BEGIN

  INSERT INTO prismglobal.CUSTOMER_INFO
    (CUSTOMERID,
     CUSTOMER_NAME,
     DISPLAY_TP_SELECTION,
     FILE_LOCATION,
     SUPPORT_EMAIL,
     PROJECTID,
     SEND_LOGIN_PDF,
     DATETIMESTAMP)
  VALUES
    (:new.CUSTOMERID,
     :new.CUSTOMER_NAME,
     :new.DISPLAY_TP_SELECTION,
     :new.FILE_LOCATION,
     :new.SUPPORT_EMAIL,
     3,
     :new.SEND_LOGIN_PDF,
     :new.DATETIMESTAMP);

END;

/