DECLARE
V_NO NUMBER :=0;
V_CUST_ID NUMBER :=0;
BEGIN
SELECT C.CUSTOMERID INTO V_CUST_ID
  FROM CUSTOMER_INFO C
 WHERE C.CUSTOMER_CODE = 'MO';
--State Use 1
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_1','St_Use_1','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);
--State Use 2
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_2','St_Use_2','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);
--State Use 3 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_3','St_Use_3','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);
--State Use 4 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_4','St_Use_4','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);
--State Use 5 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_5','St_Use_5','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);




--State Use 6 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_6','St_Use_6','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--State Use 7 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_7','St_Use_7','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--State Use 8
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_8','St_Use_8','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--State Use 9 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_9','St_Use_9','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--State Use 10 
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'State_Use_10','St_Use_10','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Teacher Invalidation 

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Teach_Invalidation','Teach_Inval','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Absent   

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Absent','Absent','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Home School 

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Home_School','Home_Sch','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Race_Ethn


INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Race_Ethn','Race_Ethn','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Asian','A',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Black','B',2,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Hispanic','H',3,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Indian (American Indian or Alaskan Native)','I',4,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'White','W',5,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Native Hawaiian or Other Pacific Islander','P',6,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Multi-Racial','M',7,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',8,'N',SYSDATE);
--Private School

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Private_School','Private_Sch','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Current School Year
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Current_School_Year','Curr_Sch_Yr','PP',V_CUST_ID,'','','N',SYSDATE);

--Educator_First_Name_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorFirstName_ELA','Eductr_First_Nm_ELA','PP',V_CUST_ID,'2054','','N',SYSDATE);

--Educator_First_Name_MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorFirstName_MA','Eductr_First_Nm_MA','PP',V_CUST_ID,'2055','','N',SYSDATE);

--Educator_First_Name_SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorFirstName_SCI','Eductr_First_Nm_SCI','PP',V_CUST_ID,'2056','','N',SYSDATE);

--Educator_Last_Name_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorLastName_ELA','Eductr_Last_Nm_ELA','PP',V_CUST_ID,'2054','','N',SYSDATE);

--Educator_Last_Name_MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorLastName_MA','Eductr_Last_Nm_MA','PP',V_CUST_ID,'2055','','N',SYSDATE);

--Educator_Last_Name_SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'EducatorLastName_SCI','Eductr_Last_Nm_SCI','PP',V_CUST_ID,'2056','','N',SYSDATE);

--Educator_Email_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'ExaminerEmail_ELA','Examiner_Email_ELA','PP',V_CUST_ID,'2054','','N',SYSDATE);

--Educator_Email_MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'ExaminerEmail_MA','Examiner_Email_MA','PP',V_CUST_ID,'2055','','N',SYSDATE);

--Educator_Email_SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'ExaminerEmail_SCI','Examiner_Email_SCI','PP',V_CUST_ID,'2056','','N',SYSDATE);


--PERIOD
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Period','Period','PP',V_CUST_ID,'','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'01','01',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'02','02',2,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'03','03',3,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'04','04',4,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'05','05',5,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'06','06',6,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'07','07',7,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'08','08',8,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'09','09',9,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'10','10',10,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',11,'N',SYSDATE);

--PRECODE FLAG ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Precode_Flag_ELA','Precode_Flag_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--PRECODE FLAG MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Precode_Flag_MA','Precode_Flag_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--PRECODE FLAG SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Precode_Flag_SCI','Precode_Flag_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Appeal Indicator ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Appeal_Indicator_ELA','App_Ind_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'X','X',2,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',3,'N',SYSDATE);

--Appeal Indicator MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Appeal_Indicator_MA','App_Ind_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'X','X',2,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',3,'N',SYSDATE);

--Appeal Indicator SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Appeal_Indicator_SCI','App_Ind_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'X','X',2,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',3,'N',SYSDATE);

--Content_Form_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Content_Form_ELA','Content_Form_ELA','PP',V_CUST_ID,'2054','','N',SYSDATE);
--Content_Form_MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Content_Form_MA','Content_Form_MA','PP',V_CUST_ID,'2055','','N',SYSDATE);
--Content_Form_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Content_Form_SCI','Content_Form_SCI','PP',V_CUST_ID,'2056','','N',SYSDATE);



--PT_Content_Form_ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'PT_Content_Form_ELA','PT_Content_Form_ELA','PP',V_CUST_ID,'2054','','N',SYSDATE);
--PT_Content_Form_MA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'PT_Content_Form_MA','PT_Content_Form_MA','PP',V_CUST_ID,'2055','','N',SYSDATE);
--PT_Content_Form_SCI
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'PT_Content_Form_SCI','PT_Content_Form_SCI','PP',V_CUST_ID,'2056','','N',SYSDATE);

--City
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'City','City','PP',V_CUST_ID,'','','N',SYSDATE);


--Accommodation 1 ELA
INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Braille_Edition_ELA','Accomm_1_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 2 ELA


INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Large_Print_ELA','Accomm_2_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 3 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A051_ELA','Accomm_3_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 4 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A052_ELA','Accomm_4_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 5 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Paper_Based_ELA','Accomm_5_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 6 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Specialized_Calculator_ELA','Accomm_6_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 7 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Alternate_Response_ELA','Accomm_7_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 8 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Bilingual_Dictionary_ELA','Accomm_8_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 9 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrasting_Text_ELA','Accomm_9_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 10 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Chooser_ELA','Accomm_10_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 11 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrast_ELA','Accomm_11_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 12 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Overlay_ELA','Accomm_12_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 13 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Magnification_ELA','Accomm_13_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 14 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S106_ELA','Accomm_14_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 15 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S107_ELA','Accomm_15_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 16 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S041_ELA','Accomm_16_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 17 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S042_ELA','Accomm_17_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 18 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S111_ELA','Accomm_18_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 19 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Scribe_ELA','Accomm_19_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 20 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Separate_Setting_ELA','Accomm_20_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 21 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Test_Directions_ELA','Accomm_21_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 22 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Translation_ELA','Accomm_22_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 23 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Glossary_ELA','Accomm_23_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 24 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A041_ELA','Accomm_24_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 25 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A042_ELA','Accomm_25_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 26 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A111_ELA','Accomm_26_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 27 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A043_ELA','Accomm_27_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 28 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A044_ELA','Accomm_28_ELA','OL',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 29 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A045_ELA','Accomm_29_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 30 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A112_ELA','Accomm_30_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 31 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A046_ELA','Accomm_31_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 32 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Use_Of _Scribe_ELA','Accomm_32_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 33 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Abacus_ELA','Accomm_33_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 34 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A392_ELA','Accomm_34_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 35 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A393_ELA','Accomm_35_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 36 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A394_ELA','Accomm_36_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 37 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A395_ELA','Accomm_37_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 38 ELA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Special_Case_Paper_Based_ELA','Accomm_38_ELA','PP',V_CUST_ID,'2054','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 1 maths

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Braille_ Edition_MA','Accomm_1_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 2 MA


INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Large_ Print_MA','Accomm_2_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 3 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A051_MA','Accomm_3_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 4 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A052_MA','Accomm_4_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 5 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Paper_Based_MA','Accomm_5_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 6 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Specialized_Calculator_MA','Accomm_6_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 7 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Alternate_Response_Options_MA','Accomm_7_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 8 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Bilingual_Dictionary_MA','Accomm_8_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 9 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrasting_Text_MA','Accomm_9_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 10 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Chooser_MA','Accomm_10_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 11 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrast_MA','Accomm_11_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 12 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Overlay_MA','Accomm_12_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 13 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Magnification_MA','Accomm_13_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 14 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S106_MA','Accomm_14_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 15 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S107_MA','Accomm_15_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 16 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S041­_MA','Accomm_16_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 17 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S042_MA','Accomm_17_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 18 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S111_MA','Accomm_18_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 19 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Scribe_MA','Accomm_19_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 20 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Separate_Setting_MA','Accomm_20_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 21 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Test_Directions_MA','Accomm_21_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 22 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Translation_MA','Accomm_22_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 23 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Glossary_MA','Accomm_23_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 24 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A041_MA','Accomm_24_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 25 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A042_MA','Accomm_25_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 26 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A111_MA','Accomm_26_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 27 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A043_MA','Accomm_27_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 28 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A044_MA','Accomm_28_MA','OL',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 29 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A045_MA','Accomm_29_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 30 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A112_MA','Accomm_30_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 31 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A046_MA','Accomm_31_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 32 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Use_Of _Scribe_MA','Accomm_32_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 33 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Abacus_MA','Accomm_33_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 34 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A392_MA','Accomm_34_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 35 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A393_MA','Accomm_35_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 36 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A394_MA','Accomm_36_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 37 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A395_MA','Accomm_37_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 38 MA

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Special_Case_Paper_Based_MA','Accomm_38_MA','PP',V_CUST_ID,'2055','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 1 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Braille_Edition_SCI','Accomm_1_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 2 SCI


INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Large_Print_SCI','Accomm_2_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 3 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A051_SCI','Accomm_3_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 4 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Signing_Of_Assessment_A052_SCI','Accomm_4_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 5 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Paper_Based_SCI','Accomm_5_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 6 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Specialized_Calculator_SCI','Accomm_6_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 7 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Alternate_Response_Options_SCI','Accomm_7_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 8 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Bilingual_Dictionary_SCI','Accomm_8_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 9 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrasting_Text_SCI','Accomm_9_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 10 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Chooser_SCI','Accomm_10_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 11 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Contrast_SCI','Accomm_11_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 12 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Color_Overlay_SCI','Accomm_12_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 13 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Magnification_SCI','Accomm_13_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 14 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S106_SCI','Accomm_14_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 15 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Masking_S107_SCI','Accomm_15_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 16 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S041_SCI','Accomm_16_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 17 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S042_SCI','Accomm_17_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 18 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_S111_SCI','Accomm_18_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 19 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Scribe_SCI','Accomm_19_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 20 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Separate_Setting_SCI','Accomm_20_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 21 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Test_Directions_SCI','Accomm_21_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 22 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Translation_SCI','Accomm_22_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 23 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Support_Glossary_Sci','Accomm_23_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 24 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A041_SCI','Accomm_24_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 25 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A042_SCI','Accomm_25_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 26 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A111_SCI','Accomm_26_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 27 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A043_SCI','Accomm_27_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 28 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A044_SCI','Accomm_28_SCI','OL',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);



--Accommodation 29 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A045_SCI','Accomm_29_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 30 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A112_SCI','Accomm_30_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 31 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Read_Aloud_A046_SCI','Accomm_31_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 32 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Use_Of _Scribe_SCI','Accomm_32_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 33 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Abacus_SCI','Accomm_33_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

--Accommodation 34 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A392_SCI','Accomm_34_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 35 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Calculator_A393_SCI','Accomm_35_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 36 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A394_SCI','Accomm_36_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 37 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Multiplication_A395_SCI','Accomm_37_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);


--Accommodation 38 SCI

INSERT INTO DEMOGRAPHIC VALUES(SEQ_DEMOID.NEXTVAL,'Special_Case_Paper_Based_SCI','Accomm_38_SCI','PP',V_CUST_ID,'2056','','Y',SYSDATE)
RETURNING DEMOID INTO V_NO;
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,'Y','Y',1,'N',SYSDATE);
INSERT INTO DEMOGRAPHIC_VALUES VALUES(SEQ_DEMO_VALID.NEXTVAL,V_NO,' ','<BLANK>',2,'N',SYSDATE);

COMMIT;
END;