----Remember to change the global schema name
ALTER TABLE ORG_NODE_DIM  ADD CONSTRAINT PK_ORG_NODE_DIM PRIMARY KEY (ORG_NODEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_NODE_DIM  ADD CONSTRAINT FK_ORG_NODE_DIM_2 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE ORG_NODE_DIM  ADD CONSTRAINT FK_ORG_NODE_DIM_3 FOREIGN KEY (PARENT_ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID); 

ALTER TABLE ORG_PRODUCT_LINK  ADD CONSTRAINT PK_ORG_PRODUCT_LINK PRIMARY KEY (ORG_PROD_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_PRODUCT_LINK  ADD CONSTRAINT FK_ORG_PRODUCT_LINK_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ORG_PRODUCT_LINK  ADD CONSTRAINT FK_ORG_PRODUCT_LINK_2 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);


ALTER TABLE ORG_LSTNODE_LINK ADD CONSTRAINT PK_ORG_LSTNODE_LINK PRIMARY KEY (ORG_NODEID, ORG_LSTNODEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_LSTNODE_LINK ADD CONSTRAINT FK_ORG_LSTNODE_LINK_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ORG_LSTNODE_LINK ADD CONSTRAINT FK_ORG_LSTNODE_LINK_2 FOREIGN KEY (ORG_LSTNODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ORG_LSTNODE_LINK ADD CONSTRAINT FK_ORG_LSTNODE_LINK_3 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);

ALTER TABLE ORG_TEST_PROGRAM_LINK ADD CONSTRAINT PK_ORG_TEST_PROGRAM_LINK PRIMARY KEY (ORG_NODEID, TP_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_TEST_PROGRAM_LINK ADD CONSTRAINT FK_ORG_TEST_PROGRAM_LINK_1 FOREIGN KEY (TP_ID) REFERENCES prismglobal.TEST_PROGRAM (TP_ID);
ALTER TABLE ORG_TEST_PROGRAM_LINK ADD CONSTRAINT FK_ORG_TEST_PROGRAM_LINK_2 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (USERID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_1 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID); 
ALTER TABLE USERS ADD CONSTRAINT CHK_IS_FIRSTTIME_LOGIN CHECK (IS_FIRSTTIME_LOGIN IN ('Y', 'N'));
ALTER TABLE USERS ADD CONSTRAINT CHK_IS_NEW_USER CHECK (IS_NEW_USER IN ('Y', 'N'));

ALTER TABLE ORG_USERS ADD CONSTRAINT PK_ORG_USERS PRIMARY KEY (ORG_USER_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_USERS ADD CONSTRAINT FK_ORG_USERS_1 FOREIGN KEY (USERID) REFERENCES USERS (USERID);
ALTER TABLE ORG_USERS ADD CONSTRAINT FK_ORG_USERS_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE ORG_USERS ADD CONSTRAINT FK_ORG_USERS_3 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ORG_USERS ADD CONSTRAINT CHK_ACT_STS_ORG_USERS CHECK (ACTIVATION_STATUS IN ('AC', 'IN'));

ALTER TABLE EDU_CENTER_DETAILS ADD CONSTRAINT PK_EDU_CENTER_DETAILS PRIMARY KEY (EDU_CENTERID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE EDU_CENTER_DETAILS ADD CONSTRAINT FK_EDU_CENTER_DETAILS_1 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);

ALTER TABLE EDU_CENTER_USER_LINK ADD CONSTRAINT PK_EDU_CENTER_USER_LINK PRIMARY KEY (EDU_CENTERID, USERID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE EDU_CENTER_USER_LINK ADD CONSTRAINT FK_EDU_USER_STU_LINK_1 FOREIGN KEY (EDU_CENTERID) REFERENCES EDU_CENTER_DETAILS (EDU_CENTERID);
ALTER TABLE EDU_CENTER_USER_LINK ADD CONSTRAINT FK_EDU_USER_STU_LINK_2 FOREIGN KEY (USERID)
  REFERENCES USERS (USERID);
ALTER TABLE EDU_CENTER_USER_LINK ADD CONSTRAINT FK_EDU_USER_STU_LINK_3 FOREIGN KEY (CUST_PROD_ID)
  REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);  

ALTER TABLE STUDENT_BIO_DIM ADD CONSTRAINT PK_STUDENT_BIO_DIM PRIMARY KEY (STUDENT_BIO_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STUDENT_BIO_DIM ADD CONSTRAINT FK_STUDENT_BIO_DIM_1 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT FK_STUDENT_BIO_DIM_2 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT FK_STUDENT_BIO_DIM_3 FOREIGN KEY (GENDERID) REFERENCES prismglobal.GENDER_DIM (GENDERID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT FK_STUDENT_BIO_DIM_4 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT FK_STUDENT_BIO_DIM_5 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT FK_STUDENT_BIO_DIM_6 FOREIGN KEY (EDU_CENTERID) REFERENCES EDU_CENTER_DETAILS (EDU_CENTERID);
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT CHK_BIO_UPDATE_CMPL CHECK (IS_BIO_UPDATE_CMPL IN ('Y', 'N'));
ALTER TABLE STUDENT_BIO_DIM  ADD CONSTRAINT CHK_STUDENT_MODE CHECK (STUDENT_MODE IN ('OL','PP'));

ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT PK_SUBTEST_SCORE_FACT PRIMARY KEY (SUBTEST_FACTID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_1 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_3 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_5 FOREIGN KEY (GENDERID) REFERENCES prismglobal.GENDER_DIM (GENDERID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_6 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_7 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_8 FOREIGN KEY (FORMID) REFERENCES prismglobal.FORM_DIM (FORMID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_9 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_10 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_11 FOREIGN KEY (ASSESSMENTID) REFERENCES prismglobal.ASSESSMENT_DIM (ASSESSMENTID);
---ADDED FOR MO
ALTER TABLE SUBTEST_SCORE_FACT  ADD CONSTRAINT FK_SUBTEST_SCORE_FACT_12 FOREIGN KEY (EXAMINERID) REFERENCES EXAMINER_DIM (EXAMINERID);
  
  


ALTER TABLE OBJECTIVE_SCORE_FACT ADD CONSTRAINT PK_OBJECTIVE_SCORE_FACT PRIMARY KEY (OBJECTIVE_FACTID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_1 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_10 FOREIGN KEY (FORMID) REFERENCES prismglobal.FORM_DIM (FORMID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_11 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_12 FOREIGN KEY (ASSESSMENTID) REFERENCES prismglobal.ASSESSMENT_DIM (ASSESSMENTID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_13 FOREIGN KEY (CONDCODE_ID) REFERENCES prismglobal.CONDITION_CODES (CONDCODE_ID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_2 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_5 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_6 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_7 FOREIGN KEY (GENDERID) REFERENCES prismglobal.GENDER_DIM (GENDERID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_8 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);
ALTER TABLE OBJECTIVE_SCORE_FACT  ADD CONSTRAINT FK_OBJECTIVE_SCORE_FACT_9 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);


ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT PK_ITEM_SCORE_FACT PRIMARY KEY (ITEM_FACTID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_1 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_10 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_11 FOREIGN KEY (ITEMSETID) REFERENCES prismglobal.ITEMSET_DIM (ITEMSETID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_12 FOREIGN KEY (ASSESSMENTID) REFERENCES prismglobal.ASSESSMENT_DIM (ASSESSMENTID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_13 FOREIGN KEY (READID) REFERENCES prismglobal.READ_DIM (READID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_2 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);


ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_5 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_6 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_7 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_8 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE ITEM_SCORE_FACT  ADD CONSTRAINT FK_ITEM_SCORE_FACT_9 FOREIGN KEY (FORMID) REFERENCES prismglobal.FORM_DIM (FORMID);

ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT PK_GRADE_SELECTION_LOOKUP PRIMARY KEY (ORG_NODEID, ASSESSMENTID, ADMINID, GRADEID, LEVELID, FORMID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_2 FOREIGN KEY (ASSESSMENTID) REFERENCES prismglobal.ASSESSMENT_DIM (ASSESSMENTID);
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_3 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_4 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_5 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE GRADE_SELECTION_LOOKUP  ADD CONSTRAINT FK_GRADE_SELECTION_LOOKUP_6 FOREIGN KEY (FORMID) REFERENCES prismglobal.FORM_DIM (FORMID);

ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT PK_DEMOGRAPHIC PRIMARY KEY (DEMOID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT DEMO_CODE_UK UNIQUE (DEMO_CODE, CUSTOMERID);
ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT FK_DEMOGRAPHIC_1 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT FK_DEMOGRAPHIC_2 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT CHK_DEMO_MODE CHECK (DEMO_MODE IN ('OL','PP','BO'));
ALTER TABLE DEMOGRAPHIC ADD CONSTRAINT CHK_DEMO_VALUE_AVL CHECK (IS_DEMO_VALUE_AVL IN ('N','Y'));

ALTER TABLE DEMOGRAPHIC_VALUES ADD CONSTRAINT PK_DEMOGRAPHIC_VALUES PRIMARY KEY (DEMO_VALID, DEMOID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE DEMOGRAPHIC_VALUES ADD CONSTRAINT FK_DEMOGRAPHIC_VALUES_1 FOREIGN KEY (DEMOID) REFERENCES DEMOGRAPHIC (DEMOID); 
ALTER TABLE DEMOGRAPHIC_VALUES ADD CONSTRAINT CHK_DEMO_DEFAULT CHECK (IS_DEFAULT IN ('N','Y'));

ALTER TABLE STU_SUBTEST_DEMO_VALUES
  ADD CONSTRAINT PK_STU_SUBTEST_DEMO_VALUES PRIMARY KEY (STU_TST_DEMO_VALID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STU_SUBTEST_DEMO_VALUES ADD CONSTRAINT FK_STU_SUBTEST_DEMO_VALUES_1 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE STU_SUBTEST_DEMO_VALUES ADD CONSTRAINT FK_STU_SUBTEST_DEMO_VALUES_2 FOREIGN KEY (DEMO_VALID, DEMOID) REFERENCES DEMOGRAPHIC_VALUES (DEMO_VALID, DEMOID);
ALTER TABLE STU_SUBTEST_DEMO_VALUES ADD CONSTRAINT FK_STU_SUBTEST_DEMO_VALUES_3 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE STUDENT_PDF_FILES ADD CONSTRAINT PK_STUDENT_PDF_FILES PRIMARY KEY (STU_PDF_FILEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STUDENT_PDF_FILES ADD CONSTRAINT FK_STUDENT_PDF_FILES_1 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE STUDENT_PDF_FILES ADD CONSTRAINT FK_STUDENT_PDF_FILES_2 FOREIGN KEY (PDF_REPORTID) REFERENCES prismglobal.PDF_REPORTS (PDF_REPORTID);
ALTER TABLE STUDENT_PDF_FILES ADD CONSTRAINT FK_STUDENT_PDF_FILES_3 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);


ALTER TABLE STUDENT_DEMO_VALUES ADD CONSTRAINT PK_STUDENT_DEMO_VALUES PRIMARY KEY (STU_DEMO_VALID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STUDENT_DEMO_VALUES ADD CONSTRAINT FK_STUDENT_DEMO_VALUES_1 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE STUDENT_DEMO_VALUES ADD CONSTRAINT FK_STUDENT_DEMO_VALUES_2 FOREIGN KEY (DEMO_VALID, DEMOID) REFERENCES DEMOGRAPHIC_VALUES (DEMO_VALID, DEMOID);

ALTER TABLE ORG_PDF_FILES ADD CONSTRAINT PK_ORG_PDF_FILES PRIMARY KEY (ORG_PDF_FILEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ORG_PDF_FILES ADD CONSTRAINT FK_ORG_PDF_FILES_1 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE ORG_PDF_FILES ADD CONSTRAINT FK_ORG_PDF_FILES_3 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);

ALTER TABLE INVITATION_CODE ADD CONSTRAINT PK_INVITATION_CODE PRIMARY KEY (ICID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_IC_ORGNODEID FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE INVITATION_CODE ADD CONSTRAINT CHK_ACT_STS_IC CHECK (ACTIVATION_STATUS IN ('AC', 'IN'));
ALTER TABLE INVITATION_CODE ADD CONSTRAINT CHK_IS_NEW_IC CHECK (IS_NEW_IC IN ('Y', 'N'));

ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT FK_INVITATION_CODE_CLAIM_2 FOREIGN KEY (ORG_USER_ID) REFERENCES ORG_USERS (ORG_USER_ID); 
ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT CHK_ACT_STS_IC_CLAIM CHECK (ACTIVATION_STATUS IN ('AC', 'IN'));

ALTER TABLE USER_ROLE ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY (USERID, ROLEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_1 FOREIGN KEY (ROLEID) REFERENCES prismglobal.ROLE (ROLEID);
ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_2 FOREIGN KEY (USERID) REFERENCES USERS (USERID);

ALTER TABLE PWD_HINT_ANSWERS ADD CONSTRAINT PK_PWD_HINT_ANSWERS PRIMARY KEY (PH_ANSWERID, USERID, PH_QUESTIONID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE PWD_HINT_ANSWERS ADD CONSTRAINT FK_PWD_HINT_ANSWERS_1 FOREIGN KEY (PH_QUESTIONID) REFERENCES prismglobal.PWD_HINT_QUESTIONS (PH_QUESTIONID);
ALTER TABLE PWD_HINT_ANSWERS ADD CONSTRAINT FK_PWD_HINT_ANSWERS_2 FOREIGN KEY (USERID) REFERENCES USERS (USERID);  

ALTER TABLE ARTICLE_CONTENT ADD CONSTRAINT PK_ARTICLE_CONTENT PRIMARY KEY (ARTICLE_CONTENT_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ARTICLE_CONTENT ADD CONSTRAINT FK_ARTICLE_CONTENT_1 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);

ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT PK_ARTICLE_METADATA PRIMARY KEY (ARTICLEID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT FK_ARTICLE_METADATA_1 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT FK_ARTICLE_METADATA_2 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT FK_ARTICLE_METADATA_3 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT FK_ARTICLE_METADATA_4 FOREIGN KEY (SUBT_OBJ_MAPID) REFERENCES prismglobal.SUBTEST_OBJECTIVE_MAP (SUBT_OBJ_MAPID);
ALTER TABLE ARTICLE_METADATA ADD CONSTRAINT FK_ARTICLE_METADATA_5 FOREIGN KEY (ARTICLE_CONTENT_ID) REFERENCES ARTICLE_CONTENT (ARTICLE_CONTENT_ID);

ALTER TABLE USER_ACTIVITY_HISTORY ADD CONSTRAINT PK_USER_ACTIVITY_HISTORY PRIMARY KEY (ACTIVITYID) using index TABLESPACE FCAT_IDX1;
--delete from user_activity_history uh where not exists (select 1 from users u where u.userid=uh.userid);
ALTER TABLE USER_ACTIVITY_HISTORY ADD CONSTRAINT FK_USER_ACTIVITY_HISTORY_1 FOREIGN KEY (USERID) REFERENCES USERS (USERID);
ALTER TABLE USER_ACTIVITY_HISTORY ADD CONSTRAINT FK_USER_ACTIVITY_HISTORY_2 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE USER_ACTIVITY_HISTORY ADD CONSTRAINT FK_USER_ACTIVITY_HISTORY_3 FOREIGN KEY (ACTY_TYPEID) REFERENCES prismglobal.ACTIVITY_TYPE (ACTY_TYPEID);

ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT PK_RESCORE_REQUEST_FORM PRIMARY KEY (RRF_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_1 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_10 FOREIGN KEY (ITEMSETID) REFERENCES prismglobal.ITEMSET_DIM (ITEMSETID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_11 FOREIGN KEY (REQUESTED_USERID) REFERENCES USERS (USERID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_2 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_3 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_4 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_5 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_6 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_7 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_8 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE RESCORE_REQUEST_FORM ADD CONSTRAINT FK_RESCORE_REQUEST_FORM_9 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);

ALTER TABLE JOB_TRACKING ADD CONSTRAINT PK_JOB_TRACKING PRIMARY KEY (JOB_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE JOB_TRACKING ADD CONSTRAINT FK_JOB_TRACKING_1 FOREIGN KEY (USERID) REFERENCES USERS (USERID);
ALTER TABLE JOB_TRACKING ADD CONSTRAINT FK_JOB_TRACKING_2 FOREIGN KEY (CUSTOMERID) REFERENCES prismglobal.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE JOB_TRACKING ADD CONSTRAINT FK_JOB_TRACKING_3 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_EXTRACT_CATEGORY CHECK (EXTRACT_CATEGORY IN ('TTD','PD','AE'));
ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_EXTRACT_FILETYPE CHECK (EXTRACT_FILETYPE IN ('DAT','XML','ICL','ISR','IPR','BOTH','CR'));

ALTER TABLE BIO_STUDENT_EXTRACT ADD CONSTRAINT PK_BIO_EXTRACTID PRIMARY KEY (BIO_EXTRACTID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE BIO_STUDENT_EXTRACT ADD CONSTRAINT FK_BIO_STUDENT_EXTRACT_1 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);

ALTER TABLE STATE_MEAN_IPI_SCORE ADD CONSTRAINT PK_STATE_MEAN_IPI_SCORE PRIMARY KEY (STATE_MEAN_IPI_SCOREID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STATE_MEAN_IPI_SCORE ADD CONSTRAINT FK_STATE_MEAN_IPI_SCORE_1 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE STATE_MEAN_IPI_SCORE ADD CONSTRAINT FK_STATE_MEAN_IPI_SCORE_2 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE STATE_MEAN_IPI_SCORE ADD CONSTRAINT FK_STATE_MEAN_IPI_SCORE_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE STATE_MEAN_IPI_SCORE ADD CONSTRAINT FK_STATE_MEAN_IPI_SCORE_4 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);

ALTER TABLE DISAGGREGATION_CATEGORY ADD CONSTRAINT DISAGGREGATIONCATEGORYID PRIMARY KEY (DISAGGREGATIONCATEGORYID) using index TABLESPACE FCAT_IDX1;

ALTER TABLE DISAGGREGATION_CATEGORY_TYPE ADD CONSTRAINT DISAGGREGATIONCATEGORYTYPEID PRIMARY KEY (DISAGGREGATIONCATEGORYTYPEID) using index TABLESPACE FCAT_IDX1;

ALTER TABLE ASFD_FACT ADD CONSTRAINT PK_ASFD_FACT PRIMARY KEY (ASFD_ID) using index TABLESPACE FCAT_IDX1; 
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_4 FOREIGN KEY (SUBTESTID)  REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_5 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_6 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_7 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_8 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE ASFD_FACT ADD CONSTRAINT FK_ASFD_FACT_9 FOREIGN KEY (ITEMSETID)  REFERENCES prismglobal.ITEMSET_DIM (ITEMSETID);

ALTER TABLE STFD_FACT ADD CONSTRAINT STFD_FACT_PK PRIMARY KEY (STFD_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_5 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_6 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE STFD_FACT ADD CONSTRAINT FK_STFD_FACT_7 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);

ALTER TABLE DISA_FACT ADD CONSTRAINT DISA_FACT_PK PRIMARY KEY (DISA_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_3 FOREIGN KEY (CONTENTID)  REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_4 FOREIGN KEY (SUBTESTID)  REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_5 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_6 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE DISA_FACT ADD CONSTRAINT FK_DISA_FACT_7 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);

ALTER TABLE SPPR_FACT ADD CONSTRAINT SPPR_FACT_PK PRIMARY KEY (SPPR_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_5 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_6 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE SPPR_FACT ADD CONSTRAINT FK_SPPR_FACT_7 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);

ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT ACAD_STD_SUMM_FACT_PK PRIMARY KEY (AS_SUMM_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_3 FOREIGN KEY (CONTENTID) REFERENCES prismglobal.CONTENT_DIM (CONTENTID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_4 FOREIGN KEY (SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_5 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_6 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_7 FOREIGN KEY (OBJECTIVEID) REFERENCES prismglobal.OBJECTIVE_DIM (OBJECTIVEID);
ALTER TABLE ACAD_STD_SUMM_FACT ADD CONSTRAINT FK_ACAD_STD_SUMM_FACT_8 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);

ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT UDTR_ROSTER_FACT_PK PRIMARY KEY (UDTR_ROSTER_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_10 FOREIGN KEY (SOCIAL_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_4 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_5 FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_6 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_7 FOREIGN KEY (ENGLANG_ARTS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_8 FOREIGN KEY (MATHEMATICS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_ROSTER_FACT ADD CONSTRAINT FK_UDTR_ROSTER_FACT_9 FOREIGN KEY (SCIENCE_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT UDTR_SUMM_FACT_PK PRIMARY KEY (UDTR_SUMM_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_4 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_5 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_6 FOREIGN KEY (ENGLANG_ARTS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_7 FOREIGN KEY (MATHEMATICS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_8 FOREIGN KEY (SCIENCE_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE UDTR_SUMM_FACT ADD CONSTRAINT FK_UDTR_SUMM_FACT_9 FOREIGN KEY (SOCIAL_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT CLASS_SUMM_FACT_PK PRIMARY KEY (CLASS_SUMM_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_4 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_5 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_6 FOREIGN KEY (ENGLANG_ARTS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_7 FOREIGN KEY (MATHEMATICS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_8 FOREIGN KEY (SCIENCE_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE CLASS_SUMM_FACT ADD CONSTRAINT FK_CLASS_SUMM_FACT_9 FOREIGN KEY (SOCIAL_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE SUMT_FACT ADD CONSTRAINT SUMT_FACT_PK PRIMARY KEY (SUMT_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_4 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_5 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_6 FOREIGN KEY (ENGLANG_ARTS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_7 FOREIGN KEY (MATHEMATICS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_8 FOREIGN KEY (SCIENCE_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE SUMT_FACT ADD CONSTRAINT FK_SUMT_FACT_9 FOREIGN KEY (SOCIAL_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE MEDIA_FACT ADD CONSTRAINT MEDIA_FACT_PK PRIMARY KEY (MEDIA_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_1 FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM (ORG_NODEID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_2 FOREIGN KEY (ADMINID) REFERENCES prismglobal.ADMIN_DIM (ADMINID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_3 FOREIGN KEY (GRADEID) REFERENCES prismglobal.GRADE_DIM (GRADEID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_4 FOREIGN KEY (LEVELID) REFERENCES prismglobal.LEVEL_DIM (LEVELID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_5 FOREIGN KEY (CUST_PROD_ID) REFERENCES prismglobal.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_6 FOREIGN KEY (ENGLANG_ARTS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_7 FOREIGN KEY (MATHEMATICS_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_8 FOREIGN KEY (SCIENCE_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);
ALTER TABLE MEDIA_FACT ADD CONSTRAINT FK_MEDIA_FACT_9 FOREIGN KEY (SOCIAL_SUBTESTID) REFERENCES prismglobal.SUBTEST_DIM (SUBTESTID);

ALTER TABLE RESULTS_GRT_FACT ADD CONSTRAINT PK_RESULTS_GRT_FACT PRIMARY KEY (RESULTS_GRTID) using index TABLESPACE FCAT_IDX1;

alter table TABLE_1_STU add primary key (STUDENT_BIO_ID, SUBTESTID) using index TABLESPACE FCAT_IDX1;

alter table STUDENTDATA_EXTRACT
  add constraint PK_STUDENTDATA_EXTRACT primary key (EXTRACTID) using index TABLESPACE FCAT_IDX1;
alter table STUDENTDATA_EXTRACT add constraint FK_STUDENTDATA_EXTRACT_1 foreign key (JOB_ID) references JOB_TRACKING (JOB_ID);

alter table JOB_PARTITION_STATUS add constraint PK_JOB_PARTITION_STATUS primary key (JOB_PARTITION_ID) using index TABLESPACE FCAT_IDX1;
alter table JOB_PARTITION_STATUS add constraint CHK_JOB_PARTITION_STATUS_1 check (LOAD_MODE IN ('OAS','PP','NOMODE'));
alter table JOB_PARTITION_STATUS add constraint CHK_JOB_PARTITION_STATUS_2 check (STATUS IN ('AC','IN','CO','VA'));

alter table PASSWORD_HISTORY add constraint PK_PASSWORD_HISTORY primary key (PWD_HISTORYID) using index TABLESPACE FCAT_IDX1;

ALTER TABLE ORG_PDF_FILES ADD CONSTRAINT FK_ORG_PDF_FILES_2 FOREIGN KEY (PDF_REPORTID) REFERENCES prismglobal.PDF_REPORTS (PDF_REPORTID);

---ADDED FOR MO
ALTER TABLE ORG_EXAMINER_LOOKUP ADD CONSTRAINT FK_EXAMINER_ID FOREIGN KEY (EXAMINERID) REFERENCES EXAMINER_DIM(EXAMINERID);
ALTER TABLE ORG_EXAMINER_LOOKUP ADD CONSTRAINT FK_EXAMINER_ORG_NODEID FOREIGN KEY (ORG_NODEID) REFERENCES ORG_NODE_DIM(ORG_NODEID);
ALTER TABLE ORG_EXAMINER_LOOKUP ADD CONSTRAINT FK_EXAMINER_GRADEID FOREIGN KEY (GRADEID) REFERENCES PRISMGLOBAL.GRADE_DIM(GRADEID);
ALTER TABLE ORG_EXAMINER_LOOKUP ADD CONSTRAINT FK_EXAMINER_SUBTESTID FOREIGN KEY (SUBTESTID) REFERENCES PRISMGLOBAL.SUBTEST_DIM(SUBTESTID);

---ADDED FOR MO BY PARTHA
ALTER TABLE STG_PROCESS_STATUS  ADD CONSTRAINT PK_STG_PROCESS_STATUS PRIMARY KEY (PROCESS_ID) ; 
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_1 CHECK (HIER_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_2 CHECK (BIO_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_3 CHECK (DEMO_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_4 CHECK (CONTENT_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_5 CHECK (OBJECTIVE_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_PROCESS_STATUS ADD CONSTRAINT CHK_STG_PROCESS_STATUS_6 CHECK (ITEM_VALIDATION IN ('AC','ER','CO','IP'));

ALTER TABLE STG_HIER_DETAILS ADD CONSTRAINT PK_STG_HIER_DETAILS PRIMARY KEY (STG_HIERARCHY_DETAILS_ID);
ALTER TABLE STG_HIER_DETAILS ADD CONSTRAINT FK_STG_HIER_DETAILS_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);  

ALTER TABLE STG_OBJECTIVE_DETAILS_EXTRACT ADD CONSTRAINT FK_STG_STD_OBJECTIVE_DETAILS_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);

ALTER TABLE STG_STD_BIO_DETAILS ADD CONSTRAINT PK_STG_STD_BIO_DETAILS PRIMARY KEY (STUDENT_BIO_DETAILS_ID);
ALTER TABLE STG_STD_BIO_DETAILS ADD CONSTRAINT FK_STG_STD_BIO_DETAILS_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);

ALTER TABLE STG_STD_DEMO_DETAILS ADD CONSTRAINT FK_STG_STD_DEMO_DETAILS_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);
ALTER TABLE STG_STD_OBJECTIVE_DETAILS ADD CONSTRAINT FK_STG_STD_OBJECTIVE_DETAILS FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);  
ALTER TABLE STG_STD_SUBTEST_DETAILS ADD CONSTRAINT FK_STG_STD_SUBTEST_DETAILS_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);


---ADDED FOR MO BY SOURAV NAYEK
ALTER TABLE STG_HIER_PROCESS_STATUS ADD CONSTRAINT PK_STG_HIER_PROCESS_STATUS PRIMARY KEY (PROCESS_ID);
ALTER TABLE STG_HIER_PROCESS_STATUS ADD CONSTRAINT CHK_STG_HIER_PROCESS_STATUS  CHECK (HIER_VALIDATION IN ('AC','ER','CO','VA'));

ALTER TABLE STG_MO_HIER_EXTRACT ADD CONSTRAINT PK_HIER_EXTRACT_ID PRIMARY KEY (MO_HIER_EXTRACT_ID); 
ALTER TABLE STG_ORG_NODE_DIM ADD CONSTRAINT PK_STG_ORG_NODE_DIM_ID PRIMARY KEY (STG_ORG_NODE_DIM_ID); 
  
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT PK_STG_TASK_STATUS PRIMARY KEY (TASK_ID);
  
  
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT FK_PROCESS_ID FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID);
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_1 CHECK (HIER_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_2 CHECK (BIO_VALIDATION IN ('AC','ER','CO','IP')); 
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_3 CHECK (DEMO_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_4 CHECK (CONTENT_VALIDATION IN ('AC','ER','CO','IP'));
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_5 CHECK (OBJECTIVE_VALIDATION IN ('AC','ER','CO','IP')); 
ALTER TABLE STG_TASK_STATUS ADD CONSTRAINT CHK_STG_TASK_STATUS_6 CHECK (ITEM_VALIDATION IN ('AC','ER','CO','IP'));  

ALTER TABLE STUDENT_DATA_EXTRACT ADD CONSTRAINT FK_PROCESS_ID_1 FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS(PROCESS_ID);
ALTER TABLE STUDENT_DATA_EXTRACT ADD CONSTRAINT FK_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES STG_TASK_STATUS(TASK_ID);
ALTER TABLE STUDENT_DATA_EXTRACT ADD CONSTRAINT CHK_VALIDATION_FLAG CHECK (VALIDATION_FLAG IN ('Y','N'));
ALTER TABLE STUDENT_DATA_EXTRACT ADD CONSTRAINT CHK_IS_FILE_VALID CHECK (IS_FILE_VALID IN ('IN','VA')); 

ALTER TABLE STG_ITEM_RESPONSE_DETAILS ADD CONSTRAINT FK_STG_ITEM_RESPONSE_DETAILS FOREIGN KEY (PROCESS_ID) REFERENCES STG_PROCESS_STATUS (PROCESS_ID); 




  
  

  
  

  
  

  
  

  
  

 
 

  
  

  
 

  
  

  
  





  
  
  

  
   
  







