DROP INDEX IDX_ESRI_1;
CREATE INDEX IDX_ESRI_1 ON ERR_STUDENT_REG_INFO (STG_REG_INFO_ID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

DROP INDEX  IDX_ESRIH_1;
CREATE INDEX IDX_ESRIH_1 ON ERR_STUDENT_REG_INFO_HIST (STG_REG_INFO_ID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

DROP INDEX IDX_ESDIH_1;
CREATE INDEX IDX_ESDIH_1 ON ERR_STUDENT_DOC_INFO_HIST (STG_STUDENT_DOCID,STG_STUDENT_BIO_ID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );  
  
DROP INDEX  IDX_ESBDH_1;
CREATE INDEX IDX_ESBDH_1 ON ERR_STUDENT_BIO_DIM_HIST (STG_STUDENT_BIO_ID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );  
  
DROP INDEX IDX_ERR_STUDENT_DOC_INFO;
CREATE INDEX IDX_ERR_STUDENT_DOC_INFO ON ERR_STUDENT_DOC_INFO (STG_STUDENT_DOCID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

DROP INDEX  IDX_ERR_SD_HIST;
CREATE INDEX IDX_ERR_SD_HIST ON ERR_STUDENT_DEMO_HIST (STG_STUDENT_BIO_ID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

DROP INDEX IDX_ERR_SSF_HIST;
CREATE INDEX IDX_ERR_SSF_HIST ON ERR_SUBTEST_SCORE_FACT_HIST (STG_STUDENT_DOCID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
   
