-- Create/Recreate indexes 
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_1 on OBJECTIVE_SCORE_FACT (CUST_PROD_ID);
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_2 on OBJECTIVE_SCORE_FACT (STUDENT_BIO_ID);
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_3 on OBJECTIVE_SCORE_FACT (SUBTESTID);
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_4 on OBJECTIVE_SCORE_FACT (OBJECTIVEID);
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_5 on OBJECTIVE_SCORE_FACT (GRADEID);
create bitmap index BIDX_OBJECTIVE_SCORE_FACT_6 on OBJECTIVE_SCORE_FACT (ADMINID);