DROP INDEX ISTEPPERF.IDX_ORG_PRODUCT_LINK_TM2;
CREATE INDEX ISTEPPERF.IDX_ORG_PRODUCT_LINK_TM2 ON ISTEPPERF.ORG_PRODUCT_LINK
(CUST_PROD_ID, ORG_NODEID )
LOGGING
TABLESPACE FCAT_IDX1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
