 CREATE INDEX IDX_PASSWORD_HISTORY ON PASSWORD_HISTORY (USERID)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );