DROP INDEX ISTEPPERF.IDX_SUBTEST_SCORE_FACT_3_TM;
CREATE INDEX ISTEPPERF.IDX_SUBTEST_SCORE_FACT_3_TM ON ISTEPPERF.SUBTEST_SCORE_FACT
(ORG_NODEID, CUST_PROD_ID, SUBTESTID, ADMINID, GRADEID, SS, HSE, STATUS_CODE, STUDENT_BIO_ID, GENDERID, FORMID, ASSESSMENTID)
LOGGING
TABLESPACE FCAT_IDX1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARALLEL 8;
ALTER INDEX ISTEPPERF.IDX_SUBTEST_SCORE_FACT_3_TM PARALLEL 1;
