CREATE TABLE USERS_BKP_08082014 AS SELECT * FROM USERS;
CREATE TABLE ORG_USERS_BKP_08082014 AS SELECT * FROM ORG_USERS;
CREATE TABLE USER_ROLE_BKP_08082014 AS SELECT * FROM USER_ROLE;
--SELECT COUNT(1) FROM USERS_BKP_08082014;--639168
--SELECT COUNT(1) FROM ORG_USERS_BKP_08082014;--623394
--SELECT COUNT(1) FROM USER_ROLE_BKP_08082014;--1003301
------------------------------------------------------------------
INSERT INTO ROLE VALUES (8,'ROLE_GRW','Growth Report User',SYSDATE,SYSDATE);
------------------------------------------------------------------
CREATE TABLE MIG_GRW_USERS_MAP AS 
SELECT MIG_USERID,
       USER_ID_SEQ.NEXTVAL AS GENERATED_USERID,
       USERNAME,
       DISPLAY_USERNAME,
       LAST_NAME,
       FIRST_NAME,
       MIDDLE_NAME,
       EMAIL_ADDRESS,
       PHONE_NO,
       STREET,
       COUNTRY,
       CITY,
       ZIPCODE,
       STATE,
       CUSTOMERID,
       IS_FIRSTTIME_LOGIN,
       LAST_LOGIN_ATTEMPT,
       PASSWORD_EXPR_DATE,
       IS_NEW_USER,
       PASSWORD,
       SALT,
       LAST_LOGIN_DATE,
       SIGNED_USER_AGREEMENT,
       AUTO_GENERATED_USER,
       USER_TYPE,
       ACTIVATION_STATUS,
       SYSDATE AS CREATED_DATE_TIME,
       SYSDATE AS UPDATED_DATE_TIME
FROM ISTEP_PRODNEW.MIG_GRW_USERS_MAP; 
------------------------------------------------------------------
CREATE TABLE MIG_GRW_ORG_USERS_MAP AS 
SELECT  MIGRATED_ORG_USER_ID,
        ORG_USER_ID_SEQ.NEXTVAL AS GENARATED_ORG_USER_ID,
        USERID,
        ORG_NODEID,
        ORG_NODE_LEVEL,
        ADMINID,
        ACTIVATION_STATUS,
        SYSDATE AS CREATED_DATE_TIME,
        SYSDATE AS UPDATED_DATE_TIME
FROM ISTEP_PRODNEW.MIG_GRW_ORG_USERS_MAP;
--SELECT COUNT(1) FROM MIG_GRW_USERS_MAP;----12838
------------------------------------------------------------------
INSERT INTO USERS  
SELECT GENERATED_USERID AS USERID, 
       USERNAME,
       DISPLAY_USERNAME,
       LAST_NAME,
       FIRST_NAME,
       MIDDLE_NAME,
       EMAIL_ADDRESS,
       PHONE_NO,
       STREET,
       COUNTRY,
       CITY,
       ZIPCODE,
       STATE,
       CUSTOMERID,
       IS_FIRSTTIME_LOGIN,
       LAST_LOGIN_ATTEMPT,
       PASSWORD_EXPR_DATE,
       IS_NEW_USER,
       PASSWORD,
       SALT,
       LAST_LOGIN_DATE,
       SIGNED_USER_AGREEMENT,
       AUTO_GENERATED_USER,
       USER_TYPE,
       ACTIVATION_STATUS,
       CREATED_DATE_TIME,
       UPDATED_DATE_TIME
FROM  MIG_GRW_USERS_MAP;
--SELECT COUNT(1) FROM USERS;----639168+12838=652006
-------------------------------------------------------------
INSERT INTO ORG_USERS  
SELECT  ORG.GENARATED_ORG_USER_ID AS ORG_USER_ID,
        (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE ORG.USERID = USR.MIG_USERID) AS USERID,
        ORG.ORG_NODEID,
        ORG.ORG_NODE_LEVEL,
        ORG.ADMINID,
        ORG.ACTIVATION_STATUS,
        ORG.CREATED_DATE_TIME,
        ORG.UPDATED_DATE_TIME
FROM MIG_GRW_ORG_USERS_MAP ORG;
--SELECT COUNT(1) FROM ORG_USERS; ----623394+12838=636232
-------------------------------------------------------------
INSERT INTO USER_ROLE 
SELECT MAIN.USERID AS USER_ID, 
       MAIN.ROLEID AS ROLE_ID,
       SYSDATE,SYSDATE
  FROM (SELECT DISTINCT U.USERID, R.ROLEID
          FROM USERS U, ROLE R
         WHERE R.ROLE_NAME IN ('ROLE_USER', 'ROLE_GRW')
         AND U.CUSTOMERID = 1000
         AND USER_TYPE in ('GRW','GRW_P')) MAIN,
       USER_ROLE UR
 WHERE MAIN.USERID = UR.USERID(+)
   AND MAIN.ROLEID = UR.ROLEID(+)
   AND UR.USERID IS NULL; 
--SELECT COUNT(1) FROM USER_ROLE; ---- 1003301 +(12838*2)= 1028977
-------------------------------------------------------------
INSERT INTO USER_SELECTION_LOOKUP 
SELECT (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE USR.MIG_USERID =USL.USERID ) AS USERID,
       USL.CUST_PROD_ID,
       USL.GRADEID,
       USL.SUBTESTID,
       SYSDATE AS DATETIMESTAMP
FROM ISTEP_PRODNEW.GRW_USER_SELECTION_LOOKUP_2013 USL;  
--SELECT COUNT(1) FROM ISTEP_PRODNEW.USER_SELECTION_LOOKUP;---23919
--SELECT COUNT(1) FROM USER_SELECTION_LOOKUP;---23919

--SELECT COUNT(1) FROM ISTEP_DEV_ETL.GRW_USER_SELECTION_LOOKUP_2013@PROD_TO_ISTEPMASTER;---23919
-------------------------------------------------------------
INSERT INTO USC_LINK 
SELECT (SELECT MP.GENARATED_ORG_USER_ID 
               FROM MIG_GRW_ORG_USERS_MAP MP 
               WHERE MP.MIGRATED_ORG_USER_ID = LNK.ORG_USER_ID) AS ORG_USER_ID,
       LNK.CUST_PROD_ID,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = LNK.TEST_ELEMENT_ID) AS STUDENT_BIO_ID ,
       LNK.SUBTESTID,
       SYSDATE AS DATETIMESTAMP
 FROM ISTEP_PRODNEW.GRW_USC_LINK_2013 LNK
 WHERE  LNK.CUST_PROD_ID = 5001;
 --- SELECT COUNT(1)  FROM ISTEP_DEV_ETL.GRW_USC_LINK_2013@PROD_TO_ISTEPMASTER ; ---785905 
 --- SELECT COUNT(1) FROM ISTEP_PRODNEW.USC_LINK;---785905
 --- SELECT COUNT(1)  FROM USC_LINK; ---785905 
 --SELECT * FROM ISTEP_PRODNEW.GRW_USC_LINK_2013
 -------------------------------------------------------------
CREATE TABLE PERF_MATRIX_FACT_1 AS SELECT * FROM PERF_MATRIX_FACT WHERE 1=2;
INSERT INTO PERF_MATRIX_FACT_1
SELECT PERF_MATRIX_ID,
       ORG_NODEID,
       CUST_PROD_ID,
       STUDENT_NAME,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = CURR_TEST_ELEMENT_ID) AS CURR_STUDENT_BIO_ID,
       --CURR_TEST_ELEMENT_ID,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = PREV_TEST_ELEMENT_ID) AS PREV_STUDENT_BIO_ID,
       --PREV_TEST_ELEMENT_ID,
       SUBTESTID,
       CURR_GRADEID,
       PREV_GRADEID,
       CURR_ADMINID,
       PREV_ADMINID,
       CURR_SC,
       PREV_SC,
       (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE USR.MIG_USERID = USER_ID) AS USER_ID,
       PERF_LEVEL,
       SYSDATE AS DATETIMESTAMP
FROM ISTEP_PRODNEW.GRW_PERF_MATRIX_FACT_2013;
--SELECT COUNT(1) FROM PERF_MATRIX_FACT_1;--729243
 -------------------------------------------------------------
---RUN THE PORCEDURE FOR ALL THE COMBINATIONS
 ---THEN REFRESH THE MVIEWS (SCRIPT BELOW)
BEGIN

 DBMS_MVIEW.REFRESH('MV_PRINCIPAL_USER_SEL_LOOKUP', 'C');
 DBMS_MVIEW.REFRESH('MV_LVL2_PRCPL_USER_SEL_LOOKUP', 'C');

END;       


