

---------------------------------DDL STATEMENT---------------------------

--PRISMGLOBAL
ALTER TABLE ADMIN_DIM ADD ADMIN_CODE VARCHAR2(16);
UPDATE ADMIN_DIM SET ADMIN_CODE = '594600' WHERE ADMIN_NAME = 'TASC';

--TASC
CREATE OR REPLACE VIEW ADMIN_DIM AS
SELECT ADMINID,
       ADMIN_NAME,
       ADMIN_SEASON,
       ADMIN_YEAR,
       ADMIN_CODE,
       IS_CURRENT_ADMIN,
       FILE_LOCATION,
       ADMIN_SEQ,
       DATETIMESTAMP
  FROM prismglobal.ADMIN_DIM
  WHERE PROJECTID = 1;


-- Create PROCESS_STATUS table
CREATE TABLE TASC_PROCESS_STATUS
(
  PROCESS_ID           NUMBER PRIMARY KEY,
  FILE_NAME            VARCHAR2(256),
  SOURCE_SYSTEM        VARCHAR2(100),
  REG_VALIDATION       VARCHAR2(2),
  DOC_VALIDATION       VARCHAR2(2),
  HIER_VALIDATION      VARCHAR2(2),
  BIO_VALIDATION       VARCHAR2(2),
  DEMO_VALIDATION      VARCHAR2(2),
  CONTENT_VALIDATION   VARCHAR2(2),
  OBJECTIVE_VALIDATION VARCHAR2(2),
  ITEM_VALIDATION      VARCHAR2(2),
  WKF_PARTITION_NAME   VARCHAR2(100),
  PROCESS_LOG          VARCHAR2(4000),
  DATETIMESTAMP        DATE
);
-- Create/Recreate check constraints
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_1
  check (REG_VALIDATION IN ('AC','IN','CO','VA'));
  alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_2
  check (DOC_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_3
  check (HIER_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_4
  check (BIO_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_5
  check (DEMO_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_6
  check (CONTENT_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_7
  check (OBJECTIVE_VALIDATION IN ('AC','IN','CO','VA'));
alter table TASC_PROCESS_STATUS
  add constraint CHK_DRC_STG_PROCESS_STATUS_8
  check (ITEM_VALIDATION IN ('AC','IN','CO','VA'));
  
--STG_TASK_STATUS

CREATE TABLE STG_TASK_STATUS
(
  TASK_ID              NUMBER not null,
  PROCESS_ID           NUMBER not null,
  FILE_NAME            VARCHAR2(256),
  SOURCE_SYSTEM        VARCHAR2(100),
  IS_FILE_VALID        VARCHAR2(1),
  WKF_PARTITION_NAME   VARCHAR2(100),
  STUDENT_CASE_COUNT   NUMBER,
  DOCUMENT_CASE_COUNT  NUMBER,
  STU_RJCT_CASE_COUNT  NUMBER,
  DOC_RJCT_CASE_COUNT  NUMBER,
  TASK_LOG             VARCHAR2(4000),
  DATETIMESTAMP        DATE DEFAULT SYSDATE
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table STG_TASK_STATUS
  add constraint PK_STG_TASK_STATUS primary key (TASK_ID);
alter table STG_TASK_STATUS
  add constraint FK_PROCESS_ID foreign key (PROCESS_ID)
  references TASC_PROCESS_STATUS (PROCESS_ID);
-- Create/Recreate indexes 
create index IDX_STG_TASK_STATUS_1 on STG_TASK_STATUS (PROCESS_ID, TASK_ID);


--STG_STUDENT_REG_INFO: Contain Student level information including demographic.
CREATE TABLE STG_STUDENT_REG_INFO
(
  STG_REG_INFO_ID            NUMBER NOT NULL,
  DRC_STUDENTID              NUMBER NOT NULL,
  LAST_NAME                  VARCHAR2(25),
  FIRST_NAME                 VARCHAR2(25),
  MIDDLE_NAME                VARCHAR2(1),
  BIRTHDATE                  VARCHAR2(8),
  GENDERID                   NUMBER,
  GRADEID                    NUMBER,
  EXAMINEE_ID                VARCHAR2(9) NOT NULL,
  REGISTRATION_ON            VARCHAR2(20),
  REGISTERED_BY              VARCHAR2(100),
  ETHNICITY                  VARCHAR2(2),
  RACE_AI_AN                 VARCHAR2(2),
  RACE_AFRICAN_AMERICAN      VARCHAR2(2),
  RACE_ASIAN                 VARCHAR2(2),
  RACE_NATIVE_HAWAIIAN_OTHER VARCHAR2(2),
  RAC_WHITE                  VARCHAR2(2),
  RACE_NONE                  VARCHAR2(5),
  RESOLVED_ETHNICITY_RACE    VARCHAR2(2),
  GOVERNMENTID               VARCHAR2(50),
  GOVERNMENTID_TYPE          VARCHAR2(255),
  ADDRESS_STREET             VARCHAR2(50),
  ADDRESS_APRT_NO            VARCHAR2(30),
  ADDRESS_CITY               VARCHAR2(30),
  ADDRESS_STATE              VARCHAR2(30),
  ADDRESS_ZIP                VARCHAR2(30),
  EXAMINEE_COUNTY_CODE       VARCHAR2(10),
  REG_TC_COUNTY_CODE         VARCHAR2(10),
  REG_TC_CODE                VARCHAR2(10),
  HOME_LANGUAGE              VARCHAR2(2),
  CHRONOLOGICAL_AGE          VARCHAR2(3),
  AGE_GROUP                  VARCHAR2(2),
  EXAMINEE_MAIL_ADDRESS      VARCHAR2(200),
  EMAIL                      VARCHAR2(100),
  ALTERNATE_EMAIL            VARCHAR2(100),
  PHONE_NO                   VARCHAR2(30),
  CELL_PHONE_NO              VARCHAR2(30),
  ALTERNATE_NO               VARCHAR2(200),
  CONTACT                    VARCHAR2(2),
  REGISTERED_AT_TEST_CENTER  VARCHAR2(100),
  HIGHEST_LEVEL_EDU          VARCHAR2(2),
  READINESS_ASSESSMENT VARCHAR2(100),
  TASCREADINESS VARCHAR2(100),
  STUDENTCOUNTYNAME VARCHAR2(100),
  SPECIALCODE_A_J VARCHAR2(100),
  SPECIALCODE_K VARCHAR2(100),
  SPECIALCODE_L VARCHAR2(100),
  SPECIALCODE_M VARCHAR2(100),
  SPECIALCODE_N_S VARCHAR2(100),
  SPECIALCODE_T VARCHAR2(100),
  SPECIALCODE_U VARCHAR2(100),
  SPECIALCODE_V VARCHAR2(100),
  SPECIALCODE_W VARCHAR2(100),
  SPECIALCODE_X VARCHAR2(100),
  SPECIALCODE_Y VARCHAR2(100),
  SPECIALCODE_Z VARCHAR2(100),
  ATTENDCOLLEGE VARCHAR2(100),
  GRADE VARCHAR2(100),
  ALTERNATEID VARCHAR2(100),
  CORRECTIONSID VARCHAR2(100),
  CREDENTIALINGJID VARCHAR2(100),
  TESTCANDIDATEFLAG VARCHAR2(100),
  GENERATION VARCHAR2(100),
  INHIGHSCHOOL VARCHAR2(100),
  OPTIONS VARCHAR2(100),
  RELEASESCORESINDICATOR VARCHAR2(100),
  STUDENT_UPDATE_DATETIME    VARCHAR2(20),
  CUSTOMERID                 NUMBER,
  ADMINID                    NUMBER,
  ORG_NODEID                 NUMBER,
  ORG_NODE_CODE_PATH         VARCHAR2(100),
  STUDENT_CREATED_DATE       VARCHAR2(20),--New field added to identify latest student
  DATETIMESTAMP              DATE,
  PROCESS_ID                 NUMBER,
  TASK_ID                    NUMBER,
  VALIDATION_STATUS          VARCHAR2(2),
  IS_FILE_VALID              VARCHAR2(2),
  VALIDATION_LOG             VARCHAR2(400),
  IS_LATEST                  VARCHAR2(1),
  FILENAME                   VARCHAR2(100)
);

--ALTER TABLE STG_STUDENT_REG_INFO MODIFY STUDENT_UPDATE_DATE VARCHAR2(20);
--ALTER TABLE STG_STUDENT_REG_INFO RENAME COLUMN STUDENT_UPDATE_DATE TO STUDENT_UPDATE_DATETIME;
--ALTER TABLE STG_STUDENT_REG_INFO MODIFY BIRTHDATE VARCHAR2(8);

--ALTER TABLE STG_STUDENT_REG_INFO ADD CONSTRAINT PK_STG_REGID PRIMARY KEY (STG_REG_INFO_ID);

CREATE TABLE STG_STUDENT_SURVEY
(
STG_REG_INFO_ID NUMBER,
DRC_STUDENTID NUMBER,
SURVAY_NAME   VARCHAR2(100),
SURVEY_VALUE  VARCHAR2(100),
DATETIMESTAMP DATE
);

/*
ALTER TABLE STG_STUDENT_SURVEY ADD CONSTRAINT FK_STG_REGID
FOREIGN KEY (STG_REG_INFO_ID) REFERENCES STG_STUDENT_REG_INFO(STG_REG_INFO_ID);
*/

/*
create sequence SEQ_DRC_TASC_PROCESS_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1001
increment by 1
cache 20;
*/

create sequence SEQ_STG_REG_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1001
increment by 1
cache 20;

create sequence SEQ_TASK_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1001
increment by 1
cache 20;

--DROP TABLE STUDENT_REG_INFO;

CREATE TABLE STUDENT_REG_INFO
(
  STUDENT_REGID              NUMBER NOT NULL PRIMARY KEY,
  DRC_STUDENTID              NUMBER NOT NULL,
  LAST_NAME                  VARCHAR2(32),
  FIRST_NAME                 VARCHAR2(32),
  MIDDLE_NAME                VARCHAR2(32),
  BIRTHDATE                  VARCHAR2(8),
  GENDERID                   NUMBER,
  GRADEID                    NUMBER,
  EXAMINEE_ID                VARCHAR2(9) NOT NULL,
  REGISTRATION_ON            DATE,
  REGISTERED_BY              VARCHAR2(100),
  ETHNICITY                  VARCHAR2(2),
  RACE_AI_AN                 VARCHAR2(2),
  RACE_AFRICAN_AMERICAN      VARCHAR2(2),
  RACE_ASIAN                 VARCHAR2(2),
  RACE_NATIVE_HAWAIIAN_OTHER VARCHAR2(2),
  RAC_WHITE                  VARCHAR2(2),
  RACE_NONE                  VARCHAR2(5),
  RESOLVED_ETHNICITY_RACE    VARCHAR2(2),
  GOVERNMENTID               VARCHAR2(50),
  GOVERNMENTID_TYPE          VARCHAR2(255),
  ADDRESS_STREET             VARCHAR2(50),
  ADDRESS_APRT_NO            VARCHAR2(30),
  ADDRESS_CITY               VARCHAR2(30),
  ADDRESS_STATE              VARCHAR2(30),
  ADDRESS_ZIP                VARCHAR2(30),
  EXAMINEE_COUNTY_CODE       VARCHAR2(10),
  REG_TC_COUNTY_CODE         VARCHAR2(10),
  REG_TC_CODE                VARCHAR2(10),
  HOME_LANGUAGE              VARCHAR2(2),
  CHRONOLOGICAL_AGE          VARCHAR2(3),
  AGE_GROUP                  VARCHAR2(2),
  EXAMINEE_MAIL_ADDRESS      VARCHAR2(200),
  EMAIL                      VARCHAR2(100),
  ALTERNATE_EMAIL            VARCHAR2(100),
  PHONE_NO                   VARCHAR2(30),
  CELL_PHONE_NO              VARCHAR2(30),
  ALTERNATE_NO               VARCHAR2(200),
  CONTACT                    VARCHAR2(2),
  REGISTERED_AT_TEST_CENTER  VARCHAR2(100),
  HIGHEST_LEVEL_EDU          VARCHAR2(2),
  READINESS_ASSESSMENT VARCHAR2(1),
  TASCREADINESS VARCHAR2(100),
  STUDENTCOUNTYNAME VARCHAR2(100),
  SPECIALCODE_A_J VARCHAR2(10),
  SPECIALCODE_K VARCHAR2(1),
  SPECIALCODE_L VARCHAR2(1),
  SPECIALCODE_M VARCHAR2(1),
  SPECIALCODE_N_S VARCHAR2(6),
  SPECIALCODE_T VARCHAR2(1),
  SPECIALCODE_U VARCHAR2(1),
  SPECIALCODE_V VARCHAR2(1),
  SPECIALCODE_W VARCHAR2(1),
  SPECIALCODE_X VARCHAR2(1),
  SPECIALCODE_Y VARCHAR2(1),
  SPECIALCODE_Z VARCHAR2(1),
  ATTENDCOLLEGE VARCHAR2(1),
  GRADE VARCHAR2(2),
  ALTERNATEID VARCHAR2(40),
  CORRECTIONSID VARCHAR2(9),
  CREDENTIALINGJID VARCHAR2(2),
  TESTCANDIDATEFLAG VARCHAR2(5),
  GENERATION VARCHAR2(4),
  INHIGHSCHOOL VARCHAR2(5),
  OPTIONS VARCHAR2(5),
  RELEASESCORESINDICATOR VARCHAR2(5),
  STUDENT_UPDATE_DATETIME    DATE,
  CUSTOMERID                 NUMBER NOT NULL,
  ADMINID                    NUMBER NOT NULL,
  ORG_NODEID                 NUMBER,
  ORG_NODE_CODE_PATH         VARCHAR2(100) NOT NULL,
  UDB_PROCESSED_DATE         DATE DEFAULT SYSDATE NOT NULL,
  RECONCILE_EXPORT_STATUS    VARCHAR2(1) DEFAULT 'N',
  RECONCILE_EXPORT_DATE      DATE,
  CREATED_DATETIME           DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATETIME           DATE
);

ALTER TABLE student_reg_info ADD CONSTRAINT IDX_UNQ_DRC_STUDENTID UNIQUE (DRC_STUDENTID);
ALTER TABLE student_reg_info ADD CONSTRAINT IDX_UNQ_CUST_EXAMINEE UNIQUE (customerid,EXAMINEE_ID);

CREATE TABLE STUDENT_SURVEY
(

STUDENT_SURVEYID NUMBER PRIMARY KEY,
STUDENT_REGID NUMBER NOT NULL,
SURVAY_NAME   VARCHAR2(100),
SURVEY_VALUE  VARCHAR2(100),
CREATED_DATE_TIME DATE,
UPDATED_DATE_TIME DATE
);

ALTER TABLE STUDENT_SURVEY ADD CONSTRAINT FK_STUDENT_REGID
FOREIGN KEY (STUDENT_REGID) REFERENCES STUDENT_REG_INFO(STUDENT_REGID);


CREATE TABLE STG_STUDENT_DOC_INFO
(    
  STG_STUDENT_DOCID      NUMBER NOT NULL,--PK
  DOCUMENTID             NUMBER NOT NULL,--DRCDocumentID
  STUDENT_REGID          NUMBER,--FK
  DRC_STUDENTID          NUMBER NOT NULL,--DRCStudentID
  SCHEDULE_ID            VARCHAR2(10),--ScheduledID
  TCA_SCHEDULED_DATE     VARCHAR2(10),--TCAScheduleDate
  DATE_SCHEDULED         VARCHAR2(20),--DateScheduled
  IMAGING_ID             VARCHAR2(26),--ImagingID
  LITHOCODE              VARCHAR2(8),--LithoCode
  CONTENT_CODE           VARCHAR2(2) NOT NULL,--ContentCode
  FORM                   VARCHAR2(5) NOT NULL,--Form
  TEST_LANGUAGE          VARCHAR2(1) NOT NULL,--TestLanguage
  TEST_MODE              VARCHAR2(2) NOT NULL,--TestMode
  FIELD_TEST_FORM        VARCHAR2(3),--FieldTestForm
  CHANGED_FORM_FLAG      VARCHAR2(1),--ChangedFormFlag
  BARCODE_ID             VARCHAR2(16),--BarcodeID
  CHECKIN_DATE           VARCHAR2(20),--CheckinDatetime
  EXPIRED_DATE           VARCHAR2(20),--ExpiredDatetime
  EXPIRED_REASON         VARCHAR2(2000),--Reason
  SCHED_TC_COUNTY_CODE   VARCHAR2(8),--SchedTC_Cty_Code
  SCHED_TC_CODE          VARCHAR2(8),--SchedTC_Code
  SCHED_EDU_CENTER_CODE  VARCHAR2(8),--SchedEC_Code
  REGION_ORGCODE         VARCHAR2(15),
  STATUS_CODE            VARCHAR2(4),
  LARGEPRINT             VARCHAR2(1),
  BRAILLE                VARCHAR2(1),
  TEST_EVENT_UPDATE_DATE VARCHAR2(14),--Used to find out latest doc
  STG_STUDENT_BIO_ID     NUMBER,--FK related to BIO
  ORG_NODEID             NUMBER,
  ORG_NODE_CODE_PATH     VARCHAR2(100),
  BASE_DOCUMENT_FLAG     VARCHAR(1),
  DOC_PROCESS_STATUS     VARCHAR2(3), --Checks- SCH- Scheduled, CHI- CheckIn, EXP- Expired, TES -TestEventScores
  DOC_CREATED_DATE       VARCHAR2(20),--capture xml created date time
  CUSTOMERID             NUMBER,
  ADMINID                NUMBER,
  PROCESS_ID             NUMBER,
  TASK_ID                NUMBER,
  VALIDATION_STATUS      VARCHAR2(2),
  IS_FILE_VALID          VARCHAR2(2),
  VALIDATION_LOG         VARCHAR2(400),
  IS_LATEST              VARCHAR2(1),
  FILENAME               VARCHAR2(100),
  DATETIMESTAMP          DATE DEFAULT SYSDATE
);

--ALTER TABLE STG_STUDENT_DOC_INFO RENAME COLUMN DATETIMETIMESTAMP TO DATETIMESTAMP;
--ALTER TABLE STG_STUDENT_DOC_INFO RENAME COLUMN DOC_UPDATE_DATE TO STATUS_CODE;
--ALTER TABLE STG_STUDENT_DOC_INFO MODIFY STATUS_CODE VARCHAR2(4);
--ALTER TABLE STG_STUDENT_DOC_INFO DROP COLUMN SCORING_COMPLETE_DATE;

CREATE TABLE STG_STUDENT_BIO_DIM
(
  STG_STUDENT_BIO_ID NUMBER not null,
  FIRST_NAME         VARCHAR2(32),
  MIDDLE_NAME        VARCHAR2(32),
  LAST_NAME          VARCHAR2(32),
  BIRTHDATE          VARCHAR2(10),
  DRC_STUDENTID      NUMBER NOT NULL,
  TEST_ELEMENT_ID    VARCHAR2(30) not null,
  INT_STUDENT_ID     VARCHAR2(52),
  EXT_STUDENT_ID     VARCHAR2(20),
  LITHOCODE          VARCHAR2(26),
  GENDERID           NUMBER,
  GRADEID            NUMBER,
  EDU_CENTERID       NUMBER,
  BARCODE            VARCHAR2(26),
  SPECIAL_CODES      VARCHAR2(26),
  STUDENT_MODE       VARCHAR2(2),
  ORG_NODEID         NUMBER,
  CUSTOMERID         NUMBER,
  ADMINID            NUMBER,
  IS_BIO_UPDATE_CMPL VARCHAR2(1),
  PP_IMAGING_ID      VARCHAR2(26),
  OAS_IMAGING_ID     VARCHAR2(26),
  PROCESS_ID         NUMBER,
  TASK_ID            NUMBER,
  DATETIMSTAMP       DATE
);

CREATE TABLE STG_STUDENT_DEMO
(
STG_STUDENT_BIO_ID NUMBER,
DEMO_CODE VARCHAR2(200),
DEMO_VALUE VARCHAR2(200),
DEMOID NUMBER,
DEMO_VALID NUMBER,
SUBTEST_CODE VARCHAR2(100),
SUBTESTID NUMBER,
PROCESS_ID NUMBER,
CUSTOMERID NUMBER,
TASK_ID NUMBER,
VALIDATION_STATUS VARCHAR2(2),
IS_FILE_VALID VARCHAR2(2),
VALIDATION_LOG VARCHAR2(4000),
DATETIMESTAMP DATE DEFAULT SYSDATE
);

create table TEMP_NEWDEMO_GHI
(
  DEMOID            NUMBER not null,
  DEMO_NAME         VARCHAR2(50) not null,
  DEMO_CODE         VARCHAR2(20) not null,
  DEMO_MODE         VARCHAR2(20) not null,
  CUSTOMERID        NUMBER not null,
  SUBTESTID         NUMBER,
  CATEGORY          VARCHAR2(20),
  IS_DEMO_VALUE_AVL VARCHAR2(1) not null,
  DATETIMESTAMP     DATE not null
);

-- Create table
create table TEMP_NEWDEMO_VAL_GHI
(
  DEMO_VALID      NUMBER not null,
  DEMOID          NUMBER not null,
  DEMO_VALUE_NAME VARCHAR2(50) not null,
  DEMO_VALUE_CODE VARCHAR2(20) not null,
  DEMO_VALUE_SEQ  NUMBER not null,
  IS_DEFAULT      VARCHAR2(1) not null,
  DATETIMESTAMP   DATE not null
);

--Export data from above two table and create insert script using below script
TASC GHI FORM New Demo Population.sql



CREATE TABLE STG_SUBTEST_SCORE_FACT
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  STG_STUDENT_DOCID  NUMBER,
  DRC_STUDENTID      NUMBER NOT NULL,
  CONTENT_CODE       VARCHAR2(2) NOT NULL,
  TEST_FORM          VARCHAR2(1) NOT NULL,
  STATUS_CODE        VARCHAR2(3),
  DATE_TEST_TAKEN    DATE,
  AAGE               VARCHAR2(5),
  AANCE              NUMBER,
  AANP               NUMBER,
  AANS               NUMBER,
  AASS               NUMBER,
  ACSIP              NUMBER,
  ACSIS              NUMBER,
  ACSIN              NUMBER,
  CSI                NUMBER,
  CSIL               NUMBER,
  CSIU               NUMBER,
  DIFF               VARCHAR2(5),
  GE                 VARCHAR2(5),
  HSE                VARCHAR2(1),
  LEX                NUMBER,
  LEXL               NUMBER,
  LEXU               NUMBER,
  NCE                NUMBER,
  NCR                NUMBER,
  NP                 NUMBER,
  NPA                NUMBER,
  NPG                NUMBER,
  NPL                NUMBER,
  NPH                NUMBER,
  NS                 NUMBER,
  NSA                NUMBER,
  NSG                NUMBER,
  OM                 VARCHAR2(5),
  OMS                NUMBER,
  OP                 NUMBER,
  OPM                NUMBER,
  PC                 NUMBER,
  PL                 VARCHAR2(100),
  PP                 NUMBER,
  PR                 NUMBER,
  SEM                NUMBER,
  SNPC               NUMBER,
  SS                 NUMBER,
  QTL                NUMBER,
  QTLL               NUMBER,
  QTLU               NUMBER,
  PROCESS_ID         NUMBER,
  TASK_ID            NUMBER,
  DATETIMESTAMP      DATE DEFAULT SYSDATE
);

CREATE TABLE STG_OBJECTIVE_SCORE_FACT
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  DRC_STUDENTID    NUMBER NOT NULL,
  CONTENT_CODE     VARCHAR2(2) NOT NULL,
  OBJECTIVE_CODE   VARCHAR2(10) NOT NULL,
  TEST_FORM        VARCHAR2(1) NOT NULL,
  CONDCODE_CODE    VARCHAR2(100),
  TEST_DATE        DATE,
  NCR              NUMBER,
  OS               VARCHAR2(5),
  OPI              VARCHAR2(5),
  OPI_CUT          VARCHAR2(5),
  MEAN_IPI         VARCHAR2(5),
  OPIQ             NUMBER,
  OPIP             NUMBER,
  PC               NUMBER,
  PP               NUMBER,
  SS               NUMBER,
  PL               VARCHAR2(1),
  INRC             VARCHAR2(1),
  PROCESS_ID       NUMBER,
  TASK_ID          NUMBER,
  DATETIMESTAMP    DATE
);


CREATE TABLE STG_ITEM_SCORE_FACT
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  DRC_STUDENTID      NUMBER NOT NULL,
  CONTENT_CODE   VARCHAR2(2) NOT NULL,
  OBJECTIVE_CODE VARCHAR2(10),
  FORM           VARCHAR2(10),
  GRADE          VARCHAR2(10),
  ITEM_TYPE      VARCHAR2(100),
  ITEM_CODE      VARCHAR2(100) NOT NULL,
  ITEM_NAME      VARCHAR2(100),
  READ_CODE      VARCHAR2(100),
  SCORE_VALUES   VARCHAR2(400),
  PROCESS_ID     NUMBER,
  TASK_ID        NUMBER,
  DATETIMESTAMP  DATE DEFAULT SYSDATE
);

--DROP TABLE STUDENT_DOC_INFO;

CREATE TABLE STUDENT_DOC_INFO
(    
  STUDENT_DOCID          NUMBER NOT NULL,
  DOCUMENTID             NUMBER NOT NULL,
  STUDENT_REGID          NUMBER NOT NULL,
  SCHEDULE_ID            VARCHAR2(10),
  TCA_SCHEDULED_DATE     DATE NOT NULL,
  DATE_SCHEDULED         DATE,
  IMAGING_ID             VARCHAR2(26),
  LITHOCODE              VARCHAR2(8),
  CONTENT_CODE           VARCHAR2(2) NOT NULL,
  FORM                   VARCHAR2(5) NOT NULL,
  TEST_LANGUAGE          VARCHAR2(1) NOT NULL,
  TEST_MODE              VARCHAR2(2) NOT NULL,
  FIELD_TEST_FORM        VARCHAR2(3),
  CHANGED_FORM_FLAG      VARCHAR2(1),
  BARCODE_ID             VARCHAR2(16),
  CHECKIN_DATE           DATE,
  EXPIRED_DATE           DATE,
  EXPIRED_REASON         VARCHAR2(2000),
  EXAMINEE_COUNTY_CODE   VARCHAR2(8),
  SCHED_TC_COUNTY_CODE   VARCHAR2(8),
  SCHED_TC_CODE          VARCHAR2(8),
  REGION_ORGCODE         VARCHAR2(15),
  STATUS_CODE            VARCHAR2(4),
  TEST_EVENT_UPDATE_DATE DATE,
  STUDENT_BIO_ID         NUMBER,
  BASE_DOCUMENT_FLAG     VARCHAR(1),
  DOC_PROCESS_STATUS     VARCHAR2(3),
  CUSTOMERID             NUMBER,
  ADMINID                NUMBER,
  ORG_NODEID             NUMBER,
  UDB_PROCESSED_DATE     DATE DEFAULT SYSDATE NOT NULL,
  RECONCILE_EXPORT_STATUS VARCHAR2(1) DEFAULT 'N',
  RECONCILE_EXPORT_DATE  DATE,
  CREATED_DATE_TIME      DATE DEFAULT SYSDATE,
  UPDATED_DATE_TIME      DATE
);

ALTER TABLE STUDENT_DOC_INFO ADD CONSTRAINT PK_STUDENT_DOCID
PRIMARY KEY (STUDENT_DOCID);

ALTER TABLE STUDENT_DOC_INFO ADD CONSTRAINT FK_DOC_STUDENT_REGID
FOREIGN KEY (STUDENT_REGID) REFERENCES STUDENT_REG_INFO(STUDENT_REGID);

--ALTER TABLE STUDENT_DOC_INFO RENAME COLUMN DOC_UPDATE_DATE TO STATUS_CODE;
--ALTER TABLE STUDENT_DOC_INFO MODIFY STATUS_CODE VARCHAR2(4);
--ALTER TABLE STUDENT_DOC_INFO DROP COLUMN SCORING_COMPLETE_DATE;


--ALTER TABLE STUDENT_BIO_DIM ADD ACTIVATION_STATUS VARCHAR2(2);
--UPDATE STUDENT_BIO_DIM SET ACTIVATION_STATUS = 'AC' WHERE ACTIVATION_STATUS IS NULL;--NEW
COMMIT;
--ALTER TABLE STUDENT_BIO_DIM MODIFY IS_BIO_UPDATE_CMPL NULL;
ALTER TABLE SUBTEST_SCORE_FACT ADD STUDENT_DOCID NUMBER;
ALTER TABLE SUBTEST_SCORE_FACT_HIST ADD STUDENT_DOCID NUMBER;
--ALTER TABLE STUDENT_BIO_DIM_HIST ADD PP_IMAGING_ID VARCHAR2(26);--NEW

ALTER TABLE SUBTEST_SCORE_FACT_HIST ADD TASK_ID NUMBER;
ALTER TABLE OBJECTIVE_SCORE_FACT_HIST ADD TASK_ID NUMBER;
ALTER TABLE ITEM_SCORE_FACT_HIST ADD TASK_ID NUMBER;

---New
ALTER TABLE STG_SUBTEST_SCORE_FACT MODIFY TEST_FORM VARCHAR2(5);
ALTER TABLE STG_OBJECTIVE_SCORE_FACT MODIFY TEST_FORM VARCHAR2(5);
ALTER TABLE STG_ITEM_SCORE_FACT MODIFY FORM VARCHAR2(5);

--UPDATE DEMOGRAPHIC SET IS_DEMO_VALUE_AVL = 'N' WHERE DEMO_CODE LIKE 'Cont_Tst_Cd%';


-----------------------------ERROR TABLE IMPLEMENTATION-------------------------

CREATE TABLE ERR_STUDENT_REG_INFO
(
  STG_REG_INFO_ID            NUMBER NOT NULL,
  DRC_STUDENTID              NUMBER NOT NULL,
  CUSTOMERID                 NUMBER,
  PROCESS_ID                 NUMBER,
  VALIDATION_STATUS          VARCHAR2(2),
  VALIDATION_LOG             VARCHAR2(400),
  DATETIMESTAMP              DATE DEFAULT SYSDATE
);


CREATE TABLE ERR_STUDENT_DOC_INFO
(    
  STG_STUDENT_DOCID      NUMBER NOT NULL,
  DOCUMENTID             NUMBER NOT NULL,
  STUDENT_REGID          NUMBER,
  DRC_STUDENTID          NUMBER NOT NULL,
  CONTENT_CODE           VARCHAR2(2) NOT NULL,
  STG_STUDENT_BIO_ID     NUMBER,
  CUSTOMERID             NUMBER,
  ORG_NODEID             NUMBER,
  PROCESS_ID             NUMBER,
  VALIDATION_STATUS      VARCHAR2(2),
  VALIDATION_LOG         VARCHAR2(400),
  DATETIMESTAMP          DATE DEFAULT SYSDATE
);


CREATE TABLE ERR_STUDENT_REG_INFO_HIST
(
  STG_REG_INFO_ID            NUMBER NOT NULL,
  DRC_STUDENTID              NUMBER NOT NULL,
  LAST_NAME                  VARCHAR2(25),
  FIRST_NAME                 VARCHAR2(25),
  MIDDLE_NAME                VARCHAR2(1),
  BIRTHDATE                  VARCHAR2(8),
  GENDERID                   NUMBER,
  GRADEID                    NUMBER,
  EXAMINEE_ID                VARCHAR2(9) NOT NULL,
  REGISTRATION_ON            VARCHAR2(20),
  REGISTERED_BY              VARCHAR2(100),
  ETHNICITY                  VARCHAR2(2),
  RACE_AI_AN                 VARCHAR2(2),
  RACE_AFRICAN_AMERICAN      VARCHAR2(2),
  RACE_ASIAN                 VARCHAR2(2),
  RACE_NATIVE_HAWAIIAN_OTHER VARCHAR2(2),
  RAC_WHITE                  VARCHAR2(2),
  RACE_NONE                  VARCHAR2(5),
  RESOLVED_ETHNICITY_RACE    VARCHAR2(2),
  GOVERNMENTID               VARCHAR2(50),
  GOVERNMENTID_TYPE          VARCHAR2(255),
  ADDRESS_STREET             VARCHAR2(50),
  ADDRESS_APRT_NO            VARCHAR2(30),
  ADDRESS_CITY               VARCHAR2(30),
  ADDRESS_STATE              VARCHAR2(30),
  ADDRESS_ZIP                VARCHAR2(30),
  EXAMINEE_COUNTY_CODE       VARCHAR2(10),
  REG_TC_COUNTY_CODE         VARCHAR2(10),
  REG_TC_CODE                VARCHAR2(10),
  HOME_LANGUAGE              VARCHAR2(2),
  CHRONOLOGICAL_AGE          VARCHAR2(3),
  AGE_GROUP                  VARCHAR2(2),
  EXAMINEE_MAIL_ADDRESS      VARCHAR2(200),
  EMAIL                      VARCHAR2(100),
  ALTERNATE_EMAIL            VARCHAR2(100),
  PHONE_NO                   VARCHAR2(30),
  CELL_PHONE_NO              VARCHAR2(30),
  ALTERNATE_NO               VARCHAR2(200),
  CONTACT                    VARCHAR2(2),
  REGISTERED_AT_TEST_CENTER  VARCHAR2(100),
  HIGHEST_LEVEL_EDU          VARCHAR2(2),
  READINESS_ASSESSMENT VARCHAR2(100),
  TASCREADINESS VARCHAR2(100),
  STUDENTCOUNTYNAME VARCHAR2(100),
  SPECIALCODE_A_J VARCHAR2(100),
  SPECIALCODE_K VARCHAR2(100),
  SPECIALCODE_L VARCHAR2(100),
  SPECIALCODE_M VARCHAR2(100),
  SPECIALCODE_N_S VARCHAR2(100),
  SPECIALCODE_T VARCHAR2(100),
  SPECIALCODE_U VARCHAR2(100),
  SPECIALCODE_V VARCHAR2(100),
  SPECIALCODE_W VARCHAR2(100),
  SPECIALCODE_X VARCHAR2(100),
  SPECIALCODE_Y VARCHAR2(100),
  SPECIALCODE_Z VARCHAR2(100),
  ATTENDCOLLEGE VARCHAR2(100),
  GRADE VARCHAR2(100),
  ALTERNATEID VARCHAR2(100),
  CORRECTIONSID VARCHAR2(100),
  CREDENTIALINGJID VARCHAR2(100),
  TESTCANDIDATEFLAG VARCHAR2(100),
  GENERATION VARCHAR2(100),
  INHIGHSCHOOL VARCHAR2(100),
  OPTIONS VARCHAR2(100),
  RELEASESCORESINDICATOR VARCHAR2(100),
  STUDENT_UPDATE_DATE        VARCHAR2(6),
  CUSTOMERID                 NUMBER,
  ADMINID                    NUMBER,
  ORG_NODEID                 NUMBER,
  ORG_NODE_CODE_PATH         VARCHAR2(100),
  STUDENT_CREATED_DATE       VARCHAR2(20),
  PROCESS_ID                 NUMBER,
  TASK_ID                    NUMBER,
  VALIDATION_STATUS          VARCHAR2(2),
  IS_FILE_VALID              VARCHAR2(2),
  VALIDATION_LOG             VARCHAR2(400),
  IS_LATEST                  VARCHAR2(1),
  FILENAME                   VARCHAR2(100),
  DATETIMESTAMP              DATE
);

--ALTER TABLE ERR_STUDENT_REG_INFO_HIST MODIFY BIRTHDATE VARCHAR2(8);

CREATE TABLE ERR_STUDENT_SURVEY_HIST
(
STG_REG_INFO_ID NUMBER,
DRC_STUDENTID NUMBER,
SURVAY_NAME   VARCHAR2(100),
SURVEY_VALUE  VARCHAR2(100),
DATETIMESTAMP DATE
);

CREATE TABLE ERR_STUDENT_DOC_INFO_HIST
(    
  STG_STUDENT_DOCID      NUMBER NOT NULL,
  DOCUMENTID             NUMBER NOT NULL,
  STUDENT_REGID          NUMBER,
  DRC_STUDENTID          NUMBER NOT NULL,
  SCHEDULE_ID            VARCHAR2(10),
  TCA_SCHEDULED_DATE     VARCHAR2(10),
  DATE_SCHEDULED         VARCHAR2(20),
  IMAGING_ID             VARCHAR2(26),
  LITHOCODE              VARCHAR2(8),
  CONTENT_CODE           VARCHAR2(2) NOT NULL,
  FORM                   VARCHAR2(5) NOT NULL,
  TEST_LANGUAGE          VARCHAR2(1) NOT NULL,
  TEST_MODE              VARCHAR2(2) NOT NULL,
  FIELD_TEST_FORM        VARCHAR2(3),
  CHANGED_FORM_FLAG      VARCHAR2(1),
  BARCODE_ID             VARCHAR2(16),
  CHECKIN_DATE           VARCHAR2(20),
  EXPIRED_DATE           VARCHAR2(20),
  EXPIRED_REASON         VARCHAR2(2000),
  SCHED_TC_COUNTY_CODE   VARCHAR2(8),
  SCHED_TC_CODE          VARCHAR2(8),
  SCHED_EDU_CENTER_CODE  VARCHAR2(8),
  REGION_ORGCODE         VARCHAR2(15),
  STATUS_CODE            VARCHAR2(4),
  TEST_EVENT_UPDATE_DATE VARCHAR2(14),
  LARGEPRINT             VARCHAR2(1),
  BRAILLE                VARCHAR2(1),
  STG_STUDENT_BIO_ID     NUMBER,
  ORG_NODEID             NUMBER,
  ORG_NODE_CODE_PATH     VARCHAR2(100),
  BASE_DOCUMENT_FLAG     VARCHAR(1),--BaseDocumentFlag
  DOC_PROCESS_STATUS     VARCHAR2(3), --Checks- SCH- Scheduled, CHI- CheckIn, EXP- Expired, TES -TestEventScores
  DOC_CREATED_DATE       VARCHAR2(20),--DOC CREATED DATE ??
  CUSTOMERID             NUMBER,
  ADMINID                NUMBER,
  PROCESS_ID             NUMBER,
  TASK_ID                NUMBER,
  VALIDATION_STATUS      VARCHAR2(2),
  IS_FILE_VALID          VARCHAR2(2),
  VALIDATION_LOG         VARCHAR2(400),
  IS_LATEST              VARCHAR2(1),
  FILENAME               VARCHAR2(100),
  DATETIMESTAMP         DATE DEFAULT SYSDATE
);

--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST RENAME COLUMN DATETIMETIMESTAMP TO DATETIMESTAMP;
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST RENAME COLUMN DOC_UPDATE_DATE TO STATUS_CODE;
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY STATUS_CODE VARCHAR2(4);
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST DROP COLUMN SCORING_COMPLETE_DATE;
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY TEST_EVENT_UPDATE_DATE VARCHAR2(14);

CREATE TABLE ERR_STUDENT_BIO_DIM_HIST
(
  STG_STUDENT_BIO_ID NUMBER not null,
  FIRST_NAME         VARCHAR2(32),
  MIDDLE_NAME        VARCHAR2(32),
  LAST_NAME          VARCHAR2(32),
  BIRTHDATE          VARCHAR2(10),
  DRC_STUDENTID      NUMBER NOT NULL,
  TEST_ELEMENT_ID    VARCHAR2(30) not null,
  INT_STUDENT_ID     VARCHAR2(52),
  EXT_STUDENT_ID     VARCHAR2(20),
  LITHOCODE          VARCHAR2(26),
  GENDERID           NUMBER,
  GRADEID            NUMBER,
  EDU_CENTERID       NUMBER,
  BARCODE            VARCHAR2(26),
  SPECIAL_CODES      VARCHAR2(26),
  STUDENT_MODE       VARCHAR2(2),
  ORG_NODEID         NUMBER,
  CUSTOMERID         NUMBER,
  ADMINID            NUMBER,
  IS_BIO_UPDATE_CMPL VARCHAR2(1),
  PP_IMAGING_ID      VARCHAR2(26),
  OAS_IMAGING_ID     VARCHAR2(26),
  PROCESS_ID         NUMBER,
  TASK_ID            NUMBER,
  DATETIMSTAMP       DATE
);

CREATE TABLE ERR_STUDENT_DEMO_HIST
(
STG_STUDENT_BIO_ID NUMBER,
DEMO_CODE VARCHAR2(200),
DEMO_VALUE VARCHAR2(200),
DEMOID NUMBER,
DEMO_VALID NUMBER,
SUBTEST_CODE VARCHAR2(100),
SUBTESTID NUMBER,
PROCESS_ID NUMBER,
CUSTOMERID NUMBER,
TASK_ID NUMBER,
VALIDATION_STATUS VARCHAR2(2),
IS_FILE_VALID VARCHAR2(2),
VALIDATION_LOG VARCHAR2(4000),
DATETIMESTAMP DATE DEFAULT SYSDATE
);

CREATE TABLE ERR_SUBTEST_SCORE_FACT_HIST
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  STG_STUDENT_DOCID  NUMBER,
  DRC_STUDENTID      NUMBER NOT NULL,
  CONTENT_CODE       VARCHAR2(2) NOT NULL,
  TEST_FORM          VARCHAR2(1) NOT NULL,
  STATUS_CODE        VARCHAR2(3),
  DATE_TEST_TAKEN    DATE,
  AAGE               VARCHAR2(5),
  AANCE              NUMBER,
  AANP               NUMBER,
  AANS               NUMBER,
  AASS               NUMBER,
  ACSIP              NUMBER,
  ACSIS              NUMBER,
  ACSIN              NUMBER,
  CSI                NUMBER,
  CSIL               NUMBER,
  CSIU               NUMBER,
  DIFF               VARCHAR2(5),
  GE                 VARCHAR2(5),
  HSE                VARCHAR2(1),
  LEX                NUMBER,
  LEXL               NUMBER,
  LEXU               NUMBER,
  NCE                NUMBER,
  NCR                NUMBER,
  NP                 NUMBER,
  NPA                NUMBER,
  NPG                NUMBER,
  NPL                NUMBER,
  NPH                NUMBER,
  NS                 NUMBER,
  NSA                NUMBER,
  NSG                NUMBER,
  OM                 VARCHAR2(5),
  OMS                NUMBER,
  OP                 NUMBER,
  OPM                NUMBER,
  PC                 NUMBER,
  PL                 VARCHAR2(100),
  PP                 NUMBER,
  PR                 NUMBER,
  SEM                NUMBER,
  SNPC               NUMBER,
  SS                 NUMBER,
  QTL                NUMBER,
  QTLL               NUMBER,
  QTLU               NUMBER,
  PROCESS_ID         NUMBER,
  TASK_ID            NUMBER,
  DATETIMESTAMP      DATE DEFAULT SYSDATE
);

CREATE TABLE ERR_OBJECTIVE_SCORE_FACT_HIST
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  DRC_STUDENTID    NUMBER NOT NULL,
  CONTENT_CODE     VARCHAR2(2) NOT NULL,
  OBJECTIVE_CODE   VARCHAR2(10) NOT NULL,
  TEST_FORM        VARCHAR2(1) NOT NULL,
  CONDCODE_CODE    VARCHAR2(100),
  TEST_DATE        DATE,
  NCR              NUMBER,
  OS               VARCHAR2(5),
  OPI              VARCHAR2(5),
  OPI_CUT          VARCHAR2(5),
  MEAN_IPI         VARCHAR2(5),
  OPIQ             NUMBER,
  OPIP             NUMBER,
  PC               NUMBER,
  PP               NUMBER,
  SS               NUMBER,
  PL               VARCHAR2(1),
  INRC             VARCHAR2(1),
  PROCESS_ID       NUMBER,
  TASK_ID          NUMBER,
  DATETIMESTAMP    DATE
);


CREATE TABLE ERR_ITEM_SCORE_FACT_HIST
(
  STG_STUDENT_BIO_ID NUMBER NOT NULL,
  DRC_STUDENTID      NUMBER NOT NULL,
  CONTENT_CODE   VARCHAR2(2) NOT NULL,
  OBJECTIVE_CODE VARCHAR2(10),
  FORM           VARCHAR2(10),
  GRADE          VARCHAR2(10),
  ITEM_TYPE      VARCHAR2(100),
  ITEM_CODE      VARCHAR2(100) NOT NULL,
  ITEM_NAME      VARCHAR2(100),
  READ_CODE      VARCHAR2(100),
  SCORE_VALUES   VARCHAR2(400),
  PROCESS_ID     NUMBER,
  TASK_ID        NUMBER,
  DATETIMESTAMP  DATE DEFAULT SYSDATE
);

-----------------
ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY TEST_EVENT_UPDATE_DATE VARCHAR2(14);

------------------------------
/*
ALTER TABLE STUDENT_REG_INFO ADD
(
UDB_PROCESSED_DATE DATE DEFAULT SYSDATE NOT NULL,
RECONCILE_EXPORT_STATUS VARCHAR2(1) DEFAULT 'N',
RECONCILE_EXPORT_DATE DATE
);
*/

ALTER TABLE STUDENT_REG_INFO ADD CONSTRAINT CHK_RECON_EXP_STAT_1
CHECK (RECONCILE_EXPORT_STATUS IN ('Y','N'));

/*
ALTER TABLE STUDENT_DOC_INFO ADD
(
UDB_PROCESSED_DATE DATE DEFAULT SYSDATE NOT NULL,
RECONCILE_EXPORT_STATUS VARCHAR2(1) DEFAULT 'N',
RECONCILE_EXPORT_DATE DATE
);
*/
ALTER TABLE STUDENT_DOC_INFO ADD CONSTRAINT CHK_RECON_EXP_STAT_2
CHECK (RECONCILE_EXPORT_STATUS IN ('Y','N'));


--------------------
ALTER TABLE STG_STUDENT_REG_INFO MODIFY LAST_NAME VARCHAR2(32);
ALTER TABLE STG_STUDENT_REG_INFO MODIFY FIRST_NAME VARCHAR2(32);

ALTER TABLE STUDENT_REG_INFO MODIFY LAST_NAME VARCHAR2(32);
ALTER TABLE STUDENT_REG_INFO MODIFY FIRST_NAME VARCHAR2(32);

ALTER TABLE STG_STUDENT_DOC_INFO MODIFY SCHEDULE_ID VARCHAR2(12);
ALTER TABLE STUDENT_DOC_INFO MODIFY SCHEDULE_ID VARCHAR2(12);

ALTER TABLE STG_STUDENT_DOC_INFO MODIFY FIELD_TEST_FORM VARCHAR2(5);
ALTER TABLE STUDENT_DOC_INFO MODIFY FIELD_TEST_FORM VARCHAR2(5);

ALTER TABLE STG_STUDENT_DOC_INFO MODIFY STATUS_CODE VARCHAR2(1);
ALTER TABLE STUDENT_DOC_INFO MODIFY STATUS_CODE VARCHAR2(1);

ALTER TABLE STG_STUDENT_DOC_INFO MODIFY SCHED_TC_CODE VARCHAR2(15);
--ALTER TABLE STG_STUDENT_DOC_INFO ADD REGION_ORGCODE VARCHAR2(15);

ALTER TABLE STUDENT_DOC_INFO MODIFY SCHED_TC_CODE VARCHAR2(15);
--ALTER TABLE STUDENT_DOC_INFO ADD REGION_ORGCODE VARCHAR2(15);

ALTER TABLE ERR_STUDENT_REG_INFO_HIST MODIFY LAST_NAME VARCHAR2(32);
ALTER TABLE ERR_STUDENT_REG_INFO_HIST MODIFY FIRST_NAME VARCHAR2(32);

ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY SCHEDULE_ID VARCHAR2(12);

ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY FIELD_TEST_FORM VARCHAR2(5);

ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY STATUS_CODE VARCHAR2(1);

ALTER TABLE ERR_STUDENT_DOC_INFO_HIST MODIFY SCHED_TC_CODE VARCHAR2(15);
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST ADD REGION_ORGCODE VARCHAR2(15);
--ALTER TABLE ERR_STUDENT_DOC_INFO_HIST ADD ORG_NODE_CODE_PATH VARCHAR2(100);

--ALTER TABLE STG_STUDENT_DOC_INFO ADD ORG_NODE_CODE_PATH VARCHAR2(100);
--ALTER TABLE STUDENT_DOC_INFO ADD ORG_NODEID NUMBER;
--ALTER TABLE ERR_STUDENT_DOC_INFO ADD ORG_NODEID NUMBER;

ALTER TABLE STG_STUDENT_DEMO MODIFY DEMO_VALUE VARCHAR2(255);
ALTER TABLE STUDENT_DEMO_VALUES MODIFY DEMO_VALUE VARCHAR2(255);

ALTER TABLE ERR_STUDENT_DEMO_HIST MODIFY DEMO_VALUE VARCHAR2(255);
ALTER TABLE STUDENT_DEMO_VALUES_HIST MODIFY DEMO_VALUE VARCHAR2(255);


ALTER TABLE STG_STUDENT_BIO_DIM MODIFY TEST_ELEMENT_ID VARCHAR2(50);
ALTER TABLE STUDENT_BIO_DIM MODIFY TEST_ELEMENT_ID VARCHAR2(50);
ALTER TABLE STUDENT_BIO_DIM_HIST MODIFY TEST_ELEMENT_ID VARCHAR2(50);
ALTER TABLE ERR_STUDENT_BIO_DIM_HIST MODIFY TEST_ELEMENT_ID VARCHAR2(50);


ALTER TABLE  TABLE_1_STU MODIFY TEST_ELEMENT_ID VARCHAR2(50);

CREATE INDEX IDX_STG_STUDENT_REG_INFO ON STG_STUDENT_REG_INFO(STG_REG_INFO_ID,DRC_STUDENTID,VALIDATION_STATUS);
CREATE INDEX IDX_STG_STUDENT_SURVEY ON STG_STUDENT_SURVEY(STG_REG_INFO_ID,DRC_STUDENTID);
CREATE INDEX IDX_ERR_STUDENT_REG_INFO ON ERR_STUDENT_REG_INFO(VALIDATION_STATUS,DRC_STUDENTID);

ALTER TABLE STG_STUDENT_REG_INFO MODIFY MIDDLE_NAME VARCHAR2(32);
ALTER TABLE STUDENT_REG_INFO MODIFY MIDDLE_NAME VARCHAR2(32);
ALTER TABLE ERR_STUDENT_REG_INFO_HIST MODIFY MIDDLE_NAME VARCHAR2(32);



---------------------------DML STATEMENT-----------------------
--ETL_JOBMASTER_CONFIG:PRISMGLOBAL
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_REG_INFO_LOAD','S_DRC_STG_STUDENT_REG_INFO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_DUPLICATE_STUDENT_REG_INFO','S_DRC_DUPLICATE_STUDENT_REG_INFO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_SURVEY_LOAD','S_DRC_STG_STUDENT_SURVEY_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_REG_INFO','S_DRC_PROCESS_STATUS_STG_REG_INFO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_STUDENT_REG_INFO_LOAD','S_DRC_OPR_STUDENT_REG_INFO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_REG_INFO','S_DRC_PROCESS_STATUS_OPR_REG_INFO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_DOC_INFO_LOAD','S_DRC_STG_STUDENT_DOC_INFO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_DOC_INFO','S_DRC_PROCESS_STATUS_STG_DOC_INFO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_BIO_DIM_LOAD','S_DRC_STG_STUDENT_BIO_DIM_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_BIO_DIM','S_DRC_PROCESS_STATUS_STG_BIO_DIM','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_DEMO_LOAD','S_DRC_STG_STUDENT_DEMO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_DEMO_VALUES','S_DRC_PROCESS_STATUS_STG_DEMO_VALUES','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_SUBTEST_SCORE_FACT_LOAD','S_DRC_STG_SUBTEST_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_SUBTEST_SCORE_FACT','S_DRC_PROCESS_STATUS_STG_SUBTEST_SCORE_FACT','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_OBJECTIVE_SCORE_FACT_LOAD','S_DRC_STG_OBJECTIVE_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_OBJ_SCORE_FACT','S_DRC_PROCESS_STATUS_STG_OBJ_SCORE_FACT','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_ITEM_SCORE_FACT_LOAD','S_DRC_STG_ITEM_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_STG_ITEM_SCORE_FACT','S_DRC_PROCESS_STATUS_STG_ITEM_SCORE_FACT','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
---
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_STUDENT_DOC_INFO_LOAD','S_DRC_OPR_STUDENT_DOC_INFO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_DOC_INFO','S_DRC_PROCESS_STATUS_OPR_DOC_INFO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_STUDENT_BIO_DIM_LOAD','S_DRC_OPR_STUDENT_BIO_DIM_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_BIO_LOAD','S_DRC_PROCESS_STATUS_OPR_BIO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_STUDENT_DEMO_LOAD','S_DRC_OPR_STUDENT_DEMO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_STUDENT_DEMO','S_DRC_PROCESS_STATUS_OPR_STUDENT_DEMO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_SUBTEST_DEMO_LOAD','S_DRC_OPR_SUBTEST_DEMO_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_SUBTEST_DEMO','S_DRC_PROCESS_STATUS_OPR_SUBTEST_DEMO','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_SUBTEST_SCORE_FACT_LOAD','S_DRC_OPR_SUBTEST_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_SUBTEST_LOAD','S_DRC_PROCESS_STATUS_OPR_SUBTEST_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_OBJECTIVE_SCORE_FACT_LOAD','S_DRC_OPR_OBJECTIVE_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_OBJ_LOAD','S_DRC_PROCESS_STATUS_OPR_OBJ_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_ITEM_SCORE_FACT_LOAD','S_DRC_OPR_ITEM_SCORE_FACT_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_PROCESS_STATUS_OPR_ITEM_LOAD','S_DRC_PROCESS_STATUS_OPR_ITEM_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
---New
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_BIO_INV_SUB_DEL','S_DRC_OPR_BIO_INV_SUB_DEL','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_GRADE_SELECTION_LOOKUP_LOAD','S_DRC_OPR_GRADE_SELECTION_LOOKUP_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_ORG_PRODUCT_LINK_LOAD','S_DRC_OPR_ORG_PRODUCT_LINK_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
---
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_REG_INFO_VALIDATION','S_DRC_STG_STUDENT_REG_INFO_VALIDATION','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_STG_STUDENT_DOC_INFO_VALIDATION','S_DRC_STG_STUDENT_DOC_INFO_VALIDATION','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);
---
INSERT INTO ETL_JOBMASTER_CONFIG(MAPPING_NAME,SESSION_NAME,WORKFLOW_NAME,REPOSITORY_SERVICE,INTEGRATION_SERVICE,DOMAIN_NAME,PROJECTID,CREATED_DATE_TIME,UPDATED_DATE_TIME) VALUES ('M_DRC_OPR_EXP_DOC_LOAD','S_DRC_OPR_EXP_DOC_LOAD','WKF_DRC_TASC_GHI_GRT_LOAD',NULL,NULL,NULL,1,SYSDATE,SYSDATE);


--------------------------------PROCEDURE----------------------------
--Procedure which will populate new demo for the customer
SP_TASC_DEMO_ADD_GHI.prc
--Procedure to truncate staging table
SP_TRUNCATE_STG_TASC_TABLES
--Package/Procedure 
PKG_PRF_ORG_USR
PKG_STUDENTDATA_EXTRACT
PKG_STUDENT_FILE_DOWNLOAD


--Procedure to update some demographic like Test_Form
-------------------------------
For Resolved Ethnicity Demo Follow the Demo Update Procedure..
1. Race fields value ‘N’ is added for all the customers in QA
2. Resolved Ethnicity has been corrected for all the customers in QA (Defect# 83470)
3. New Test Form Demo value will be populate through this script.
We are running the procedure  SP_TASC_UPD_DEMO to correct these two demographics

Below is the script
----------------------------------
--Populate New Demo
DECLARE
V_CUSTOMER_SUCCESS VARCHAR2(500);
BEGIN
FOR I IN (SELECT CUSTOMERID FROM CUSTOMER_INFO) 
  LOOP 
    SP_TASC_DEMO_ADD_GHI(IN_CUSTOMER_ID =>I.CUSTOMERID,OUT_STATUS => V_CUSTOMER_SUCCESS);
    DBMS_OUTPUT.PUT_LINE(V_CUSTOMER_SUCCESS);
	DBMS_OUTPUT.PUT_LINE('SUCCESS FOR CUSTOMER: = '||I.CUSTOMERID);
  END LOOP;                                            
END;


--Update Existing Demo
DECLARE
V_CUSTOMER_SUCCESS VARCHAR2(500);
BEGIN
FOR I IN (SELECT CUSTOMERID FROM CUSTOMER_INFO) 
  LOOP 
    SP_TASC_UPD_DEMO(IN_CUSTOMER_ID =>I.CUSTOMERID,OUT_STATUS => V_CUSTOMER_SUCCESS);
    DBMS_OUTPUT.PUT_LINE(V_CUSTOMER_SUCCESS);
	DBMS_OUTPUT.PUT_LINE('SUCCESS FOR CUSTOMER: = '||I.CUSTOMERID);
  END LOOP;                                            
END;


