 -- SELECT *  FROM PROJECT_DIM WHERE PROJECT_NAME = 'TASC';
 -- SELECT * FROM PRODUCT WHERE PROJECTID = 1;
 -- SELECT * FROM ASSESSMENT_DIM WHERE PRODUCTID = 1001;

--FORM_DIM
INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'G' AS FORM_NAME,
       'G' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='TASC') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;

INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'H' AS FORM_NAME,
       'H' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='TASC') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;

INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'I' AS FORM_NAME,
       'I' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='TASC') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;

INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'BR-G' AS FORM_NAME,
       'BR-G' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='TASC') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;

INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'BR-H' AS FORM_NAME,
       'BR-H' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='TASC') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;

BEGIN
DBMS_MVIEW.REFRESH('FORM_DIM','C');
END;

--LEVEL_MAP
INSERT INTO LEVEL_MAP
SELECT (SELECT MAX(LEVEL_MAPID) FROM LEVEL_MAP) + ROWNUM AS LEVEL_MAPID,
       A.LEVELID,
       A.FORMID,
       A.ASSESSMENTID,
       A.DATETIMESTAMP
FROM        
(SELECT 
       LVL.LEVELID,
       FRM.FORMID,
       ASES.ASSESSMENTID,
       SYSDATE AS DATETIMESTAMP
FROM LEVEL_DIM LVL,
     FORM_DIM FRM,
     ASSESSMENT_DIM ASES,
     PRODUCT PDT,
     PROJECT_DIM PJT
WHERE PJT.PROJECT_NAME='TASC'
  AND PJT.PROJECTID = PDT.PROJECTID
  AND ASES.PRODUCTID = PDT.PRODUCTID
  AND FRM.PROJECTID = PJT.PROJECTID
  AND LVL.PROJECTID = PJT.PROJECTID
  AND FRM.FORM_NAME IN ('G','H','I','BR-G','BR-H')
  ORDER BY LVL.LEVELID)A;
  
COMMIT;  
  
--SUBTEST_OBJECTIVE_MAP  
 DECLARE
  V_SOM_ID NUMBER;
  V_DATETIMESTAMP DATE := SYSDATE;
 BEGIN
  SELECT MAX(SUBT_OBJ_MAPID) INTO V_SOM_ID FROM SUBTEST_OBJECTIVE_MAP;
  FOR R_LEVEL_MAP IN (SELECT LM.LEVEL_MAPID
                    FROM LEVEL_MAP LM,
                          FORM_DIM FRM,
                          ASSESSMENT_DIM ASES,
                          PRODUCT PDT,
                          PROJECT_DIM PJT
                  WHERE PJT.PROJECT_NAME='TASC'
                    AND PJT.PROJECTID = PDT.PROJECTID
                    AND ASES.PRODUCTID = PDT.PRODUCTID
                    AND FRM.PROJECTID = PJT.PROJECTID
                    AND FRM.FORM_NAME IN ('G','H','I','BR-G','BR-H')
                    AND LM.FORMID  = FRM.FORMID
                    AND LM.ASSESSMENTID = ASES.ASSESSMENTID)
  LOOP
    FOR R_SOM IN (SELECT SOM.* 
                  FROM SUBTEST_OBJECTIVE_MAP SOM, 
                       FORM_DIM FRM,
                       PROJECT_DIM PJT,
                       ASSESSMENT_DIM ASES,
                       PRODUCT PDT,
                       LEVEL_MAP LM
                  WHERE PJT.PROJECT_NAME='TASC'
                  AND PJT.PROJECTID = PDT.PROJECTID
                  AND ASES.PRODUCTID = PDT.PRODUCTID
                  AND FRM.PROJECTID = PJT.PROJECTID
                  AND LM.ASSESSMENTID =  ASES.ASSESSMENTID
                  AND LM.FORMID = FRM.FORMID
                  AND SOM.ASSESSMENTID =  ASES.ASSESSMENTID
                  AND FRM.FORM_NAME =  'A'  
                  AND SOM.LEVEL_MAPID = LM.LEVEL_MAPID 
                  ORDER BY SOM.SUBT_OBJ_MAPID,SOM.SUBTESTID,SOM.OBJECTIVEID)
      LOOP
        V_SOM_ID := V_SOM_ID+1;
        
        INSERT INTO SUBTEST_OBJECTIVE_MAP VALUES(V_SOM_ID,R_SOM.SUBTESTID,R_SOM.OBJECTIVEID,R_LEVEL_MAP.LEVEL_MAPID,R_SOM.ASSESSMENTID,V_DATETIMESTAMP);
      END LOOP;    
  END LOOP;  
  COMMIT;                
 END;
 --SELECT * FROM SUBTEST_OBJECTIVE_MAP WHERE ASSESSMENTID = 1001
 
--ITEMSET_DIM
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (11081, 'Writing TE Final Score', '05', null, 3, null, 'TE', null, null, 2048, null, null, null, 1, SYSDATE);

insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (11082, 'Social Studies CR Scores', '02', null, 2, null, 'CR', null, null, 2052, null, null, null, 1, SYSDATE);  
commit;

 --SELECT MAX (ITEMSETID) FROM itemset_dim; ---11082
 
DROP SEQUENCE SEQ_ITEMSETID;

CREATE SEQUENCE SEQ_ITEMSETID
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 11083
INCREMENT BY 1
NOCACHE;



  
--SELECT * FROM OBJECTIVE_DIM;
--SELECT * FROM subtest_objective_map;
--SELECT * FROM level_map;
--SELECT * FROM grade_level_map;
--SELECT * FROM level_dim WHERE projectid = 1;
--SELECT * FROM form_dim;
