ALTER TABLE STG_STUDENT_DEMO ADD STG_STUDENT_DOCID NUMBER;
ALTER TABLE STG_OBJECTIVE_SCORE_FACT ADD STG_STUDENT_DOCID NUMBER;
ALTER TABLE STG_ITEM_SCORE_FACT ADD STG_STUDENT_DOCID NUMBER;
ALTER TABLE STG_STUDENT_REG_INFO MODIFY GOVERNMENTID VARCHAR2(255);
ALTER TABLE STUDENT_REG_INFO MODIFY GOVERNMENTID VARCHAR2(255);