--@\PKG_CONTRACT_PROPERTY.pck; ---not needed (handled by Joy) 
@\PKG_DELETE_FACT_TABLES.pck;
@\PKG_GET_MIG_RESULTS_GRT.pck;
@\PKG_MO_STUDENT_DATA_VALIDATION.pck;
@\PKG_PROC_MVIEW_REFRESH.pck;
--@\PKG_RESCORE_REQUEST.pck; ---not needed (handled by Joy) 
@\PKG_RPRT_STUD_DETAILS.pck;
--@\PRISM_REPORT.pck;
@\PKG_GROUP_DOWNLOADS_MO.pck;
@\PKG_REBUILD_INDEXES.pck;