---COMMENTED BY JOY
--@\PKG_CONTRACT_PROPERTY.pck;
@\PKG_DELETE_FACT_TABLES.pck;
@\PKG_GET_MIG_RESULTS_GRT.pck;
@\PKG_MO_STUDENT_DATA_VALIDATION.pck;
@\PKG_PROC_MVIEW_REFRESH.pck;
---COMMENTED BY JOY
--@\PKG_RESCORE_REQUEST.pck;
@\PKG_RPRT_STUD_DETAILS.pck;
--@\PRISM_REPORT.pck;
@\PKG_GROUP_DOWNLOADS_MO.pck;