------Remember to change the global schema name
ALTER TABLE ORG_NODE_DIM ADD CONSTRAINT CHK_ORG_MODE CHECK (ORG_MODE IN ('OL','PP','BO','PUBLIC', 'NON-PUBLIC'));

ALTER TABLE USERS ADD CONSTRAINT CHK_USERS_1 CHECK (USER_TYPE IN ('GRW','GRW_P', 'FE','PU','SSO','TU'));
ALTER TABLE USERS MODIFY USER_TYPE DEFAULT 'FE';

ALTER TABLE ITEM_SCORE_FACT  MODIFY OBJECTIVEID NOT NULL;
alter table  ITEM_SCORE_FACT modify READID NOT NULL;

ALTER TABLE STUDENT_PDF_FILES MODIFY IS_FILE_EXISTS DEFAULT 'N';

ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_IC_CUST_PROD_ID FOREIGN KEY (CUST_PROD_ID) REFERENCES prism_global.CUST_PRODUCT_LINK (CUST_PROD_ID);
ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_IC_GRADEID FOREIGN KEY (GRADE_ID) REFERENCES prism_global.GRADE_DIM (GRADEID);
ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_IC_STUD_BIO_ID FOREIGN KEY (STUDENT_BIO_ID) REFERENCES STUDENT_BIO_DIM (STUDENT_BIO_ID);

ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT PK_INVITATION_CODE_CLAIM PRIMARY KEY (INVITATION_CODE_CLAIM_ID) using index TABLESPACE FCAT_IDX1;
ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT U_INVITATION_CODE_CLAIM UNIQUE (ICID, ORG_USER_ID)  using INDEX TABLESPACE FCAT_IDX1;

ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_JOB_STATUS CHECK (JOB_STATUS  IN('SU','IP','CO','ER','DE','AR','DL','FT','NA'));
ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_REQUEST_TYPE CHECK (REQUEST_TYPE IN ('SDF','SBE','GDF'));





