-- Run this is ISTEP FACT Schema -- (remember to change the schema name for global schema) 

--Tables

CREATE SYNONYM SCORE_TYPE_LOOKUP FOR prism_global.SCORE_TYPE_LOOKUP;
CREATE SYNONYM PROJECT_DIM FOR prism_global.PROJECT_DIM;
CREATE SYNONYM PWD_HINT_QUESTIONS FOR prism_global.PWD_HINT_QUESTIONS;
CREATE SYNONYM ACTIVITY_TYPE FOR prism_global.ACTIVITY_TYPE;
--CREATE SYNONYM ROLE FOR prism_global.ROLE;


-- Sequences

CREATE SYNONYM SEQ_DASH_ACTION_ACCESS FOR prism_global.SEQ_DASH_ACTION_ACCESS;
CREATE SYNONYM SEQ_DASH_CONTRACT_PROP FOR prism_global.SEQ_DASH_CONTRACT_PROP;
CREATE SYNONYM SEQ_DASH_RPT_ACTION FOR prism_global.SEQ_DASH_RPT_ACTION;
CREATE SYNONYM DB_REPORT_ID_SEQ FOR prism_global.DB_REPORT_ID_SEQ;
CREATE SYNONYM DASH_MESSAGE_SEQ FOR prism_global.DASH_MESSAGE_SEQ;
CREATE SYNONYM RPTMSGTYPE_SEQ FOR prism_global.RPTMSGTYPE_SEQ;
CREATE SYNONYM NMN_LOOKUPID_SEQ FOR prism_global.NMN_LOOKUPID_SEQ;

-- TYPE

CREATE SYNONYM DYN_ATTR_DTLS FOR prism_global.DYN_ATTR_DTLS;