ALTER TABLE STUDENT_BIO_DIM ADD ACTIVATION_STATUS VARCHAR2(2);
UPDATE STUDENT_BIO_DIM SET ACTIVATION_STATUS = 'AC' WHERE ACTIVATION_STATUS IS NULL;--NEW
COMMIT;
ALTER TABLE STUDENT_BIO_DIM MODIFY IS_BIO_UPDATE_CMPL NULL;
ALTER TABLE STUDENT_BIO_DIM_HIST ADD PP_IMAGING_ID VARCHAR2(26);--NEW