----CHANGE THE GLOBAL SCHEMA NAME
GRANT SELECT ON SEQ_DEMOID TO PRISMGLOBAL;

GRANT SELECT,INSERT,DELETE ON DEMOGRAPHIC TO PRISMGLOBAL;
GRANT SELECT,INSERT,DELETE ON DEMOGRAPHIC_VALUES TO PRISMGLOBAL;
GRANT SELECT,INSERT,DELETE ON ORG_NODE_DIM TO PRISMGLOBAL;

COMMIT;

----TO REVOKE THE GRANTS GIVEN ABOVE RUN THE BELOW COMMENTED REVOKE COMMANDS
/*
REVOKE SELECT ON SEQ_DEMOID FROM PRISMGLOBAL;

REVOKE SELECT,INSERT,DELETE ON DEMOGRAPHIC FROM PRISMGLOBAL;
REVOKE SELECT,INSERT,DELETE ON DEMOGRAPHIC_VALUES FROM PRISMGLOBAL;
REVOKE SELECT,INSERT,DELETE ON ORG_NODE_DIM FROM PRISMGLOBAL;
*/
