ALTER TABLE ORG_NODE_DIM  ADD CONSTRAINT CHK_ORG_MODE CHECK (ORG_MODE IN ('OL','PP','BO')); 

ALTER TABLE USERS ADD CONSTRAINT CHK_ACT_STS_USERS CHECK (ACTIVATION_STATUS IN ('AC', 'IN','SS'));
ALTER TABLE USERS ADD CONSTRAINT PK_USERNAME UNIQUE (USERNAME);

ALTER TABLE STUDENT_BIO_DIM ADD CONSTRAINT STUDENT_BIO_DIM_UK UNIQUE (TEST_ELEMENT_ID, CUSTOMERID, STUDENT_MODE);

--ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_INVITATION_CODE_2 FOREIGN KEY (ADMINID) REFERENCES PRISMGLOBAL.ADMIN_DIM (ADMINID);
--ALTER TABLE INVITATION_CODE ADD CONSTRAINT FK_INVITATION_CODE_3 FOREIGN KEY (CUSTOMERID) REFERENCES PRISMGLOBAL.CUSTOMER_INFO (CUSTOMERID);
ALTER TABLE INVITATION_CODE MODIFY ORG_NODEID NOT NULL;
--ALTER TABLE INVITATION_CODE MODIFY ADMINID NOT NULL;
--ALTER TABLE INVITATION_CODE MODIFY CUSTOMERID  NOT NULL;

ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT PK_INVITATION_CODE_CLAIM PRIMARY KEY (ICID, ORG_USER_ID);
ALTER TABLE INVITATION_CODE_CLAIM ADD CONSTRAINT FK_INVITATION_CODE_CLAIM_1 FOREIGN KEY (ICID) REFERENCES INVITATION_CODE (ICID);

ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_JOB_STATUS CHECK (JOB_STATUS IN('SU','IP','CO','ER','DE','AR','DL','FT','NRF'));
ALTER TABLE JOB_TRACKING ADD CONSTRAINT CHK_REQUEST_TYPE CHECK (REQUEST_TYPE IN ('SDF','SBE','GDF','FTP'));

ALTER TABLE STUDENT_PDF_FILES MODIFY FILENAME NOT NULL;

ALTER TABLE INVITATION_CODE MODIFY CREATED_BY_ID NOT NULL;

ALTER TABLE INVITATION_CODE_CLAIM MODIFY CLAIM_DATE default SYSDATE;


