insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('INVITATION_CODE_CLAIM_ID_SEQ', 'INVITATION_CODE_CLAIM', 22944600, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ORG_PRODUCT_LINK', 'ORG_PRODUCT_LINK', 202305, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ARTICLE_CONTENT_SEQ', 'ARTICLE_CONTENT', 17394, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ACTIVITYID_SEQ', 'USER_ACTIVITY_HISTORY', 717890, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ACAD_STD_SUMM_FACT_SEQ', 'ACAD_STD_SUMM_FACT', 3311600, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ARTICLE_METADATA_SEQ', 'ARTICLE_METADATA', 25431, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ORG_NODE_DIM', 'ORG_NODE_DIM', 898945, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_OBJ_SCORE_FACT_ID', 'OBJECTIVE_SCORE_FACT', 117987600, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ISTEP_PROCESS_ID', 'STG_PROCESS_STATUS', 2291756, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_IC_ID', 'INVITATION_CODE', 22983306, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('PWD_HINT_ANSWERS_SEQ', 'PWD_HINT_ANSWERS', 301708, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('PERF_MATRIX_SEQ', 'PERF_MATRIX_FACT', 38257421, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ORG_USER_ID_SEQ', 'ORG_USERS', 4081047, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_PASSWORD_HISTORY', 'PASSWORD_HISTORY', 1, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('USER_ID_SEQ', 'USERS', 4066618, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SUBTEST_FACT_SEQ', 'SUBTEST_SCORE_FACT', 84019500, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('STUDENT_PDF_SEQ', 'STUDENT_PDF_FILES', 23612873, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_STATE_MEAN_IPI_SCORE', 'STATE_MEAN_IPI_SCORE', 3795, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('METADATA_CATEGORY_SEQ', 'CATEGORY_SEQ', 1860, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('OBJECTIVE_FACT_SEQ', 'OBJECTIVE_SCORE_FACT', 117987600, 1, 'ISTEPSCB');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('DASH_MESSAGE_SEQ', 'DASH_MESSAGE_TYPE', 1500, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('DB_REPORT_ID_SEQ', 'DASH_REPORTS', 10120, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('NMN_LOOKUPID_SEQ', 'NP_MEAN_NCE_LOOKUP', 40001, 4, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('RPTMSGTYPE_SEQ', 'DASH_MESSAGES', 1500, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_DASH_ACTION_ACCESS', 'DASH_ACTION_ACCESS', 5241, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_DASH_CONTRACT_PROP', 'DASH_CONTRACT_PROP', 213, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_DASH_RPT_ACTION', 'DASH_RPT_ACTION', 121, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_SCORE_LKP_ID', 'SCORE_TYPE_LOOKUP', 101, 1, 'PRISMGLOBAL');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('STUD_EXTRACTID_SEQ', 'STUDENTDATA_EXTRACT', 4982, 2, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_TASC_PROCESS_ID', 'STG_PROCESS_STATUS', 818841, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_TASC_HIER_PROCESS_ID', 'STG_HIER_PROCESS_STATUS', 262, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_DEMO_VALID', 'DEMOGRAPHIC_VALUES', 7761, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_DEMOID', 'DEMOGRAPHIC', 2181, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('PWD_HINT_ANSWERS_SEQ', 'PWD_HINT_ANSWERS', 1546, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('PERF_LOG_SEQ', 'PERF_LOG', 4204906, 5, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ORG_USER_ID_SEQ', 'ORG_USERS', 8121, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('METADATA_CATEGORY_SEQ', ' NULL', 1860, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('JOB_SEQ', 'JOB_TRACKING', 6609, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('INVITATION_CODE_CLAIM_ID_SEQ', 'INVITATION_CODE_CLAIM', 22944600, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ARTICLE_METADATA_SEQ', 'ARTICLE_METADATA', 25431, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ARTICLE_CONTENT_SEQ', 'ARTICLE_CONTENT', 17394, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('ACTIVITYID_SEQ', 'USER_ACTIVITY_HISTORY', 134441, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ER_TEST_SCHEDULE', 'ER_TEST_SCHEDULE', 1, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ER_STUDENT_SCHED_HISTORY', 'ER_STUDENT_SCHED_HISTORY', 1, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ER_STUDENT_DEMO', 'ER_STUDENT_DEMO', 1, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('USER_ID_SEQ', 'USERS', 8120, 1, 'TASC');

insert into GLOBAL_SEQ_BUMP (SEQUENCE_NAME, TABLE_NAME, LAST_NUMBER, INCREMENT_BY, SEQUENCE_OWNER)
values ('SEQ_ER_EXCEPTION_DATA', 'ER_EXCEPTION_DATA', 1, 1, 'TASC');

commit;

