--UPDATE GLOBAL_SEQ_BUMP SET SEQUENCE_OWNER = 'PRISMGLOBAL' WHERE SEQUENCE_OWNER  IS NULL;
--UPDATE GLOBAL_SEQ_BUMP SET SEQUENCE_OWNER = 'ISTEPSCB' WHERE SEQUENCE_OWNER = 'ISTEPPERF';

---IN THE GLOBAL SCHEMA RUN THE BELOW UPDATE 
UPDATE GLOBAL_SEQ_BUMP G SET G.LAST_NUMBER = (SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME=G.SEQUENCE_NAME)
  WHERE  G.SEQUENCE_OWNER = 'PRISMGLOBAL';
  
COMMIT;

