
---IN THE ISTEP SCHEMA RUN THE BELOW UPDATE 
---CHANGE THE ISETP SCHEMA NAME
 UPDATE PRISMGLOBAL.GLOBAL_SEQ_BUMP G SET G.LAST_NUMBER = (SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME=G.SEQUENCE_NAME)
  WHERE  G.SEQUENCE_OWNER = 'ISTEPSCB';
  
COMMIT; 