
---IN THE TASC SCHEMA RUN THE BELOW UPDATE 
---CHANGE THE TASC SCHEMA NAME
UPDATE PRISMGLOBAL.GLOBAL_SEQ_BUMP G SET G.LAST_NUMBER = (SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME=G.SEQUENCE_NAME)
  WHERE  G.SEQUENCE_OWNER = 'TASC';
  
COMMIT; 

