CREATE OR REPLACE PROCEDURE PRC_REFRESH_PRINCIPAL_USER
AS
begin

 DBMS_MVIEW.REFRESH('MV_PRINCIPAL_USER_SEL_LOOKUP', 'C');
 DBMS_MVIEW.REFRESH('MV_LVL2_PRCPL_USER_SEL_LOOKUP', 'C');

end PRC_REFRESH_PRINCIPAL_USER;
/
