CREATE MATERIALIZED VIEW LOG ON SUBTEST_SCORE_FACT; 


CREATE MATERIALIZED VIEW MV_RPRT_STUD_DETAILS
REFRESH FAST ON DEMAND
AS
SELECT
SCR.SUBTEST_FACTID,
SCR.STUDENT_BIO_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_COLUMNTYPE=>'FIRST_NAME') AS FIRST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_COLUMNTYPE=>'LAST_NAME') AS LAST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_COLUMNTYPE=>'MIDDLE_NAME') AS MIDDLE_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_COLUMNTYPE=>'BIRTHDATE') AS BIRTHDATE,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_BIO(P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID,P_COLUMNTYPE=>'INT_STUDENT_ID') AS LOCAL_STUDENT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_COLUMNTYPE=>'ORG_MODE') AS DISTRICT_MODE,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICT_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_COLUMNTYPE=>'ORG_NODE_NAME') AS DISTRICT_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_COLUMNTYPE=>'ORG_MODE') AS SCHOOL_MODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SCHOOL_NAME_CODE(P_ORG_NODEID =>SCR.ORG_NODEID,P_COLUMNTYPE=>'ORG_NODE_NAME') AS SCHOOL_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_DISTRICTID(P_ORG_NODEID =>SCR.ORG_NODEID) AS DISTRICT_ORG_NODEID,
SCR.ORG_NODEID AS SCHOOL_ORG_NODEID,
SCR.CUST_PROD_ID,
SCR.ASSESSMENTID,
SCR.CONTENTID,
SCR.SUBTESTID,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_NAME') AS SUBTEST_NAME,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_CODE') AS SUBTEST_CODE,
PKG_RPRT_STUD_DETAILS.SF_GET_SUBTEST_DETAILS( P_SUBTESTID=>SCR.SUBTESTID, P_COLUMNTYPE =>'SUBTEST_SEQ') AS SUBTEST_SEQ,
SCR.GENDERID,
SCR.GRADEID,
SCR.LEVELID,
SCR.FORMID,
SCR.ADMINID,
SCR.SS,
SCR.PL,
SCR.GE,
SCR.STATUS_CODE,
SCR.HSE,

PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Disability_Status',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS DISABILITY_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Ethnicity',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ETHNICITY_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Eng_Prof_Status',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ELL_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Migrant_Status',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS MIGRANT_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'Economic_Status',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS ECONOMIC_STATUS_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'School_Enrolled',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS FAY_SCHOOL_ID,
PKG_RPRT_STUD_DETAILS.SF_GET_STUDENT_DEMO_VALID( P_DEMOCODE=>'District_Enrolled',P_STUDENT_BIO_ID=>SCR.STUDENT_BIO_ID,P_CUST_PROD_ID=>SCR.CUST_PROD_ID,P_ADMINID=>SCR.ADMINID) AS FAY_DISTRICT_ID,

PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'01', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_KEY_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'02', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_CRAFT_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'03', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_RD_VCBLRY_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'04', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_TXT_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'05', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_RSRCH_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'06', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_LANG_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'01', OBJECTIVE_CODE=>'07', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_ELA_WR_LTSN_PL,

PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'01', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_ALGEBRA_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'02', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_BASE_TEN_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'03', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_FRACTIONS_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'04', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_MSMNT_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'05', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_RATIO_PROP_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'06', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_NUMBR_SYS_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'07', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_EXPR_EQU_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'08', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_FUNCTIONS_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'09', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_GEOMETRY_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'02', OBJECTIVE_CODE=>'10', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_MA_STAT_PROB_PL,


PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'01', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_CONN_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'02', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_INQ_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'03', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_PHY_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'04', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_EARTH_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'05', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_ENV_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'03', OBJECTIVE_CODE=>'06', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SCI_APPL_PL,

PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'04', OBJECTIVE_CODE=>'01', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SS_GEO_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'04', OBJECTIVE_CODE=>'02', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SS_HIST_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'04', OBJECTIVE_CODE=>'03', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SS_POL_SCI_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'04', OBJECTIVE_CODE=>'04', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SS_ECO_PL,
PKG_RPRT_STUD_DETAILS.SF_GET_OBJECTIVE_PL(SUBTEST_CODE=>'04', OBJECTIVE_CODE=>'05', P_STUDENT_BIO_ID =>SCR.STUDENT_BIO_ID, p_columntype =>'PL',p_subtest_id=>SCR.SUBTESTID) AS OBJ_SS_BHVIR_PL,

SCR.DATETIMESTAMP
FROM SUBTEST_SCORE_FACT SCR ;



