SELECT * FROM CUSTOMER_INFO;--1028
SELECT * FROM CUST_PRODUCT_LINK WHERE CUSTOMERID = 1028;

SELECT * FROM CUST_PRODUCT_LINK --5141

--ORG_NODE_DIM
BEGIN
	INSERT INTO ORG_NODE_DIM VALUES (0,'ROOT','ROOT',0,'NA','NA','PUBLIC',0,NULL,NULL,1106,SYSDATE,SYSDATE);
	INSERT INTO ORG_NODE_DIM VALUES (SEQ_ORG_NODE_DIM.NEXTVAL,'Wisconsin State DPI','WI',1,'WI','WI','PUBLIC',0,'0~WI',NULL,1106,SYSDATE,SYSDATE);
	COMMIT;
END;

-- ORG_PROD_LINK
DECLARE
  V_CUST_PROD_ID NUMBER := 0;
BEGIN
  SELECT CUST_PROD_ID INTO V_CUST_PROD_ID FROM CUST_PRODUCT_LINK WHERE CUSTOMERID =1106;

  FOR I IN (SELECT ORG_NODEID FROM ORG_NODE_DIM WHERE CUSTOMERID =1106) LOOP
    INSERT INTO ORG_PRODUCT_LINK VALUES(SEQ_ORG_PRODUCT_LINK.NEXTVAL,i.ORG_NODEID,V_CUST_PROD_ID,SYSDATE);
  END LOOP;
  COMMIT;
END;


--ctbadmin USERS
--pwd and salt need to be updated by java program
DECLARE
  V_CUSTOMERID NUMBER := 0;

BEGIN
  SELECT CUSTOMERID INTO V_CUSTOMERID FROM CUSTOMER_INFO WHERE CUSTOMER_NAME = 'Wisconsin State DPI';

  INSERT INTO USERS VALUES (USER_ID_SEQ.NEXTVAL,'ctbadmin','ctbadminWI','WITASC','DRC',NULL,
                            'abir.d@tcs.com',NULL,NULL,'USA','Monterey','93940','CA',V_CUSTOMERID,'N',NULL,NULL,'N',
                            'pwd','salt',
                            NULL,NULL,NULL,'FE','SS',SYSDATE,NULL);
  COMMIT;
END;


--USER_ROLE
DECLARE
  V_USERID NUMBER := 0;
BEGIN
  SELECT USERID INTO V_USERID FROM USERS WHERE USERNAME = 'ctbadmin';

  FOR I IN (SELECT ROLEID FROM ROLE WHERE ROLEID in (1,2,3,7)) LOOP
    INSERT INTO USER_ROLE VALUES (V_USERID, I.ROLEID, SYSDATE, NULL);
  END LOOP;
  COMMIT;
END;

--ORG_USER
DECLARE
  V_ORG_NODEID NUMBER := 0;
  V_USERID NUMBER := 0;
  V_ADMIN_ID NUMBER := 0;
BEGIN
  SELECT ORG_NODEID INTO V_ORG_NODEID FROM ORG_NODE_DIM WHERE ORG_NODE_LEVEL=1 AND CUSTOMERID =1106;
  SELECT USERID INTO V_USERID FROM USERS WHERE USERNAME = 'ctbadmin';
  SELECT ADMINID INTO V_ADMIN_ID from ADMIN_DIM WHERE IS_CURRENT_ADMIN = 'Y';

  INSERT INTO ORG_USERS VALUES (ORG_USER_ID_SEQ.NEXTVAL,V_USERID,V_ORG_NODEID,1,V_ADMIN_ID,'AC',SYSDATE,NULL); 
  COMMIT;
END;

