CREATE OR REPLACE FUNCTION SF_STG_BIO_DETAILS_ID(IN_VAR NUMBER) RETURN NUMBER IS
  V_IN_VAR          NUMBER := IN_VAR;
  V_OUT_ID NUMBER := 0;
BEGIN
  IF (V_IN_VAR = 1) THEN
    SELECT  SEQ_ISTEP_PROCESS_ID.NEXTVAL INTO V_OUT_ID FROM DUAL;
  END IF;
  RETURN V_OUT_ID;
END SF_STG_BIO_DETAILS_ID;
/
