SELECT COUNT (1) FROM MIG_GRW_USERS; --12867
SELECT COUNT (1) FROM MIG_GRW_ORG_USERS;---12867
SELECT COUNT (1) FROM MIG_GRW_USER_SELECTION_LOOKUP; ---23959
SELECT COUNT (1) FROM MIG_USC_BIO_LINK; --- 785905
SELECT COUNT (1) FROM MIG_PERF_MATRIX_BIO; --- 729243
INSERT INTO ROLE VALUES (8,'ROLE_GRW','Growth Report User',SYSDATE,SYSDATE);
CREATE TABLE MIG_GRW_USERS_MAP AS 
SELECT USERID AS MIG_USERID,
       USER_ID_SEQ.NEXTVAL AS GENERATED_USERID,
       USERNAME,
       DISPLAY_USERNAME,
       LAST_NAME,
       FIRST_NAME,
       MIDDLE_NAME,
       EMAIL_ADDRESS,
       PHONE_NO,
       STREET,
       COUNTRY,
       CITY,
       ZIPCODE,
       STATE,
       CUSTOMERID,
       IS_FIRSTTIME_LOGIN,
       LAST_LOGIN_ATTEMPT,
       PASSWORD_EXPR_DATE,
       IS_NEW_USER,
       PASSWORD,
       SALT,
       LAST_LOGIN_DATE,
       SIGNED_USER_AGREEMENT,
       AUTO_GENERATED_USER,
       USER_TYPE,
       ACTIVATION_STATUS,
       SYSDATE AS CREATED_DATE_TIME,
       SYSDATE AS UPDATED_DATE_TIME
FROM MIG_GRW_USERS; 

CREATE TABLE MIG_GRW_ORG_USERS_MAP AS 
SELECT  ORG_USER_ID AS MIGRATED_ORG_USER_ID,
        ORG_USER_ID_SEQ.NEXTVAL AS GENARATED_ORG_USER_ID,
        USERID,
        ORG_NODEID,
        ORG_NODE_LEVEL,
        ADMINID,
        ACTIVATION_STATUS,
        SYSDATE AS CREATED_DATE_TIME,
        SYSDATE AS UPDATED_DATE_TIME
FROM MIG_GRW_ORG_USERS;

CREATE TABLE USERS_BKP_072914 AS SELECT * FROM USERS;---593220
SELECT COUNT (1) FROM USERS; ---606087

INSERT INTO USERS  
SELECT GENERATED_USERID AS USERID, 
       USERNAME,
       DISPLAY_USERNAME,
       LAST_NAME,
       FIRST_NAME,
       MIDDLE_NAME,
       EMAIL_ADDRESS,
       PHONE_NO,
       STREET,
       COUNTRY,
       CITY,
       ZIPCODE,
       STATE,
       CUSTOMERID,
       IS_FIRSTTIME_LOGIN,
       LAST_LOGIN_ATTEMPT,
       PASSWORD_EXPR_DATE,
       IS_NEW_USER,
       PASSWORD,
       SALT,
       LAST_LOGIN_DATE,
       SIGNED_USER_AGREEMENT,
       AUTO_GENERATED_USER,
       USER_TYPE,
       ACTIVATION_STATUS,
       CREATED_DATE_TIME,
       UPDATED_DATE_TIME
FROM  MIG_GRW_USERS_MAP;

CREATE TABLE ORG_USERS_BKP_072914 AS SELECT * FROM ORG_USERS;--2815721
SELECT COUNT(1) FROM ORG_USERS; --2828588
INSERT INTO ORG_USERS  
SELECT  ORG.GENARATED_ORG_USER_ID AS ORG_USER_ID,
        (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE ORG.USERID = USR.MIG_USERID) AS USERID,
        ORG.ORG_NODEID,
        ORG.ORG_NODE_LEVEL,
        ORG.ADMINID,
        ORG.ACTIVATION_STATUS,
        ORG.CREATED_DATE_TIME,
        ORG.UPDATED_DATE_TIME
FROM MIG_GRW_ORG_USERS_MAP ORG;

INSERT INTO User_Role 
SELECT MAIN.USERID AS USER_ID, 
       MAIN.ROLEID AS ROLE_ID,
       SYSDATE,SYSDATE
  FROM (SELECT DISTINCT U.USERID, R.ROLEID
          FROM USERS U, ROLE R
         WHERE R.ROLE_NAME IN ('ROLE_USER', 'ROLE_GRW')
         AND U.CUSTOMERID = 1000
         AND USER_TYPE in ('GRW','GRW_P')) MAIN,
       USER_ROLE UR
 WHERE MAIN.USERID = UR.USERID(+)
   AND MAIN.ROLEID = UR.ROLEID(+)
   AND UR.USERID IS NULL;

CREATE TABLE USER_SEL_LOOKUP_BKP_07302014 AS SELECT * FROM USER_SELECTION_LOOKUP ;
TRUNCATE TABLE USER_SELECTION_LOOKUP;
SELECT COUNT (1) FROM USER_SELECTION_LOOKUP; ---23919 
INSERT INTO USER_SELECTION_LOOKUP
SELECT (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE USL.USERID = USR.MIG_USERID) AS USERID,
       USL.CUST_PROD_ID,
       USL.GRADEID,
       USL.SUBTESTID,
       SYSDATE AS DATETIMESTAMP
FROM MIG_GRW_USER_SELECTION_LOOKUP USL WHERE CUST_PROD_ID=5001;

SELECT COUNT (1) FROM USC_LINK;---785905
INSERT INTO USC_LINK 
SELECT (SELECT MP.GENARATED_ORG_USER_ID 
               FROM MIG_GRW_ORG_USERS_MAP MP 
               WHERE MP.MIGRATED_ORG_USER_ID = LNK.ORG_USER_ID) AS ORG_USER_ID,
       LNK.CUST_PROD_ID,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = LNK.TEST_ELEMENT_ID) AS STUDENT_BIO_ID ,
       LNK.SUBTESTID,
       SYSDATE AS DATETIMESTAMP
 FROM MIG_USC_BIO_LINK LNK
 WHERE  LNK.CUST_PROD_ID = 5001;
 
CREATE TABLE PERF_MATRIX_FACT_BKP_07302014 AS SELECT * FROM PERF_MATRIX_FACT;
TRUNCATE TABLE PERF_MATRIX_FACT;

INSERT INTO PERF_MATRIX_FACT_1
SELECT PERF_MATRIX_SEQ.NEXTVAL AS PERF_MATRIX_ID,
       ORG_NODEID,
       CUST_PROD_ID,
       STUDENT_NAME,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = CURR_TEST_ELEMENT_ID) AS CURR_STUDENT_BIO_ID,
       --CURR_TEST_ELEMENT_ID,
       (SELECT STD.STUDENT_BIO_ID FROM STUDENT_BIO_DIM STD
                WHERE STD.TEST_ELEMENT_ID = PREV_TEST_ELEMENT_ID) AS PREV_STUDENT_BIO_ID,
       --PREV_TEST_ELEMENT_ID,
       SUBTESTID,
       CURR_GRADEID,
       PREV_GRADEID,
       CURR_ADMINID,
       PREV_ADMINID,
       CURR_SC,
       PREV_SC,
       (SELECT GENERATED_USERID FROM MIG_GRW_USERS_MAP USR WHERE USR.MIG_USERID = USER_ID) AS USER_ID,
       PERF_LEVEL,
       SYSDATE AS DATETIMESTAMP
FROM  MIG_PERF_MATRIX_BIO;      

INSERT INTO PERF_MATRIX_FACT  SELECT * FROM PERF_MATRIX_FACT_1;

