SELECT * FROM ISTEPPRODCOPY.ORG_NODE_DIM MINUS SELECT * FROM ORG_NODE_DIM;
SELECT * FROM ISTEPPRODCOPY.ORG_PRODUCT_LINK MINUS SELECT * FROM ORG_PRODUCT_LINK;
SELECT * FROM ISTEPPRODCOPY.ORG_TEST_PROGRAM_LINK MINUS SELECT * FROM ORG_TEST_PROGRAM_LINK;
SELECT * FROM ISTEPPRODCOPY.USERS MINUS SELECT * FROM USERS;
SELECT * FROM ISTEPPRODCOPY.ORG_USERS MINUS SELECT * FROM ORG_USERS;
SELECT * FROM ISTEPPRODCOPY.EDU_CENTER_DETAILS MINUS SELECT * FROM EDU_CENTER_DETAILS;
SELECT * FROM ISTEPPRODCOPY.EDU_CENTER_USER_LINK MINUS SELECT * FROM EDU_CENTER_USER_LINK; 
SELECT * FROM ISTEPPRODCOPY.STUDENT_BIO_DIM MINUS SELECT * FROM STUDENT_BIO_DIM;
SELECT * FROM ISTEPPRODCOPY.SUBTEST_SCORE_FACT MINUS SELECT * FROM SUBTEST_SCORE_FACT;

SELECT OBJECTIVE_FACTID,ORG_NODEID,CUST_PROD_ID,ASSESSMENTID,STUDENT_BIO_ID,CONTENTID,SUBTESTID,
OBJECTIVEID,GENDERID,GRADEID,LEVELID,FORMID,ADMINID,NCR,OS,OPI,OPI_CUT,MEAN_IPI,PC,PP,SS,PL,INRC,
CONDCODE_ID,TEST_DATE,DATETIMESTAMP  FROM ISTEPPRODCOPY.OBJECTIVE_SCORE_FACT 
MINUS 
SELECT OBJECTIVE_FACTID,ORG_NODEID,CUST_PROD_ID,ASSESSMENTID,STUDENT_BIO_ID,CONTENTID,SUBTESTID,
OBJECTIVEID,GENDERID,GRADEID,LEVELID,FORMID,ADMINID,NCR,OS,OPI,OPI_CUT,MEAN_IPI,PC,PP,SS,PL,INRC,
CONDCODE_ID,TEST_DATE,DATETIMESTAMP FROM OBJECTIVE_SCORE_FACT;

SELECT * FROM ISTEPPRODCOPY.ITEM_SCORE_FACT MINUS SELECT * FROM ITEM_SCORE_FACT;
SELECT * FROM ISTEPPRODCOPY.GRADE_SELECTION_LOOKUP MINUS SELECT * FROM GRADE_SELECTION_LOOKUP;
SELECT * FROM ISTEPPRODCOPY.DEMOGRAPHIC MINUS SELECT * FROM DEMOGRAPHIC;
SELECT * FROM ISTEPPRODCOPY.DEMOGRAPHIC_VALUES MINUS SELECT * FROM DEMOGRAPHIC_VALUES;
SELECT * FROM ISTEPPRODCOPY.STU_SUBTEST_DEMO_VALUES MINUS SELECT * FROM STU_SUBTEST_DEMO_VALUES;
SELECT * FROM ISTEPPRODCOPY.STUDENT_PDF_FILES MINUS SELECT * FROM STUDENT_PDF_FILES;
SELECT * FROM ISTEPPRODCOPY.USERS_MAP MINUS SELECT * FROM USERS_MAP;
SELECT * FROM ISTEPPRODCOPY.ORG_LSTNODE_LINK MINUS SELECT * FROM ORG_LSTNODE_LINK;
SELECT * FROM ISTEPPRODCOPY.STUDENT_DEMO_VALUES MINUS SELECT * FROM STUDENT_DEMO_VALUES;
SELECT * FROM ISTEPPRODCOPY.ORG_PDF_FILES MINUS SELECT * FROM ORG_PDF_FILES;
SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE MINUS SELECT * FROM INVITATION_CODE;
SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE_CLAIM MINUS SELECT * FROM INVITATION_CODE_CLAIM;
SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE_LOOKUP MINUS SELECT * FROM INVITATION_CODE_LOOKUP;
SELECT * FROM ISTEPPRODCOPY.USC_LINK MINUS SELECT * FROM USC_LINK;
SELECT * FROM ISTEPPRODCOPY.USER_ROLE MINUS SELECT * FROM USER_ROLE;
SELECT * FROM ISTEPPRODCOPY.USER_SELECTION_LOOKUP MINUS SELECT * FROM USER_SELECTION_LOOKUP;
SELECT * FROM ISTEPPRODCOPY.PWD_HINT_ANSWERS MINUS SELECT * FROM PWD_HINT_ANSWERS;

SELECT COUNT(1) FROM ISTEPPRODCOPY.ARTICLE_CONTENT a,ARTICLE_CONTENT b
WHERE a.ARTICLE_CONTENT_ID=b.ARTICLE_CONTENT_ID
AND DBMS_LOB.COMPARE(a.ARTICLE_CONTENT, b.ARTICLE_CONTENT)<>0;

SELECT * FROM ISTEPPRODCOPY.ARTICLE_METADATA MINUS SELECT * FROM ARTICLE_METADATA;
SELECT * FROM ISTEPPRODCOPY.USER_ACTIVITY_HISTORY MINUS SELECT * FROM USER_ACTIVITY_HISTORY; <---- 106
SELECT * FROM ISTEPPRODCOPY.RESCORE_REQUEST_FORM MINUS SELECT * FROM RESCORE_REQUEST_FORM;
SELECT COUNT(1) FROM ISTEPPRODCOPY.JOB_TRACKING  A ,JOB_TRACKING B
WHERE A.JOB_ID = B.JOB_ID
AND DBMS_LOB.COMPARE(A.REQUEST_DETAILS,B.REQUEST_DETAILS) <>0;
SELECT * FROM ISTEPPRODCOPY.BIO_STUDENT_EXTRACT MINUS SELECT * FROM BIO_STUDENT_EXTRACT;
SELECT * FROM ISTEPPRODCOPY.PERF_MATRIX_FACT MINUS SELECT * FROM PERF_MATRIX_FACT;
SELECT * FROM ISTEPPRODCOPY.CUTSCOREIPI MINUS SELECT * FROM CUTSCOREIPI;
SELECT * FROM ISTEPPRODCOPY.CUTSCORESCALESCORE MINUS SELECT * FROM CUTSCORESCALESCORE;
SELECT * FROM ISTEPPRODCOPY.STATE_MEAN_IPI_SCORE MINUS SELECT * FROM STATE_MEAN_IPI_SCORE;
SELECT * FROM ISTEPPRODCOPY.DISAGGREGATION_CATEGORY MINUS SELECT * FROM DISAGGREGATION_CATEGORY;
SELECT * FROM ISTEPPRODCOPY.DISAGGREGATION_CATEGORY_TYPE MINUS SELECT * FROM DISAGGREGATION_CATEGORY_TYPE;
SELECT * FROM ISTEPPRODCOPY.ASFD_ORDERBY MINUS SELECT * FROM ASFD_ORDERBY;
SELECT * FROM ISTEPPRODCOPY.ASFD_FACT MINUS SELECT * FROM ASFD_FACT;
SELECT * FROM ISTEPPRODCOPY.STFD_FACT MINUS SELECT * FROM STFD_FACT;
SELECT * FROM ISTEPPRODCOPY.DISA_FACT MINUS SELECT * FROM DISA_FACT;
SELECT * FROM ISTEPPRODCOPY.SPPR_FACT MINUS SELECT * FROM SPPR_FACT;
SELECT * FROM ISTEPPRODCOPY.SPPR_FACT MINUS SELECT * FROM SPPR_FACT;
SELECT * FROM ISTEPPRODCOPY.ACAD_STD_SUMM_FACT MINUS SELECT * FROM ACAD_STD_SUMM_FACT;
SELECT * FROM ISTEPPRODCOPY.UDTR_ROSTER_FACT MINUS SELECT * FROM UDTR_ROSTER_FACT;
SELECT * FROM ISTEPPRODCOPY.UDTR_SUMM_FACT MINUS SELECT * FROM UDTR_SUMM_FACT;
SELECT * FROM ISTEPPRODCOPY.CLASS_SUMM_FACT MINUS SELECT * FROM CLASS_SUMM_FACT;
SELECT * FROM ISTEPPRODCOPY.SUMT_FACT MINUS SELECT * FROM SUMT_FACT;
SELECT * FROM ISTEPPRODCOPY.MEDIA_FACT MINUS SELECT * FROM MEDIA_FACT;
SELECT * FROM ISTEPPRODCOPY.RESULTS_GRT_FACT MINUS SELECT * FROM RESULTS_GRT_FACT;
SELECT * FROM ISTEPPRODCOPY.USABILITY_LOG MINUS SELECT * FROM USABILITY_LOG;
SELECT * FROM ISTEPPRODCOPY.STU_DEMO_VAL MINUS SELECT * FROM STU_DEMO_VAL;
SELECT * FROM ISTEPPRODCOPY.STU_SUB_DETAILS MINUS SELECT * FROM STU_SUB_DETAILS;
SELECT * FROM ISTEPPRODCOPY.PERF_LOG MINUS SELECT * FROM PERF_LOG;
SELECT * FROM ISTEPPRODCOPY.ORGUSER_DETAILS MINUS SELECT * FROM ORGUSER_DETAILS;

SELECT SEQ_NO,COLUMN_NAME,START_POSITION,END_POSITION,LENGTH,CATEGORY,CATEGORY_TYPE,
CATEGORY_VALUE,DATA_EXTRACT_BLOCK,REPLACE_FLAG,REPLACE_VALUE,IS_BIO_UPDATE,DESCRIPTION,ACTIVATION_STATUS,
DATETIMESTAMP,PRODUCT_CODE FROM ISTEPPRODCOPY.STG_DATA_LAYOUT_CONFIG 
MINUS 
SELECT SEQ_NO,COLUMN_NAME,START_POSITION,END_POSITION,LENGTH,CATEGORY,CATEGORY_TYPE,
CATEGORY_VALUE,DATA_EXTRACT_BLOCK,REPLACE_FLAG,REPLACE_VALUE,IS_BIO_UPDATE,DESCRIPTION,ACTIVATION_STATUS,
DATETIMESTAMP,PRODUCT_CODE FROM STG_DATA_LAYOUT_CONFIG;

SELECT * FROM ISTEPPRODCOPY.STG_ETL_JOBMASTER MINUS SELECT * FROM STG_ETL_JOBMASTER;
SELECT * FROM ISTEPPRODCOPY.STG_PROCESS_STATUS MINUS SELECT * FROM STG_PROCESS_STATUS;

------REVERSE------

SELECT * FROM ORG_NODE_DIM MINUS SELECT * FROM ISTEPPRODCOPY.ORG_NODE_DIM;
SELECT * FROM ORG_PRODUCT_LINK MINUS SELECT * FROM ISTEPPRODCOPY.ORG_PRODUCT_LINK;
SELECT * FROM ORG_TEST_PROGRAM_LINK MINUS SELECT * FROM ISTEPPRODCOPY.ORG_TEST_PROGRAM_LINK;
SELECT * FROM USERS MINUS SELECT * FROM ISTEPPRODCOPY.USERS;
SELECT * FROM ORG_USERS MINUS SELECT * FROM ISTEPPRODCOPY.ORG_USERS;
SELECT * FROM EDU_CENTER_DETAILS MINUS SELECT * FROM ISTEPPRODCOPY.EDU_CENTER_DETAILS;
SELECT * FROM EDU_CENTER_USER_LINK MINUS SELECT * FROM ISTEPPRODCOPY.EDU_CENTER_USER_LINK; <---
SELECT * FROM STUDENT_BIO_DIM MINUS SELECT * FROM ISTEPPRODCOPY.STUDENT_BIO_DIM;
SELECT * FROM SUBTEST_SCORE_FACT MINUS SELECT * FROM ISTEPPRODCOPY.SUBTEST_SCORE_FACT;

SELECT OBJECTIVE_FACTID,ORG_NODEID,CUST_PROD_ID,ASSESSMENTID,STUDENT_BIO_ID,CONTENTID,SUBTESTID,
OBJECTIVEID,GENDERID,GRADEID,LEVELID,FORMID,ADMINID,NCR,OS,OPI,OPI_CUT,MEAN_IPI,PC,PP,SS,PL,INRC,
CONDCODE_ID,TEST_DATE,DATETIMESTAMP  FROM OBJECTIVE_SCORE_FACT 
MINUS 
SELECT OBJECTIVE_FACTID,ORG_NODEID,CUST_PROD_ID,ASSESSMENTID,STUDENT_BIO_ID,CONTENTID,SUBTESTID,
OBJECTIVEID,GENDERID,GRADEID,LEVELID,FORMID,ADMINID,NCR,OS,OPI,OPI_CUT,MEAN_IPI,PC,PP,SS,PL,INRC,
CONDCODE_ID,TEST_DATE,DATETIMESTAMP FROM ISTEPPRODCOPY.OBJECTIVE_SCORE_FACT;

SELECT * FROM ITEM_SCORE_FACT MINUS SELECT * FROM ISTEPPRODCOPY.ITEM_SCORE_FACT;
SELECT * FROM GRADE_SELECTION_LOOKUP MINUS SELECT * FROM ISTEPPRODCOPY.GRADE_SELECTION_LOOKUP;
SELECT * FROM DEMOGRAPHIC MINUS SELECT * FROM ISTEPPRODCOPY.DEMOGRAPHIC;
SELECT * FROM DEMOGRAPHIC_VALUES MINUS SELECT * FROM ISTEPPRODCOPY.DEMOGRAPHIC_VALUES;
SELECT * FROM STU_SUBTEST_DEMO_VALUES MINUS SELECT * FROM ISTEPPRODCOPY.STU_SUBTEST_DEMO_VALUES;
SELECT * FROM STUDENT_PDF_FILES MINUS SELECT * FROM ISTEPPRODCOPY.STUDENT_PDF_FILES;
SELECT * FROM USERS_MAP MINUS SELECT * FROM ISTEPPRODCOPY.USERS_MAP;
SELECT * FROM ORG_LSTNODE_LINK MINUS SELECT * FROM ISTEPPRODCOPY.ORG_LSTNODE_LINK;
SELECT * FROM STUDENT_DEMO_VALUES MINUS SELECT * FROM ISTEPPRODCOPY.STUDENT_DEMO_VALUES;
SELECT * FROM ORG_PDF_FILES MINUS SELECT * FROM ISTEPPRODCOPY.ORG_PDF_FILES;
SELECT * FROM INVITATION_CODE MINUS SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE;
SELECT * FROM INVITATION_CODE_CLAIM MINUS SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE_CLAIM;
SELECT * FROM INVITATION_CODE_LOOKUP MINUS SELECT * FROM ISTEPPRODCOPY.INVITATION_CODE_LOOKUP;
SELECT * FROM USC_LINK MINUS SELECT * FROM ISTEPPRODCOPY.USC_LINK;
SELECT * FROM USER_ROLE MINUS SELECT * FROM ISTEPPRODCOPY.USER_ROLE;
SELECT * FROM USER_SELECTION_LOOKUP MINUS SELECT * FROM ISTEPPRODCOPY.USER_SELECTION_LOOKUP;
SELECT * FROM PWD_HINT_ANSWERS MINUS SELECT * FROM ISTEPPRODCOPY.PWD_HINT_ANSWERS;

SELECT COUNT(1) FROM ISTEPPRODCOPY.ARTICLE_CONTENT a,ARTICLE_CONTENT b
WHERE a.ARTICLE_CONTENT_ID=b.ARTICLE_CONTENT_ID
AND DBMS_LOB.COMPARE(a.ARTICLE_CONTENT, b.ARTICLE_CONTENT)<>0;

SELECT * FROM ARTICLE_METADATA MINUS SELECT * FROM ISTEPPRODCOPY.ARTICLE_METADATA;
SELECT * FROM USER_ACTIVITY_HISTORY MINUS SELECT * FROM ISTEPPRODCOPY.USER_ACTIVITY_HISTORY;
SELECT * FROM RESCORE_REQUEST_FORM MINUS SELECT * FROM ISTEPPRODCOPY.RESCORE_REQUEST_FORM;
SELECT COUNT(1) FROM ISTEPPRODCOPY.JOB_TRACKING  A ,JOB_TRACKING B
WHERE A.JOB_ID = B.JOB_ID
AND DBMS_LOB.COMPARE(A.REQUEST_DETAILS,B.REQUEST_DETAILS) <>0;
SELECT * FROM BIO_STUDENT_EXTRACT MINUS SELECT * FROM ISTEPPRODCOPY.BIO_STUDENT_EXTRACT;
SELECT * FROM PERF_MATRIX_FACT MINUS SELECT * FROM ISTEPPRODCOPY.PERF_MATRIX_FACT;
SELECT * FROM CUTSCOREIPI MINUS SELECT * FROM ISTEPPRODCOPY.CUTSCOREIPI;
SELECT * FROM CUTSCORESCALESCORE MINUS SELECT * FROM ISTEPPRODCOPY.CUTSCORESCALESCORE;
SELECT * FROM STATE_MEAN_IPI_SCORE MINUS SELECT * FROM ISTEPPRODCOPY.STATE_MEAN_IPI_SCORE;
SELECT * FROM DISAGGREGATION_CATEGORY MINUS SELECT * FROM ISTEPPRODCOPY.DISAGGREGATION_CATEGORY;
SELECT * FROM DISAGGREGATION_CATEGORY_TYPE MINUS SELECT * FROM ISTEPPRODCOPY.DISAGGREGATION_CATEGORY_TYPE;
SELECT * FROM ASFD_ORDERBY MINUS SELECT * FROM ISTEPPRODCOPY.ASFD_ORDERBY;
SELECT * FROM ASFD_FACT MINUS SELECT * FROM ISTEPPRODCOPY.ASFD_FACT;
SELECT * FROM STFD_FACT MINUS SELECT * FROM ISTEPPRODCOPY.STFD_FACT;
SELECT * FROM DISA_FACT MINUS SELECT * FROM ISTEPPRODCOPY.DISA_FACT;
SELECT * FROM SPPR_FACT MINUS SELECT * FROM ISTEPPRODCOPY.SPPR_FACT;
SELECT * FROM SPPR_FACT MINUS SELECT * FROM ISTEPPRODCOPY.SPPR_FACT;
SELECT * FROM ACAD_STD_SUMM_FACT MINUS SELECT * FROM ISTEPPRODCOPY.ACAD_STD_SUMM_FACT;
SELECT * FROM UDTR_ROSTER_FACT MINUS SELECT * FROM ISTEPPRODCOPY.UDTR_ROSTER_FACT;
SELECT * FROM UDTR_SUMM_FACT MINUS SELECT * FROM ISTEPPRODCOPY.UDTR_SUMM_FACT;
SELECT * FROM CLASS_SUMM_FACT MINUS SELECT * FROM ISTEPPRODCOPY.CLASS_SUMM_FACT;
SELECT * FROM SUMT_FACT MINUS SELECT * FROM ISTEPPRODCOPY.SUMT_FACT;
SELECT * FROM MEDIA_FACT MINUS SELECT * FROM ISTEPPRODCOPY.MEDIA_FACT;
SELECT * FROM RESULTS_GRT_FACT MINUS SELECT * FROM ISTEPPRODCOPY.RESULTS_GRT_FACT;
SELECT * FROM USABILITY_LOG MINUS SELECT * FROM ISTEPPRODCOPY.USABILITY_LOG;
SELECT * FROM STU_DEMO_VAL MINUS SELECT * FROM ISTEPPRODCOPY.STU_DEMO_VAL;
SELECT * FROM STU_SUB_DETAILS MINUS SELECT * FROM ISTEPPRODCOPY.STU_SUB_DETAILS;
SELECT * FROM PERF_LOG MINUS SELECT * FROM ISTEPPRODCOPY.PERF_LOG;
SELECT * FROM ORGUSER_DETAILS MINUS SELECT * FROM ISTEPPRODCOPY.ORGUSER_DETAILS;

SELECT SEQ_NO,COLUMN_NAME,START_POSITION,END_POSITION,LENGTH,CATEGORY,CATEGORY_TYPE,
CATEGORY_VALUE,DATA_EXTRACT_BLOCK,REPLACE_FLAG,REPLACE_VALUE,IS_BIO_UPDATE,DESCRIPTION,ACTIVATION_STATUS,
DATETIMESTAMP,PRODUCT_CODE FROM STG_DATA_LAYOUT_CONFIG
MINUS
SELECT SEQ_NO,COLUMN_NAME,START_POSITION,END_POSITION,LENGTH,CATEGORY,CATEGORY_TYPE,
CATEGORY_VALUE,DATA_EXTRACT_BLOCK,REPLACE_FLAG,REPLACE_VALUE,IS_BIO_UPDATE,DESCRIPTION,ACTIVATION_STATUS,
DATETIMESTAMP,PRODUCT_CODE FROM ISTEPPRODCOPY.STG_DATA_LAYOUT_CONFIG; 

SELECT * FROM STG_ETL_JOBMASTER MINUS SELECT * FROM ISTEPPRODCOPY.STG_ETL_JOBMASTER;
SELECT * FROM STG_PROCESS_STATUS MINUS SELECT * FROM ISTEPPRODCOPY.STG_PROCESS_STATUS;





















