prompt Importing table ETL_JOBMASTER_CONFIG...
set feedback off
set define off
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_ORG_NODE_DIM_LOAD', 'S_STG_ORG_NODE_DIM_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:04', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:04', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_ORG_NODE_DIM_BKP_LOAD', 'S_ORG_NODE_DIM_BKP_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:04', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:04', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ORG_NODE_LOAD', 'S_OPR_ORG_NODE_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:05', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:05', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_WI_GRT_DATA_LOAD', 'S_STG_WI_GRT_DATA_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('25-05-2016 01:56:14', 'dd-mm-yyyy hh24:mi:ss'), to_date('25-05-2016 01:56:14', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_WI_GRT_DATA_VALIDATE', 'S_STG_WI_GRT_DATA_VALIDATE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('25-05-2016 09:11:55', 'dd-mm-yyyy hh24:mi:ss'), to_date('25-05-2016 09:11:55', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ORG_PRODUCT_LINK_LOAD', 'S_OPR_ORG_PRODUCT_LINK_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:05', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:05', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_ORG_LSTNODE_LINK_LOAD', 'S_STG_ORG_LSTNODE_LINK_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:06', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:06', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ORG_LSTNODE_LINK_LOAD', 'S_OPR_ORG_LSTNODE_LINK_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 04:29:06', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 04:29:06', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_CHECK_PRODUCT', 'S_CHECK_PRODUCT', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 08:12:30', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 08:12:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_ERROR_PRODUCT_EMAIL', 'S_ERROR_PRODUCT_EMAIL', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 08:12:30', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 08:12:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_BIO_DETAILS_LOAD', 'S_STG_STD_BIO_DETAILS_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 08:12:31', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 08:12:31', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_BIO_LOAD', 'S_PROCESS_STATUS_STG_BIO_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 11:30:10', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 11:30:10', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_DEMO_DETAILS_LOAD', 'S_STG_STD_DEMO_DETAILS_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 11:30:11', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 11:30:11', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_DEMO_LOAD', 'S_PROCESS_STATUS_STG_DEMO_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('26-05-2016 11:30:11', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-05-2016 11:30:11', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_SUBTEST_DETAILS_LOAD', 'S_STG_STD_SUBTEST_DETAILS_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('27-05-2016 04:13:32', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-05-2016 04:13:32', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_SUBTEST_LOAD', 'S_PROCESS_STATUS_STG_SUBTEST_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('27-05-2016 04:13:33', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-05-2016 04:13:33', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_OBJECTIVE_DETAILS_LOAD', 'S_STG_STD_OBJECTIVE_DETAILS_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('30-05-2016 05:41:24', 'dd-mm-yyyy hh24:mi:ss'), to_date('30-05-2016 05:41:24', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_OBJECTIVE_LOAD', 'S_PROCESS_STATUS_STG_OBJECTIVE_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('30-05-2016 05:41:24', 'dd-mm-yyyy hh24:mi:ss'), to_date('30-05-2016 05:41:24', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_ITEM_RESPONSE_DETAILS_LOAD', 'S_STG_ITEM_RESPONSE_DETAILS_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('30-05-2016 09:07:39', 'dd-mm-yyyy hh24:mi:ss'), to_date('30-05-2016 09:07:39', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_ITEM_LOAD', 'S_PROCESS_STATUS_STG_ITEM_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('30-05-2016 09:07:40', 'dd-mm-yyyy hh24:mi:ss'), to_date('30-05-2016 09:07:40', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STUDENT_DEMO_VALUES_LOAD', 'S_OPR_STUDENT_DEMO_VALUES_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 04:47:48', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 04:47:48', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_STUDENT_DEMO_LOAD', 'S_PROCESS_STATUS_OPR_STUDENT_DEMO_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 04:47:48', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 04:47:48', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STU_SUBTEST_DEMO_VALUES_LOAD', 'S_OPR_STU_SUBTEST_DEMO_VALUES_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 06:40:56', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 06:40:56', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_SUBTEST_DEMO_LOAD', 'S_PROCESS_STATUS_OPR_SUBTEST_DEMO_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 06:40:56', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 06:40:56', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_SUBTEST_SCORE_FACT_LOAD', 'S_OPR_SUBTEST_SCORE_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:54', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_SUBTEST_FACT_LOAD', 'S_PROCESS_STATUS_OPR_SUBTEST_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:55', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:55', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_OBJECTIVE_SCORE_FACT_LOAD', 'S_OPR_OBJECTIVE_SCORE_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:55', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:55', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_OBJECTIVE_FACT_LOAD', 'S_PROCESS_STATUS_OPR_OBJECTIVE_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:56', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:56', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ITEM_SCORE_FACT_LOAD', 'S_OPR_ITEM_SCORE_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:56', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:56', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_ITEM_FACT_LOAD', 'S_PROCESS_STATUS_OPR_ITEM_FACT_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('01-06-2016 08:30:57', 'dd-mm-yyyy hh24:mi:ss'), to_date('01-06-2016 08:30:57', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STUDENT_BIO_DIM_LOAD', 'S_OPR_STUDENT_BIO_DIM_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 03:40:49', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 03:40:49', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_BIO_LOAD', 'S_PROCESS_STATUS_OPR_BIO_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('31-05-2016 03:40:49', 'dd-mm-yyyy hh24:mi:ss'), to_date('31-05-2016 03:40:49', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_ORG_LOAD', 'S_PROCESS_STATUS_STG_ORG_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('08-06-2016 09:21:51', 'dd-mm-yyyy hh24:mi:ss'), to_date('08-06-2016 09:21:51', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_ORG_LOAD', 'S_PROCESS_STATUS_OPR_ORG_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('08-06-2016 09:24:00', 'dd-mm-yyyy hh24:mi:ss'), to_date('08-06-2016 09:24:00', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_GRADE_SELECTION_LOOKUP_LOAD', 'S_OPR_GRADE_SELECTION_LOOKUP_LOAD', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('10-06-2016 08:28:52', 'dd-mm-yyyy hh24:mi:ss'), to_date('10-06-2016 08:28:52', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STUDENT_DEMO_DELETE', 'S_OPR_STUDENT_DEMO_DELETE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('24-06-2016 07:22:12', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-06-2016 07:22:12', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_SUBTEST_DEMO_DELETE', 'S_OPR_SUBTEST_DEMO_DELETE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('24-06-2016 07:22:12', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-06-2016 07:22:12', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_SUBTEST_FACT_DELETE', 'S_OPR_SUBTEST_FACT_DELETE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('24-06-2016 07:22:13', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-06-2016 07:22:13', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_OBJECTIVE_FACT_DELETE', 'S_OPR_OBJECTIVE_FACT_DELETE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('24-06-2016 07:22:13', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-06-2016 07:22:13', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ITEM_FACT_DELETE', 'S_OPR_ITEM_FACT_DELETE', 'WKF_WISCONSIN_PRISM_GRT_LOAD', null, null, null, 4, to_date('24-06-2016 07:22:14', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-06-2016 07:22:14', 'dd-mm-yyyy hh24:mi:ss'));

prompt Done.
