--DELETE FROM ITEMSET_DIM WHERE PROJECTID = 5; 

insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned MC- ELA', '1001', null, 1, null, 'MC1', null, null, 2066, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned Autoscored- ELA', '1002', null, 2, null, 'AS1', null, null, 2066, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned Text-Dependent Analysis - ELA', '1003', null, 3, null, 'TD1', null, null, 2066, null, null, null, 4, SYSDATE);
--
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned MC- Math', '1004', null, 1, null, 'MC1', null, null, 2067, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned Autoscored- Math', '1005', null, 2, null, 'AS1', null, null, 2067, null, null, null, 4, SYSDATE);
--
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned MC- Science', '1006', null, 1, null, 'MC1', null, null, 2068, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned Autoscored- Science', '1007', null, 2, null, 'AS1', null, null, 2068, null, null, null, 4, SYSDATE);
--
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Points Earned MC- Social Study', '1008', null, 1, null, 'MC1', null, null, 2069, null, null, null, 4, SYSDATE);
---
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to MC- ELA', '1009', null, 4, null, 'MC2', null, null, 2066, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to Autoscored- ELA', '1010', null, 5, null, 'AS2', null, null, 2066, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to Text-Dependent Analysis - ELA', '1011', null, 6, null, 'TD2', null, null, 2066, null, null, null, 4, SYSDATE);

---
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to MC - Math', '1012', null, 3, null, 'MC2', null, null, 2067, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to Autoscored - Math', '1013', null, 4, null, 'AS2', null, null, 2067, null, null, null, 4, SYSDATE);
--
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to MC - Science', '1014', null, 3, null, 'MC2', null, null, 2068, null, null, null, 4, SYSDATE);
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to Autoscored - Science', '1015', null, 4, null, 'AS2', null, null, 2068, null, null, null, 4, SYSDATE);
--
insert into ITEMSET_DIM (ITEMSETID, ITEM_NAME, ITEM_CODE, SESSION_ID, ITEM_SEQ, POINT_POSSIBLE, ITEM_TYPE, PDF_FILENAME, SUBT_OBJ_MAPID, SUBTESTID, ITEM_NUMBER, ITEM_PART, MODEULEID, PROJECTID, DATETIMESTAMP)
values (SEQ_ITEMSETID.NEXTVAL, 'Answers to MC - Social Study', '1016', null, 2, null, 'MC2', null, null, 2069, null, null, null, 4, SYSDATE);
commit;