--PROJECT_DIM
INSERT INTO PROJECT_DIM (PROJECTID, PROJECT_NAME, CREATED_DATE_TIME, UPDATED_DATE_TIME) VALUES (3, 'Missouri', SYSDATE, SYSDATE);
COMMIT;

---CUSTOMER_INFO
INSERT INTO CUSTOMER_INFO
SELECT  (SELECT MAX(CUSTOMERID) FROM CUSTOMER_INFO)+ROWNUM AS CUSTOMERID,
       'Missouri  MAP – Test' AS CUSTOMER_NAME,
       'Y' AS DISPLAY_TP_SELECTION,
       '/INORSREPORTS/MISSOURI' AS FILE_LOCATION,
       NULL AS SUPPORT_EMAIL,
       NULL AS SEND_LOGIN_PDF,
       'MO' AS CUSTOMER_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;      
--SELECT * FROM CUSTOMER_INFO;

--ADMIN_DIM;
INSERT INTO ADMIN_DIM
SELECT (SELECT MAX(ADMINID)+1 FROM ADMIN_DIM) AS ADMINID,
       'Missouri 2015' AS ADMIN_NAME,
       'SPRING/SUMMER' AS ADMIN_SEASON,
        2015 AS ADMIN_YEAR,
        'Y' AS IS_CURRENT_ADMIN,
        2015 AS FILE_LOCATION,
        1 AS ADMIN_SEQ,
        (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
        SYSDATE AS DATETIMESTAMP
 FROM DUAL;       
COMMIT;
--SELECT * FROM ADMIN_DIM;


-- PRODUCT;
INSERT INTO PRODUCT
SELECT 2001 AS PRODUCTID,
       'MO MAP GLA Summative 2015' AS PRODUCT_NAME,
       'OL' AS PRODUCT_TYPE,
       1 AS PRODUCT_SEQ,
       'MAPSMTSPR2015' AS PRODUCT_CODE,
       'N' AS IS_IC_REQUIRED,
       'N' AS IS_EDITABLE,
       '/MAPSMTSPR2015' AS FILE_LOCATION,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;


--CUST_PRODUCT_LINK
INSERT INTO CUST_PRODUCT_LINK
SELECT (SELECT MAX(CUST_PROD_ID) FROM CUST_PRODUCT_LINK)+ ROWNUM AS CUST_PROD_ID,
       CI.CUSTOMERID,       
       PDT.PRODUCTID,
       ADM.ADMINID,
       'AC' AS ACTIVATION_STATUS,
       SYSDATE AS DATETIMESTAMP
FROM CUSTOMER_INFO CI,
     PRODUCT PDT,
     ADMIN_DIM ADM,
     PROJECT_DIM PJT
WHERE PJT.PROJECT_NAME='Missouri'
  AND PJT.PROJECTID = PDT.PROJECTID
  AND CI.PROJECTID = PDT.PROJECTID 
  AND ADM.PROJECTID = PDT.PROJECTID ;
  COMMIT;
--SELECT * FROM CUST_PRODUCT_LINK;  
 
--ASSESSMENT_DIM;
INSERT INTO ASSESSMENT_DIM
SELECT (SELECT MAX(ASSESSMENTID) FROM ASSESSMENT_DIM)+ROWNUM AS ASSESSMENTID,
       'MO MAP GLA Summative 2015' AS ASSESSMENT_NAME,
       'AC' AS ASSESSMENT_TYPE,
       'MAPSMTSPR2015' AS ASSESSMENT_CODE,
       PDT.PRODUCTID,
       SYSDATE AS DATETIMESTAMP
FROM PRODUCT PDT,
     PROJECT_DIM PJT
WHERE PJT.PROJECT_NAME='Missouri'
  AND PJT.PROJECTID = PDT.PROJECTID;
 COMMIT;
--SELECT * FROM ASSESSMENT_DIM; 


--TEST_PROGRAM
INSERT INTO TEST_PROGRAM
SELECT (SELECT MAX(TP_ID) FROM TEST_PROGRAM)+ ROWNUM AS TP_ID,
       'MAPSMTSPR2015' AS TP_CODE,
       'MO SUMT Spring 2015' AS TP_NAME,
       'PUBLIC' AS TP_TYPE,
       3 AS NUM_LEVELS,
       'OL' AS TP_MODE,
       CI.CUSTOMERID,
       ADM.ADMINID,
       'AC' AS ACTIVATION_STATUS,
       SYSDATE AS DATETIMESTAMP
FROM CUSTOMER_INFO CI,
     ADMIN_DIM ADM,
     PROJECT_DIM PJT
WHERE PJT.PROJECT_NAME='Missouri'
  AND CI.PROJECTID = PJT.PROJECTID 
  AND ADM.PROJECTID = PJT.PROJECTID ;
COMMIT;
--SELECT * FROM TEST_PROGRAM;

--ORG_TP_STRUCTURE
INSERT INTO ORG_TP_STRUCTURE
SELECT TP.TP_ID,
       LVL.ORG_LEVEL,
       LVL.ORG_LABEL,
       SYSDATE AS DATETIMESTAMP
FROM CUSTOMER_INFO CI,
     ADMIN_DIM ADM,
     PROJECT_DIM PJT,
     TEST_PROGRAM TP,
     (SELECT 1 AS ORG_LEVEL , 'State' AS ORG_LABEL FROM DUAL
     UNION ALL
     SELECT 2 AS ORG_LEVEL , 'District' AS ORG_LABEL FROM DUAL
     UNION ALL
     SELECT 3 AS ORG_LEVEL , 'School' AS ORG_LABEL FROM DUAL) LVL
WHERE PJT.PROJECT_NAME='Missouri'
  AND CI.PROJECTID = PJT.PROJECTID 
  AND ADM.PROJECTID = PJT.PROJECTID
  AND TP.CUSTOMERID=CI.CUSTOMERID
  AND TP.ADMINID = ADM.ADMINID;
   COMMIT;
--SELECT * FROM ORG_TP_STRUCTURE;

--CONTENT_DIM
INSERT INTO CONTENT_DIM
SELECT (SELECT MAX(CONTENTID) FROM CONTENT_DIM)+ ROWNUM AS CONTENTID,
       LVL.NAME AS CONTENT_NAME,
       LVL.SEQ AS CONTENT_SEQ,
       ASES.ASSESSMENTID,
       SYSDATE AS DATETIMESTAMP
FROM PRODUCT PDT,
     PROJECT_DIM PJT,
     ASSESSMENT_DIM ASES,
    (SELECT 1 AS SEQ , 'English Language Arts' AS NAME FROM DUAL
     UNION ALL
     SELECT 2 AS SEQ , 'Mathematics' AS NAME FROM DUAL
     UNION ALL
     SELECT 3 AS SEQ , 'Science' AS NAME FROM DUAL) LVL
WHERE PJT.PROJECT_NAME='Missouri'
  AND PJT.PROJECTID = PDT.PROJECTID
  AND PDT.PRODUCTID =ASES.PRODUCTID ;
 COMMIT;
--SELECT * FROM CONTENT_DIM;

--SUBTEST_DIM
INSERT INTO SUBTEST_DIM
SELECT (SELECT MAX(SUBTESTID) FROM SUBTEST_DIM )+ROWNUM AS SUBTESTID,
		A.SUBTEST_NAME,
		A.SUBTEST_SEQ,
		A.SUBTEST_CODE,
		A.SUBTEST_TYPE,
		A.CONTENTID,
		A.CANDIDATE_SUB_SEQ,
		A.DATETIMESTAMP
FROM(SELECT CONT.CONTENT_NAME AS SUBTEST_NAME,
			CONT.CONTENT_SEQ AS SUBTEST_SEQ,
			'0'||CONT.CONTENT_SEQ AS SUBTEST_CODE,
			'S' AS SUBTEST_TYPE,
			CONT.CONTENTID,
			NULL AS CANDIDATE_SUB_SEQ,
			SYSDATE AS DATETIMESTAMP
			FROM PRODUCT PDT,
				 PROJECT_DIM PJT,
				 ASSESSMENT_DIM ASES,
				 CONTENT_DIM CONT
			WHERE PJT.PROJECT_NAME='Missouri'
			  AND PJT.PROJECTID = PDT.PROJECTID
			  AND PDT.PRODUCTID =ASES.PRODUCTID 
			  AND CONT.ASSESSMENTID = ASES.ASSESSMENTID
			  ORDER BY CONT.CONTENT_NAME ,
					   CONT.CONTENT_SEQ ,
					   '0'||CONT.CONTENT_SEQ,
					   'S' AS SUBTEST_TYPE,
					   CONT.CONTENTID)A;
       
 COMMIT;
--SELECT * FROM SUBTEST_DIM ;


--OBJECTIVE_DIM
ALTER TABLE OBJECTIVE_DIM MODIFY OBJECTIVE_NAME VARCHAR2(50);
ALTER TABLE OBJECTIVE_DIM MODIFY OBJECTIVE_DESC VARCHAR2(300);
INSERT INTO OBJECTIVE_DIM
SELECT (SELECT MAX(OBJECTIVEID) FROM OBJECTIVE_DIM)+ROWNUM AS OBJECTIVEID,
       META_OBJ.NME AS OBJECTIVE_NAME,
       (SELECT MAX(OBJECTIVE_SEQ) FROM OBJECTIVE_DIM)+ROWNUM AS OBJECTIVE_SEQ,
       META_OBJ.TYP AS OBJECTIVE_TYPE,
       META_OBJ.CODE AS OBJECTIVE_CODE,
       META_OBJ.DESCRIPTION AS OBJECTIVE_DESC,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM (select 'Reading' AS NME,          '1' AS CODE,  'C' AS TYP,     '01' AS SUBTEST_CODE,  'Reading' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Writing' AS NME,          '2' AS CODE,  'C' AS TYP,  '01' AS SUBTEST_CODE,  'Writing' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Listening' AS NME,          '3' AS CODE,  'C' AS TYP,  '01' AS SUBTEST_CODE,  'Listening' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Research' AS NME,          '4' AS CODE,  'C' AS TYP,  '01' AS SUBTEST_CODE,  'Research' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Concepts and Procedures' AS NME,      '1' AS CODE,  'C' AS TYP,  '02' AS SUBTEST_CODE,  'Concepts and Procedures' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Prob. Solving & Modeling & Data Anal.' AS NME,    '2' AS CODE,  'C' AS TYP,  '02' AS SUBTEST_CODE,  'Problem Solving and Modeling and Data Analysis' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Communicating Reasoning' AS NME,      '3' AS CODE,  'C' AS TYP,  '02' AS SUBTEST_CODE,  'Communicating Reasoning' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Matter and Energy' AS NME,        '1' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Properties and Principles of Matter and Energy' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Force and Motion' AS NME,        '2' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Properties and Principles of Force and Motion' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Living Organisms' AS NME,        '3' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Characteristics and Interactions of Living Organisms' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Ecosystems' AS NME,          '4' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Changes in Ecosystems and Interactions of Organisms with their Environments' AS DESCRIPTION FROM DUAL
      UNION ALL
      select q'[Earth's Systems]' AS NME,        '5' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  q'[Processes and Interactions of the Earth's Systems (Geosphere, Atmosphere and Hydroshpere)]' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'The Universe' AS NME,          '6' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Composition and Structure of the Universe and the Motion of the Objects Within It' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Scientific Inquiry' AS NME,        '7' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Scientific Inquiry' AS DESCRIPTION FROM DUAL
      UNION ALL
      select 'Impact of Sci., Tech. and Human Activity' AS NME,  '8' AS CODE,  'C' AS TYP,  '03' AS SUBTEST_CODE,  'Impact of Science, Technology and Human Activity' AS DESCRIPTION FROM DUAL
      )META_OBJ;

COMMIT;

UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can read closely and analytically to comprehend a range of increasingly complex literary and informational texts.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Reading');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can produce effective and well-grounded writing for a range of purposes and audiences.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Writing');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can employ effective speaking and listening skills for a range of purposes and audiences.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Listening');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can engage in research and inquiry to investigate topics, and to analyze, integrate, and present information.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Research');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can explain and apply mathematical concepts and carry out mathematical procedures with precision and fluency.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Concepts and Procedures');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can solve a range of complex, well-posed problems in pure and applied mathematics, making productive use of knowledge and problem-solving strategies. Students can analyze complex, real-world scenarios and can construct and use mathematical models to interpret and solve problems.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Prob. Solving & Modeling & Data Anal.');
UPDATE OBJECTIVE_DIM SET OBJECTIVE_DESC = q'[Students can clearly and precisely construct viable arguments to support their own reasoning and to critique the reasoning of others.]'
WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME = 'Missouri')
AND TRIM(OBJECTIVE_NAME) = TRIM('Communicating Reasoning');
--SELECT * FROM OBJECTIVE_DIM;      
 
--GRADE_DIM;
INSERT INTO GRADE_DIM
SELECT (SELECT MAX(GRADEID) FROM GRADE_DIM)+ ROWNUM AS GRADEID,
       'Grade '||TO_CHAR(LEVEL+2) AS GRADE_NAME,
       LEVEL AS GRADE_SEQ,
       '0'||TO_CHAR(LEVEL+2) AS GRADE_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL CONNECT BY LEVEL <= 6;
COMMIT;
--SELECT * FROM GRADE_DIM;

--LEVEL_DIM;
INSERT INTO LEVEL_DIM
     SELECT (SELECT MAX(LEVELID) FROM LEVEL_DIM)+ROWNUM AS LEVELID,
       'Level '||LEVEL AS LEVEL_NAME,
       'MO' AS LEVEL_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
       FROM DUAL CONNECT BY LEVEL<=6;
      
       COMMIT;
--SELECT * FROM LEVEL_DIM; 

--FORM_DIM
INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'A' AS FORM_NAME,
       'A' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;
/*INSERT INTO FORM_DIM
SELECT (SELECT MAX(FORMID) FROM FORM_DIM) + ROWNUM AS FORMID,
       'Z' AS FORM_NAME,
       'Z' AS FORM_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM DUAL;       
COMMIT;*/
--SELECT * FROM FORM_DIM;


--GENDER_DIM
INSERT INTO GENDER_DIM
SELECT (SELECT MAX(GENDERID) FROM GENDER_DIM)+ROWNUM AS GENDERID,
       GND.GENDER_NAME,
       GND.GENDER_CODE,
       (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri') AS PROJECTID,
       SYSDATE AS DATETIMESTAMP
FROM (SELECT 'Male' AS GENDER_NAME , 'M' AS GENDER_CODE FROM dual
     UNION
     SELECT 'Female' AS GENDER_NAME , 'F' AS GENDER_CODE FROM dual)GND;
 
COMMIT; 

INSERT INTO GENDER_DIM 
VALUES 
(
  (SELECT MAX(GENDERID)+1 FROM GENDER_DIM), 
  'Unknown', 
  'U', 
  (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri'), 
  SYSDATE
  );  
COMMIT;    
--SELECT * FROM GENDER_DIM;

--LEVEL_MAP
INSERT INTO LEVEL_MAP
SELECT (SELECT MAX(LEVEL_MAPID) FROM LEVEL_MAP) + ROWNUM AS LEVEL_MAPID,
       A.LEVELID,
       A.FORMID,
       A.ASSESSMENTID,
       A.DATETIMESTAMP
FROM        
(SELECT 
       LVL.LEVELID,
       FRM.FORMID,
       ASES.ASSESSMENTID,
       SYSDATE AS DATETIMESTAMP
FROM LEVEL_DIM LVL,
     FORM_DIM FRM,
     ASSESSMENT_DIM ASES,
     PRODUCT PDT,
     PROJECT_DIM PJT
WHERE PJT.PROJECT_NAME='Missouri'
  AND PJT.PROJECTID = PDT.PROJECTID
  AND ASES.PRODUCTID = PDT.PRODUCTID
  AND FRM.PROJECTID = PJT.PROJECTID
  AND LVL.PROJECTID = PJT.PROJECTID
  ORDER BY LVL.LEVELID)A;
 
COMMIT; 
---SELECT * FROM LEVEL_MAP; 
   
--GRADE_LEVEL_MAP
INSERT INTO GRADE_LEVEL_MAP
                SELECT LVL_GRD_MAP.GRADEID,
                       LMP.LEVEL_MAPID,
                       'Y' ONLEVEL_FLAG,
                       SYSDATE AS DATETIMESTAMP
                FROM FORM_DIM FRM,
                     PROJECT_DIM PJT,
                     LEVEL_MAP LMP,
                     ASSESSMENT_DIM ASES,
                     PRODUCT PDT,
                    (SELECT GRADEID,LEVELID,GRD.PROJECTID  
                        FROM ( SELECT GRADEID ,GRADE_SEQ,PROJECTID FROM GRADE_DIM WHERE PROJECTID = 3)GRD,
                             (SELECT LEVELID ,ROWNUM AS LEVEL_SEQ FROM LEVEL_DIM WHERE  PROJECTID = 3 ORDER BY LEVEL_NAME)LVL
                        WHERE  GRD.GRADE_SEQ =  LVL.LEVEL_SEQ) LVL_GRD_MAP
                WHERE PJT.PROJECT_NAME='Missouri'
                  AND PJT.PROJECTID = PDT.PROJECTID
                  AND ASES.PRODUCTID = PDT.PRODUCTID
                  AND FRM.PROJECTID = PJT.PROJECTID
                  AND LVL_GRD_MAP.PROJECTID = PJT.PROJECTID 
                  AND LMP.ASSESSMENTID = ASES.ASSESSMENTID  
                  AND LMP.LEVELID = LVL_GRD_MAP.LEVELID
                  AND LMP.FORMID = FRM.FORMID;
COMMIT;
--SELECT * FROM GRADE_LEVEL_MAP;   


--SUBTEST_OBJECTIVE_MAP
CREATE TABLE STG_MO_SUBTEST_OBJECTIVE_MAP
 AS 
 (select 'Reading' AS OBJ_NAME,          '1' AS CODE,  'C' AS OBJ_TYP,     '01' AS SUBTEST_CODE,  'Reading' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Writing' AS OBJ_NAME,          '2' AS CODE,  'C' AS OBJ_TYP,  '01' AS SUBTEST_CODE,  'Writing' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Listening' AS OBJ_NAME,          '3' AS CODE,  'C' AS OBJ_TYP,  '01' AS SUBTEST_CODE,  'Listening' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Research' AS OBJ_NAME,          '4' AS CODE,  'C' AS OBJ_TYP,  '01' AS SUBTEST_CODE,  'Research' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Concepts and Procedures' AS OBJ_NAME,      '1' AS CODE,  'C' AS OBJ_TYP,  '02' AS SUBTEST_CODE,  'Concepts and Procedures' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Prob. Solving & Modeling & Data Anal.' AS OBJ_NAME,    '2' AS CODE,  'C' AS OBJ_TYP,  '02' AS SUBTEST_CODE,  'Problem Solving and Modeling and Data Analysis' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Communicating Reasoning' AS OBJ_NAME,      '3' AS CODE,  'C' AS OBJ_TYP,  '02' AS SUBTEST_CODE,  'Communicating Reasoning' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Matter and Energy' AS OBJ_NAME,        '1' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Properties and Principles of Matter and Energy' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Force and Motion' AS OBJ_NAME,        '2' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Properties and Principles of Force and Motion' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Living Organisms' AS OBJ_NAME,        '3' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Characteristics and Interactions of Living Organisms' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Ecosystems' AS OBJ_NAME,          '4' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Changes in Ecosystems and Interactions of Organisms with their Environments' AS DESCRIPTION FROM DUAL
UNION ALL
select q'[Earth's Systems]' AS OBJ_NAME,        '5' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  q'[Processes and Interactions of the Earth's Systems (Geosphere, Atmosphere and Hydroshpere)]' AS DESCRIPTION FROM DUAL
UNION ALL
select 'The Universe' AS OBJ_NAME,          '6' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Composition and Structure of the Universe and the Motion of the Objects Within It' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Scientific Inquiry' AS OBJ_NAME,        '7' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Scientific Inquiry' AS DESCRIPTION FROM DUAL
UNION ALL
select 'Impact of Sci., Tech. and Human Activity' AS OBJ_NAME,  '8' AS CODE,  'C' AS OBJ_TYP,  '03' AS SUBTEST_CODE,  'Impact of Science, Technology and Human Activity' AS DESCRIPTION FROM DUAL
);



 --SUBTEST_OBJECTIVE_MAP (RUN BOTH THE INSERT QUERIES IN THE GIVEN ORDER)
            INSERT INTO SUBTEST_OBJECTIVE_MAP 
                 SELECT (SELECT MAX(SUBT_OBJ_MAPID) FROM SUBTEST_OBJECTIVE_MAP)+ROWNUM AS SUBT_OBJ_MAPID,
                        A.SUBTESTID,
                        A.OBJECTIVEID,
                        A.LEVEL_MAPID,
                        A.ASSESSMENTID ,
                        A.DATETIMESTAMP
                 FROM (SELECT SUB.SUBTESTID,
                        OBJ.OBJECTIVEID,
                        GLM.LEVEL_MAPID,
                        ASES.ASSESSMENTID,
                        SYSDATE AS DATETIMESTAMP
                 FROM LEVEL_DIM LVL,
                     FORM_DIM FRM,
                     PROJECT_DIM PJT,
                     LEVEL_MAP LMP,
                     GRADE_LEVEL_MAP GLM,
                     ASSESSMENT_DIM ASES,
                     PRODUCT PDT,
                     STG_MO_SUBTEST_OBJECTIVE_MAP STG_OBJ,
                     SUBTEST_DIM SUB,
                     OBJECTIVE_DIM OBJ,
                     CONTENT_DIM CONT
                WHERE PJT.PROJECT_NAME='Missouri'
                  AND PJT.PROJECTID = PDT.PROJECTID
                  AND ASES.PRODUCTID = PDT.PRODUCTID
                  AND FRM.PROJECTID = PJT.PROJECTID
                  AND LVL.PROJECTID = PJT.PROJECTID 
                  AND LMP.ASSESSMENTID = ASES.ASSESSMENTID  
                  AND LMP.LEVELID = LVL.LEVELID
                  AND LMP.FORMID = FRM.FORMID
                  AND CONT.ASSESSMENTID =ASES.ASSESSMENTID 
                  AND CONT.CONTENTID = SUB.CONTENTID
                  AND SUB.SUBTEST_CODE = STG_OBJ.SUBTEST_CODE
                  AND STG_OBJ.OBJ_NAME = OBJ.OBJECTIVE_NAME
                  AND STG_OBJ.OBJ_TYP = OBJ.OBJECTIVE_TYPE
                  AND OBJ.PROJECTID = PJT.PROJECTID
                  AND GLM.LEVEL_MAPID = LMP.LEVEL_MAPID
                  AND STG_OBJ.SUBTEST_CODE  <> '03'
                  ORDER BY SUB.SUBTESTID,
                        OBJ.OBJECTIVEID,
                        GLM.LEVEL_MAPID,
                        ASES.ASSESSMENTID)A;
                  
                  COMMIT;
                  
                  
                 INSERT INTO SUBTEST_OBJECTIVE_MAP 
                 SELECT (SELECT MAX(SUBT_OBJ_MAPID) FROM SUBTEST_OBJECTIVE_MAP)+ROWNUM AS SUBT_OBJ_MAPID,
                         A.SUBTESTID,
                         A.OBJECTIVEID,
                         A.LEVEL_MAPID,
                         A.ASSESSMENTID,
                         A.DATETIMESTAMP
                 FROM
                 (SELECT SUB.SUBTESTID,
                        OBJ.OBJECTIVEID,
                        GLM.LEVEL_MAPID,
                        ASES.ASSESSMENTID,
                        SYSDATE AS DATETIMESTAMP
                 FROM LEVEL_DIM LVL,
                     FORM_DIM FRM,
                     PROJECT_DIM PJT,
                     LEVEL_MAP LMP,
                     GRADE_LEVEL_MAP GLM,
                     ASSESSMENT_DIM ASES,
                     PRODUCT PDT,
                     STG_MO_SUBTEST_OBJECTIVE_MAP STG_OBJ,
                     SUBTEST_DIM SUB,
                     OBJECTIVE_DIM OBJ,
                     CONTENT_DIM CONT,
                     GRADE_DIM GRD
                WHERE PJT.PROJECT_NAME='Missouri'
                  AND PJT.PROJECTID = PDT.PROJECTID
                  AND ASES.PRODUCTID = PDT.PRODUCTID
                  AND FRM.PROJECTID = PJT.PROJECTID
                  AND LVL.PROJECTID = PJT.PROJECTID 
                  AND LMP.ASSESSMENTID = ASES.ASSESSMENTID  
                  AND LMP.LEVELID = LVL.LEVELID
                  AND LMP.FORMID = FRM.FORMID
                  AND CONT.ASSESSMENTID =ASES.ASSESSMENTID 
                  AND CONT.CONTENTID = SUB.CONTENTID
                  AND SUB.SUBTEST_CODE = STG_OBJ.SUBTEST_CODE
                  AND STG_OBJ.OBJ_NAME = OBJ.OBJECTIVE_NAME
                  AND STG_OBJ.OBJ_TYP = OBJ.OBJECTIVE_TYPE
                  AND OBJ.PROJECTID = PJT.PROJECTID
                  AND GLM.LEVEL_MAPID = LMP.LEVEL_MAPID
                  AND STG_OBJ.SUBTEST_CODE  = '03'
                  AND GRD.PROJECTID = PJT.PROJECTID 
                  AND GRD.GRADEID = GLM.GRADEID
                  AND GRD.GRADE_CODE IN ('05','08')
                  ORDER BY  SUB.SUBTESTID,
                        OBJ.OBJECTIVEID,
                        GLM.LEVEL_MAPID,
                        ASES.ASSESSMENTID)A;
              COMMIT;
              
              
-- SCORE_TYPE_LOOKUP             
INSERT INTO SCORE_TYPE_LOOKUP
SELECT  SEQ_SCORE_LKP_ID.NEXTVAL AS SCORE_TYPEID,
        A.CATEGORY,
        A.SCORE_TYPE,
        A.SCORE_VALUE,
        A.SCORE_VALUE_NAME,    
        B.CUST_PROD_ID,
        SYSDATE AS CREATED_DATE_TIME,
        SYSDATE AS UPDATED_DATE_TIME
 FROM       
(SELECT 'SUBTEST' AS CATEGORY, 'SUB_ACHV_LVL' AS SCORE_TYPE, '0' AS SCORE_VALUE  ,  'Level Not Determined' AS SCORE_VALUE_NAME FROM DUAL
UNION     
SELECT 'SUBTEST' AS CATEGORY, 'SUB_ACHV_LVL' AS SCORE_TYPE, '1' AS SCORE_VALUE  ,  'Below Basic' AS SCORE_VALUE_NAME FROM DUAL  
UNION
SELECT 'SUBTEST' AS CATEGORY, 'SUB_ACHV_LVL' AS SCORE_TYPE, '2' AS SCORE_VALUE  ,  'Basic' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'SUBTEST' AS CATEGORY, 'SUB_ACHV_LVL' AS SCORE_TYPE, '3' AS SCORE_VALUE  ,  'Proficient' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'SUBTEST' AS CATEGORY, 'SUB_ACHV_LVL' AS SCORE_TYPE, '4' AS SCORE_VALUE  ,  'Advanced' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'OBJECTIVE' AS CATEGORY, 'OBJ_ACHV_LVL' AS SCORE_TYPE, '0' AS SCORE_VALUE  ,  'Level Not Determined' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'OBJECTIVE' AS CATEGORY, 'OBJ_ACHV_LVL' AS SCORE_TYPE, '1' AS SCORE_VALUE  ,  'Below Standard' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'OBJECTIVE' AS CATEGORY, 'OBJ_ACHV_LVL' AS SCORE_TYPE, '2' AS SCORE_VALUE  ,  'At/Near Standard' AS SCORE_VALUE_NAME FROM DUAL
UNION
SELECT 'OBJECTIVE' AS CATEGORY, 'OBJ_ACHV_LVL' AS SCORE_TYPE, '3' AS SCORE_VALUE  ,  'Above Standard' AS SCORE_VALUE_NAME FROM DUAL)A,
(SELECT CUST_PROD_ID FROM CUST_PRODUCT_LINK WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER_INFO WHERE CUSTOMER_NAME='Missouri  MAP – Test'))B;
  
 --SELECT * FROM SCORE_TYPE_LOOKUP;
 COMMIT; 



/********* LIST OF TABLES POPULATED IN ORDER**********
PROJECT_DIM
CUSTOMER_INFO
ADMIN_DIM
PRODUCT
CUST_PRODUCT_LINK
ASSESSMENT_DIM
TEST_PROGRAM
ORG_TP_STRUCTURE
CONTENT_DIM
SUBTEST_DIM
OBJECTIVE_DIM
GRADE_DIM
LEVEL_DIM
FORM_DIM
GENDER_DIM
LEVEL_MAP
GRADE_LEVEL_MAP
SUBTEST_OBJECTIVE_MAP
SCORE_TYPE_LOOKUP
*************************************************/

/*******
1.ON GLOBAL SCHEMA RUN 5_GLOBAL_GRANT_MO.sql TO GIVE GRANT TO MISSOURI DB

*******/
