--missouri(Istep New Blank Schema) RUN FROM THE GLOBAL SCHEMA

--TABLE
GRANT SELECT,REFERENCES,UPDATE,INSERT,DELETE ON PDF_REPORTS TO missouri;
GRANT SELECT ON FTP_CONFIG TO missouri;
GRANT SELECT ON ETL_JOBMASTER_CONFIG TO missouri;
GRANT SELECT ON ETL_PROJECT_CONFIG TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_ACTION_ACCESS TO missouri;
GRANT SELECT ON DASH_CONTRACT_PROP TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_RPT_ACTION TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON SCORE_TYPE_LOOKUP TO missouri;
GRANT SELECT,REFERENCES ON ITEMSET_DIM TO missouri;
GRANT SELECT ON PROJECT_DIM TO missouri;
GRANT SELECT,INSERT,REFERENCES,DELETE ON CUSTOMER_INFO TO missouri;
GRANT SELECT,REFERENCES ON ADMIN_DIM TO missouri;
GRANT SELECT ON PRODUCT TO missouri;
GRANT SELECT,INSERT,DELETE,REFERENCES ON CUST_PRODUCT_LINK TO missouri;
GRANT SELECT,REFERENCES ON ASSESSMENT_DIM TO missouri;
GRANT SELECT,REFERENCES ON GRADE_DIM TO missouri;
GRANT SELECT,REFERENCES ON GENDER_DIM TO missouri;
GRANT SELECT,REFERENCES ON LEVEL_DIM TO missouri;
GRANT SELECT,REFERENCES ON FORM_DIM TO missouri;
GRANT SELECT,REFERENCES ON READ_DIM TO missouri;
GRANT SELECT,REFERENCES ON CONTENT_DIM TO missouri;
GRANT SELECT,REFERENCES ON SUBTEST_DIM TO missouri;
GRANT SELECT,REFERENCES ON OBJECTIVE_DIM TO missouri;
GRANT SELECT,INSERT,DELETE,REFERENCES ON TEST_PROGRAM TO missouri;
GRANT SELECT,INSERT,DELETE ON ORG_TP_STRUCTURE TO missouri;
GRANT SELECT ON LEVEL_MAP TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE,REFERENCES ON SUBTEST_OBJECTIVE_MAP TO missouri;
GRANT SELECT ON GRADE_LEVEL_MAP TO missouri;
GRANT SELECT,REFERENCES ON ROLE TO missouri;
--GRANT SELECT ON ROLE_CUSTOMER TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_REPORTS TO missouri;
GRANT SELECT ON DASH_MENUS TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MENU_RPT_ACCESS TO missouri;
GRANT SELECT,INSERT,DELETE ON DASH_MESSAGE_TYPE TO missouri;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MESSAGES TO missouri;
GRANT SELECT,REFERENCES ON PWD_HINT_QUESTIONS TO missouri;
GRANT SELECT,REFERENCES ON CONDITION_CODES TO missouri;
GRANT SELECT,INSERT,DELETE ON ORG_USER_DEFINE_LOOKUP TO missouri;
GRANT SELECT ON NATL_MEAN_SS_LOOKUP TO missouri;
GRANT SELECT ON NP_MEAN_NCE_LOOKUP TO missouri;
GRANT SELECT ON NP_NCE_LOOKUP TO missouri;
GRANT SELECT,REFERENCES ON ACTIVITY_TYPE TO missouri;

-- Sequences

GRANT SELECT ON SEQ_DASH_ACTION_ACCESS TO missouri;
GRANT SELECT ON SEQ_DASH_CONTRACT_PROP TO missouri;
GRANT SELECT ON SEQ_DASH_RPT_ACTION TO missouri;
GRANT SELECT ON DB_REPORT_ID_SEQ TO missouri;
GRANT SELECT ON DASH_MESSAGE_SEQ TO missouri;
GRANT SELECT ON RPTMSGTYPE_SEQ TO missouri;
GRANT SELECT ON SEQ_SCORE_LKP_ID TO missouri;
GRANT SELECT ON NMN_LOOKUPID_SEQ TO missouri;

-- TYPE

GRANT ALL ON DYN_ATTR_DTLS TO missouri;

