
--ETL_JOBMASTER_CONFIG
DELETE FROM ETL_JOBMASTER_CONFIG WHERE PROJECTID =(SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri');
-----------------------------
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STUDENT_BIO_DIM_LOAD', 'S_OPR_STUDENT_BIO_DIM_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STUDENT_DEMO_VALUES_LOAD', 'S_OPR_STUDENT_DEMO_VALUES_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_SUBTEST_SCORE_FACT_LOAD', 'S_OPR_SUBTEST_SCORE_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_SUBTEST_LOAD', 'S_PROCESS_STATUS_STG_SUBTEST_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_SUBTEST_FACT_LOAD', 'S_PROCESS_STATUS_OPR_SUBTEST_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_ORG_EXAMINER_LOOKUP_LOAD', 'S_ORG_EXAMINER_LOOKUP_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_OBJECTIVE_SCORE_FACT_LOAD', 'S_OPR_OBJECTIVE_SCORE_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ITEM_SCORE_FACT_LOAD', 'S_OPR_ITEM_SCORE_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_ITEM_FACT_LOAD', 'S_PROCESS_STATUS_OPR_ITEM_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_OBJECTIVE_FACT_LOAD', 'S_PROCESS_STATUS_OPR_OBJECTIVE_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ITEM_SCORE_FACT_LOAD', 'S_OPR_ITEM_SCORE_FACT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_GRADE_SELECTION_LOOKUP_LOAD', 'S_OPR_GRADE_SELECTION_LOOKUP_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ORG_TEST_PROGRAM_LINK_LOAD', 'S_OPR_ORG_TEST_PROGRAM_LINK_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_ORG_PRODUCT_LINK_STUDENT_LOAD', 'S_OPR_ORG_PRODUCT_LINK_STUDENT_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('03-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('03-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STUDENT_RAW_DATA_LOAD', 'S_STUDENT_RAW_DATA_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('04-03-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('04-03-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_HIER_LOAD', 'S_PROCESS_STATUS_HIER_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('24-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_BIO_DETAILS_LOAD', 'S_STG_STD_BIO_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('24-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_DEMO_DETAILS_LOAD', 'S_STG_DEMO_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('25-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('25-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_OBJECTIVE_DETAILS_LOAD', 'S_STG_STD_OBJECTIVE_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_OBJECTIVE_LOAD', 'S_PROCESS_STATUS_STG_OBJECTIVE_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STUDENT_DATA_EXTRACT', 'S_STUDENT_DATA_EXTRACT', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('24-02-2015 12:00:00', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-02-2015 12:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_HIER_DETAILS_LOAD', 'S_STG_HIER_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('24-02-2015 12:00:00', 'dd-mm-yyyy hh24:mi:ss'), to_date('24-02-2015 12:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_LSTNODE_HIER_LOAD', 'S_STG_LSTNODE_HIER_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('25-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('25-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_BIO_LOAD', 'S_PROCESS_STATUS_STG_BIO_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_DEMO_LOAD', 'S_PROCESS_STATUS_STG_DEMO_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_SUBTEST_LOAD', 'S_PROCESS_STATUS_STG_SUBTEST_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_STD_SUBTEST_DETAILS_LOAD', 'S_STG_STD_SUBTEST_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STG_ITEM_RESPONSE_DETAILS_LOAD', 'S_STG_ITEM_RESPONSE_DETAILS_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_STG_ITEM_LOAD', 'S_PROCESS_STATUS_STG_ITEM_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_BIO_LOAD', 'S_PROCESS_STATUS_OPR_BIO_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_STUDENT_DEMO_LOAD', 'S_PROCESS_STATUS_OPR_STUDENT_DEMO_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_PROCESS_STATUS_OPR_SUBTEST_DEMO_LOAD', 'S_PROCESS_STATUS_OPR_SUBTEST_DEMO_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_OPR_STU_SUBTEST_DEMO_VALUES_LOAD', 'S_OPR_STU_SUBTEST_DEMO_VALUES_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_EXAMINER_DIM_DATA_LOAD', 'S_EXAMINER_DIM_DATA_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));

--NEW
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STUDENT_ERROR_DATA_LOAD', 'S_STUDENT_ERROR_DATA_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_STUDENT_PROCESS_VALIDATION_EMAIL', 'S_STUDENT_PROCESS_VALIDATION_EMAIL', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
--
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_MO_NCOUNT_FILE_GEN', 'S_MO_NCOUNT_FILE_GEN', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_MO_NCOUNT_EMAIL', 'S_MO_NCOUNT_EMAIL', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'));
--NEW ADDED ON 03/25/2015
insert into ETL_JOBMASTER_CONFIG (MAPPING_NAME, SESSION_NAME, WORKFLOW_NAME, REPOSITORY_SERVICE, INTEGRATION_SERVICE, DOMAIN_NAME, PROJECTID, CREATED_DATE_TIME, UPDATED_DATE_TIME)
values ('M_MO_CUST_PROD_ID_SCHOOL_LOAD', 'S_MO_CUST_PROD_ID_SCHOOL_LOAD', 'WKF_MISSOURI_PRISM_GRT_LOAD', null, null, null, 3, to_date('27-02-2015 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), to_date('27-02-2015 00:00:02', 'dd-mm-yyyy hh24:mi:ss'));

commit;



-------------------------------------------------------------------------------------------
DELETE FROM ETL_PROJECT_CONFIG WHERE PROJECTID = (SELECT PROJECTID FROM PROJECT_DIM WHERE PROJECT_NAME='Missouri');
--ETL_PROJECT_CONFIG
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (1, 'STATE_CODE', 1, 2, 2, 'STG_HIER_DETAILS', 'STATE_CODE', 'STATE_CODE', 'ORG', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (2, 'TEST_TYPE', 3, 15, 13, 'STG_HIER_DETAILS', 'TEST_TYPE', 'TEST_TYPE', 'ORG', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (3, 'DISTRICT_CODE', 16, 21, 6, 'STG_HIER_DETAILS', 'DISTRICT_CODE', 'DISTRICT_CODE', 'ORG', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (4, 'SCHOOL_CODE', 22, 25, 4, 'STG_HIER_DETAILS', 'SCHOOL_CODE', 'SCHOOL_CODE', 'ORG', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (5, 'GRADE', 26, 27, 2, 'STG_HIER_DETAILS', 'GRADE', 'GRADE', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (6, 'CITY', 28, 57, 30, 'STG_STD_DEMO_DETAILS', 'CITY', 'CITY', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (7, 'CURRENT_SCHOOL_YEAR', 58, 61, 4, 'STG_STD_DEMO_DETAILS', 'CURRENT_SCHOOL_YEAR', 'CURRENT_SCHOOL_YEAR', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (8, 'DRC_STUDENT_ID', 74, 83, 10, 'STG_STD_BIO_DETAILS', 'DRC_STUDENT_ID', 'DRC_STUDENT_ID', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (9, 'LOCAL_STUDENT_ID', 84, 103, 20, 'STG_STD_BIO_DETAILS', 'LOCAL_STUDENT_ID', 'LOCAL_STUDENT_ID', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (10, 'STATE_ID', 104, 113, 10, 'STG_STD_BIO_DETAILS', 'STATE_ID', 'STATE_ID', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (11, 'LAST_NAME', 114, 173, 60, 'STG_STD_BIO_DETAILS', 'LAST_NAME', 'LAST_NAME', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (12, 'FIRST_NAME', 174, 233, 60, 'STG_STD_BIO_DETAILS', 'FIRST_NAME', 'FIRST_NAME', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (13, 'MIDDLE_NAME', 234, 293, 60, 'STG_STD_BIO_DETAILS', 'MIDDLE_NAME', 'MIDDLE_NAME', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (14, 'SUFFIX', 294, 303, 10, 'STG_STD_BIO_DETAILS', 'SUFFIX', 'SUFFIX', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (15, 'BIRTH_DATE', 304, 313, 10, 'STG_STD_BIO_DETAILS', 'BIRTH_DATE', 'BIRTH_DATE', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (16, 'GENDER', 314, 314, 1, 'STG_STD_BIO_DETAILS', 'GENDER', 'GENDER', 'BIO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (17, 'RACE_ETHNICITY', 315, 315, 1, 'STG_STD_DEMO_DETAILS', 'RACE_ETHNICITY', 'RACE_ETHNICITY', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (18, 'HOME_SCHOOL', 316, 316, 1, 'STG_STD_DEMO_DETAILS', 'HOME_SCHOOL', 'HOME_SCHOOL', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (19, 'PRIVATE_SCHOOL', 317, 317, 1, 'STG_STD_DEMO_DETAILS', 'PRIVATE_SCHOOL', 'PRIVATE_SCHOOL', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (20, 'STATE_USE_1', 318, 318, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_1', 'STATE_USE_1', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (21, 'STATE_USE_2', 319, 319, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_2', 'STATE_USE_2', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));


insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (22, 'STATE_USE_3', 320, 320, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_3', 'STATE_USE_3', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (23, 'STATE_USE_4', 321, 321, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_4', 'STATE_USE_4', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (24, 'STATE_USE_5', 322, 322, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_5', 'STATE_USE_5', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (25, 'STATE_USE_6', 323, 323, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_6', 'STATE_USE_6', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (26, 'STATE_USE_7', 324, 324, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_7', 'STATE_USE_7', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (27, 'STATE_USE_8', 325, 325, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_8', 'STATE_USE_8', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (28, 'STATE_USE_9', 326, 326, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_9', 'STATE_USE_9', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (29, 'STATE_USE_10', 327, 327, 1, 'STG_STD_DEMO_DETAILS', 'STATE_USE_10', 'STATE_USE_10', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (30, 'PERIOD', 328, 329, 2, 'STG_STD_DEMO_DETAILS', 'PERIOD', 'PERIOD', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (31, 'CONTENT_CODE', 330, 331, 2, 'STG_STD_SUBTEST_DETAILS', 'CONTENT_CODE', 'CONTENT_CODE', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (32, 'CONTENT_FORM', 332, 334, 3, 'STG_STD_SUBTEST_DETAILS', 'CONTENT_FORM', 'CONTENT_FORM', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (33, 'PT_CONTENT_FORM', 335, 337, 3, 'STG_STD_DEMO_DETAILS', 'PT_CONTENT_FORM', 'PT_CONTENT_FORM', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (34, 'EDUCATOR_FIRST_NAME', 338, 397, 60, 'STG_STD_SUBTEST_DETAILS', 'EDUCATOR_FIRST_NAME', 'EDUCATOR_FIRST_NAME', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (35, 'EDUCATOR_LAST_NAME', 398, 457, 60, 'STG_STD_SUBTEST_DETAILS', 'EDUCATOR_LAST_NAME', 'EDUCATOR_LAST_NAME', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (36, 'EXAMINER_EMAIL', 458, 527, 70, 'STG_STD_SUBTEST_DETAILS', 'EXAMINER_EMAIL', 'EXAMINER_EMAIL', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (37, 'CONTENT_EXPORT_DATE_TIME', 528, 542, 15, 'STG_STD_SUBTEST_DETAILS', 'CONTENT_EXPORT_DATE_TIME', 'CONTENT_EXPORT_DATE_TIME', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (38, 'TEST_DATE', 543, 552, 10, 'STG_STD_SUBTEST_DETAILS', 'TEST_DATE', 'TEST_DATE', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (39, 'PRECODE_FLAG', 553, 553, 1, 'STG_STD_SUBTEST_DETAILS', 'PRECODE_FLAG', 'PRECODE_FLAG', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (40, 'ACCOMMODATIONS', 604, 641, 38, 'STG_STD_DEMO_DETAILS', 'ACCOMMODATIONS', 'ACCOMMODATIONS', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));


insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (41, 'TEACHER_INVALIDATION', 662, 662, 1, 'STG_STD_DEMO_DETAILS', 'TEACHER_INVALIDATION', 'TEACHER_INVALIDATION', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (42, 'ABSENT', 663, 663, 1, 'STG_STD_DEMO_DETAILS', 'ABSENT', 'ABSENT', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));



insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (43, 'CONTENT_AREA_TITLE', 664, 684, 21, 'STG_ITEM_RESPONSE_DETAILS', 'CONTENT_AREA_TITLE', 'CONTENT_AREA_TITLE', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (44, 'ITEM_RESPONSE_MC', 685, 784, 100, 'STG_ITEM_RESPONSE_DETAILS', 'ITEM_RESPONSE_MC', 'ITEM_RESPONSE_MC', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));


insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (45, 'ITEM_SCORE_MC', 785, 884, 100, 'STG_ITEM_RESPONSE_DETAILS', 'ITEM_SCORE_MC', 'ITEM_SCORE_MC', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (46, 'RAW_SCORE_MC', 885, 887, 3, 'STG_ITEM_RESPONSE_DETAILS', 'RAW_SCORE_MC', 'RAW_SCORE_MC', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (47, 'ITEM_SCORE_CR', 888, 987, 100, 'STG_ITEM_RESPONSE_DETAILS', 'ITEM_SCORE_CR', 'ITEM_SCORE_CR', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (48, 'RAW_SCORE_CR', 988, 990, 3, 'STG_ITEM_RESPONSE_DETAILS', 'RAW_SCORE_CR', 'RAW_SCORE_CR', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (49, 'ITEM_SCORE_TE', 991, 1040, 50, 'STG_ITEM_RESPONSE_DETAILS', 'ITEM_SCORE_TE', 'ITEM_SCORE_TE', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (50, 'RAW_SCORE_TE', 1041, 1043, 3, 'STG_ITEM_RESPONSE_DETAILS', 'RAW_SCORE_TE', 'RAW_SCORE_TE', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (51, 'TOTAL_RAW_SCORE', 1044, 1046, 3, 'STG_ITEM_RESPONSE_DETAILS', 'TOTAL_RAW_SCORE', 'TOTAL_RAW_SCORE', 'ITEM', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (52, 'COMPLETION_CRITERIA', 1047, 1047, 1, 'STG_STD_SUBTEST_DETAILS', 'COMPLETION_CRITERIA', 'COMPLETION_CRITERIA', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (53, 'PERCENT_CORRECT', 1048, 1051, 4, 'STG_STD_SUBTEST_DETAILS', 'PERCENT_CORRECT', 'PERCENT_CORRECT', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (54, 'SCALE_SCORE', 1052, 1055, 4, 'STG_STD_SUBTEST_DETAILS', 'SCALE_SCORE', 'SCALE_SCORE', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (55, 'CONTENT_ACHIEV_LEVEL', 1056, 1056, 1, 'STG_STD_SUBTEST_DETAILS', 'CONTENT_ACHIEV_LEVEL', 'CONTENT_ACHIEV_LEVEL', 'SUBTEST', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (56, 'READING_OBJECTIVE_1_CODE', 1087, 1087, 1, 'STG_STD_OBJECTIVE_DETAILS', 'RD_OBJ_1', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (57, 'READING_OBJECTIVE_1_NUMBER_CORRECT', 1088, 1090, 3, 'STG_STD_OBJECTIVE_DETAILS', 'RD_OBJ_1', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (58, 'READING_OBJECTIVE_1_PERCENT_CORRECT', 1091, 1094, 4, 'STG_STD_OBJECTIVE_DETAILS', 'RD_OBJ_1', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (59, 'READING_OBJECTIVE_1_ACHEIVEMENT_LEVEL', 1095, 1095, 1, 'STG_STD_OBJECTIVE_DETAILS', 'RD_OBJ_1', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (60, 'WRITING_OBJECTIVE_2_CODE', 1096, 1096, 1, 'STG_STD_OBJECTIVE_DETAILS', 'WRT_OBJ_2', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (61, 'WRITING_OBJECTIVE_2_NUMBER_CORRECT', 1097, 1099, 3, 'STG_STD_OBJECTIVE_DETAILS', 'WRT_OBJ_2', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (62, 'WRITING_OBJECTIVE_2_PERCENT_CORRECT', 1100, 1103, 4, 'STG_STD_OBJECTIVE_DETAILS', 'WRT_OBJ_2', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (63, 'WRITING_OBJECTIVE_2_ACHEIVEMENT_LEVEL', 1104, 1104, 1, 'STG_STD_OBJECTIVE_DETAILS', 'WRT_OBJ_2', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (64, 'LISTENING_OBJECTIVE_3_CODE', 1105, 1105, 1, 'STG_STD_OBJECTIVE_DETAILS', 'LIST_OBJ_3', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (65, 'LISTENING_OBJECTIVE_3_NUMBER_CORRECT', 1106, 1108, 3, 'STG_STD_OBJECTIVE_DETAILS', 'LIST_OBJ_3', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (66, 'LISTENING_OBJECTIVE_3_PERCENT_CORRECT', 1109, 1112, 4, 'STG_STD_OBJECTIVE_DETAILS', 'LIST_OBJ_3', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (67, 'LISTENING_OBJECTIVE_3_ACHEIVEMENT_LEVEL', 1113, 1113, 1, 'STG_STD_OBJECTIVE_DETAILS', 'LIST_OBJ_3', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (68, 'RESEARCH_OBJECTIVE_4_CODE', 1114, 1114, 1, 'STG_STD_OBJECTIVE_DETAILS', 'RES_OBJ_4', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (69, 'RESEARCH_OBJECTIVE_4_NUMBER_CORRECT', 1115, 1117, 3, 'STG_STD_OBJECTIVE_DETAILS', 'RES_OBJ_4', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (70, 'RESEARCH_OBJECTIVE_4_PERCENT_CORRECT', 1118, 1121, 4, 'STG_STD_OBJECTIVE_DETAILS', 'RES_OBJ_4', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (71, 'RESEARCH_OBJECTIVE_4_ACHEIVEMENT_LEVEL', 1122, 1122, 1, 'STG_STD_OBJECTIVE_DETAILS', 'RES_OBJ_4', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (72, 'CONCEPT_PROC_OBJECTIVE_5_CODE', 1123, 1123, 1, 'STG_STD_OBJECTIVE_DETAILS', 'CON_OBJ_5', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (73, 'CONCEPT_PROC_OBJECTIVE_5_NUMBER_CORRECT', 1124, 1126, 3, 'STG_STD_OBJECTIVE_DETAILS', 'CON_OBJ_5', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (74, 'CONCEPT_PROC_OBJECTIVE_5_PERCENT_CORRECT', 1127, 1130, 4, 'STG_STD_OBJECTIVE_DETAILS', 'CON_OBJ_5', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (75, 'CONCEPT_PROC_OBJECTIVE_5_ACHEIVEMENT_LEVEL', 1131, 1131, 1, 'STG_STD_OBJECTIVE_DETAILS', 'CON_OBJ_5', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (76, 'PROB_SOV_OBJECTIVE_6_CODE', 1132, 1132, 1, 'STG_STD_OBJECTIVE_DETAILS', 'PROB_OBJ_6', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (77, 'PROB_SOV_OBJECTIVE_6_NUMBER_CORRECT', 1133, 1135, 3, 'STG_STD_OBJECTIVE_DETAILS', 'PROB_OBJ_6', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (78, 'PROB_SOV_OBJECTIVE_6_PERCENT_CORRECT', 1136, 1139, 4, 'STG_STD_OBJECTIVE_DETAILS', 'PROB_OBJ_6', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (79, 'PROB_SOV_OBJECTIVE_6_ACHEIVEMENT_LEVEL', 1140, 1140, 1, 'STG_STD_OBJECTIVE_DETAILS', 'PROB_OBJ_6', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (80, 'COMM_OBJECTIVE_7_CODE', 1141, 1141, 1, 'STG_STD_OBJECTIVE_DETAILS', 'COMM_OBJ_7', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));

insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (81, 'COMM_OBJECTIVE_7_NUMBER_CORRECT', 1142, 1144, 3, 'STG_STD_OBJECTIVE_DETAILS', 'COMM_OBJ_7', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (82, 'COMM_OBJECTIVE_7_PERCENT_CORRECT', 1145, 1148, 4, 'STG_STD_OBJECTIVE_DETAILS', 'COMM_OBJ_7', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (83, 'COMM_OBJECTIVE_7_ACHEIVEMENT_LEVEL', 1149, 1149, 1, 'STG_STD_OBJECTIVE_DETAILS', 'COMM_OBJ_7', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (84, 'MATT_OBJECTIVE_8_CODE', 1150, 1150, 1, 'STG_STD_OBJECTIVE_DETAILS', 'MT_OBJ_8', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (85, 'MATT_OBJECTIVE_8_NUMBER_CORRECT', 1151, 1153, 3, 'STG_STD_OBJECTIVE_DETAILS', 'MT_OBJ_8', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (86, 'MATT_OBJECTIVE_8_PERCENT_CORRECT', 1154, 1157, 4, 'STG_STD_OBJECTIVE_DETAILS', 'MT_OBJ_8', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (87, 'MATT_OBJECTIVE_8_ACHEIVEMENT_LEVEL', 1158, 1158, 1, 'STG_STD_OBJECTIVE_DETAILS', 'MT_OBJ_8', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (88, 'FORCE_OBJECTIVE_9_CODE', 1159, 1159, 1, 'STG_STD_OBJECTIVE_DETAILS', 'FRC_OBJ_9', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (89, 'FORCE_OBJECTIVE_9_NUMBER_CORRECT', 1160, 1162, 3, 'STG_STD_OBJECTIVE_DETAILS', 'FRC_OBJ_9', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (90, 'FORCE_OBJECTIVE_9_PERCENT_CORRECT', 1163, 1166, 4, 'STG_STD_OBJECTIVE_DETAILS', 'FRC_OBJ_9', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (91, 'FORCE_OBJECTIVE_9_ACHEIVEMENT_LEVEL', 1167, 1167, 1, 'STG_STD_OBJECTIVE_DETAILS', 'FRC_OBJ_9', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (92, 'LIVING_OBJECTIVE_10_CODE', 1168, 1168, 1, 'STG_STD_OBJECTIVE_DETAILS', 'LV_OBJ_10', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (93, 'LIVING_OBJECTIVE_10_NUMBER_CORRECT', 1169, 1171, 3, 'STG_STD_OBJECTIVE_DETAILS', 'LV_OBJ_10', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (94, 'LIVING_OBJECTIVE_10_PERCENT_CORRECT', 1172, 1175, 4, 'STG_STD_OBJECTIVE_DETAILS', 'LV_OBJ_10', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (95, 'LIVING_OBJECTIVE_10_ACHEIVEMENT_LEVEL', 1176, 1176, 1, 'STG_STD_OBJECTIVE_DETAILS', 'LV_OBJ_10', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (96, 'ECO_OBJECTIVE_11_CODE', 1177, 1177, 1, 'STG_STD_OBJECTIVE_DETAILS', 'ECO_OBJ_11', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (97, 'ECO_OBJECTIVE_11_NUMBER_CORRECT', 1178, 1180, 3, 'STG_STD_OBJECTIVE_DETAILS', 'ECO_OBJ_11', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (98, 'ECO_OBJECTIVE_11_PERCENT_CORRECT', 1181, 1184, 4, 'STG_STD_OBJECTIVE_DETAILS', 'ECO_OBJ_11', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (99, 'ECO_OBJECTIVE_11_ACHEIVEMENT_LEVEL', 1185, 1185, 1, 'STG_STD_OBJECTIVE_DETAILS', 'ECO_OBJ_11', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (100, 'EARTH_OBJECTIVE_12_CODE', 1186, 1186, 1, 'STG_STD_OBJECTIVE_DETAILS', 'ERTH_OBJ_12', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (101, 'EARTH_OBJECTIVE_12_NUMBER_CORRECT', 1187, 1189, 3, 'STG_STD_OBJECTIVE_DETAILS', 'ERTH_OBJ_12', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (102, 'EARTH_OBJECTIVE_12_PERCENT_CORRECT', 1190, 1193, 4, 'STG_STD_OBJECTIVE_DETAILS', 'ERTH_OBJ_12', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (103, 'EARTH_OBJECTIVE_12_ACHEIVEMENT_LEVEL', 1194, 1194, 1, 'STG_STD_OBJECTIVE_DETAILS', 'ERTH_OBJ_12', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (104, 'UNIVERSE_OBJECTIVE_13_CODE', 1195, 1195, 1, 'STG_STD_OBJECTIVE_DETAILS', 'UNV_OBJ_13', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (105, 'UNIVERSE_OBJECTIVE_13_NUMBER_CORRECT', 1196, 1198, 3, 'STG_STD_OBJECTIVE_DETAILS', 'UNV_OBJ_13', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (106, 'UNIVERSE_OBJECTIVE_13_PERCENT_CORRECT', 1199, 1202, 4, 'STG_STD_OBJECTIVE_DETAILS', 'UNV_OBJ_13', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (107, 'UNIVERSE_OBJECTIVE_13_ACHEIVEMENT_LEVEL', 1203, 1203, 1, 'STG_STD_OBJECTIVE_DETAILS', 'UNV_OBJ_13', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (108, 'SCI_OBJECTIVE_14_CODE', 1204, 1204, 1, 'STG_STD_OBJECTIVE_DETAILS', 'SCI_OBJ_14', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (109, 'SCI_OBJECTIVE_14_NUMBER_CORRECT', 1205, 1207, 3, 'STG_STD_OBJECTIVE_DETAILS', 'SCI_OBJ_14', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (110, 'SCI_OBJECTIVE_14_PERCENT_CORRECT', 1208, 1211, 4, 'STG_STD_OBJECTIVE_DETAILS', 'SCI_OBJ_14', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (111, 'SCI_OBJECTIVE_14_ACHEIVEMENT_LEVEL', 1212, 1212, 1, 'STG_STD_OBJECTIVE_DETAILS', 'SCI_OBJ_14', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (112, 'HUMAN_OBJECTIVE_15_CODE', 1213, 1213, 1, 'STG_STD_OBJECTIVE_DETAILS', 'HUM_OBJ_15', 'CODE', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (113, 'HUMAN_OBJECTIVE_15_NUMBER_CORRECT', 1214, 1216, 3, 'STG_STD_OBJECTIVE_DETAILS', 'HUM_OBJ_15', 'NUMBER_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (114, 'HUMAN_OBJECTIVE_15_PERCENT_CORRECT', 1217, 1220, 4, 'STG_STD_OBJECTIVE_DETAILS', 'HUM_OBJ_15', 'PERCENT_CORRECT', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (115, 'HUMAN_OBJECTIVE_15_ACHEIVEMENT_LEVEL', 1221, 1221, 1, 'STG_STD_OBJECTIVE_DETAILS', 'HUM_OBJ_15', 'ACHEIV_LEVEL', 'OBJECTIVE', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
insert into ETL_PROJECT_CONFIG (SEQ_NO, COLUMN_NAME, START_POSITION, END_POSITION, LENGTH, CATEGORY, CATEGORY_TYPE, CATEGORY_VALUE, DATA_EXTRACT_BLOCK, REPLACE_FLAG, REPLACE_VALUE, IS_BIO_UPDATE, DESCRIPTION, ACTIVATION_STATUS, PRODUCT_CODE, PROJECTID, DATETIMESTAMP)
values (116, 'APPEAL_INDICATOR', 1222, 1222, 1, 'STG_STD_DEMO_DETAILS', 'APPEAL_INDICATOR', 'APPEAL_INDICATOR', 'DEMO', 'N', null, null, null, 'AC', null, 3, to_date('25-02-2015 08:10:30', 'dd-mm-yyyy hh24:mi:ss'));
commit;



