--FOR WISC
DECLARE
  V_PROJECTID PROJECT_DIM.PROJECTID%TYPE;
BEGIN

  SELECT PROJECTID
    INTO V_PROJECTID
    FROM PROJECT_DIM
   WHERE UPPER(PROJECT_NAME) LIKE 'WISCONSIN%';

  DELETE FROM DASH_ACTION_ACCESS WHERE PROJECTID = V_PROJECTID;
  DELETE FROM DASH_RPT_ACTION WHERE PROJECTID = V_PROJECTID;
  --MANAGE REPORT
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     CREATED_DATE_TIME,
     PROJECTID)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Add Report',
     'RPT',
     'Add Report',
     SYSDATE,
     V_PROJECTID);
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     CREATED_DATE_TIME,
     PROJECTID)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Edit Report',
     'RPT',
     'Edit Report',
     SYSDATE,
     V_PROJECTID);
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     CREATED_DATE_TIME,
     PROJECTID)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Delete Report',
     'RPT',
     'Delete Report',
     SYSDATE,
     V_PROJECTID);
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     CREATED_DATE_TIME,
     PROJECTID)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Configure Report Message',
     'RPT',
     'Configure Report Message',
     SYSDATE,
     V_PROJECTID);
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Edit Actions',
     'RPT',
     'Edit Actions',
     V_PROJECTID,
     SYSDATE);
	 
  INSERT INTO DASH_RPT_ACTION
    (DB_ACTIONID,
     ACTION_NAME,
     ACTION_TYPE,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (SEQ_DASH_RPT_ACTION.NEXTVAL,
     'Excel',
     'DRPT',
     'Excel',
     V_PROJECTID,
     SYSDATE);

  COMMIT;

END;
/
