--FOR WISC
DECLARE
  V_PROJECTID PROJECT_DIM.PROJECTID%TYPE;
BEGIN

  SELECT PROJECTID
    INTO V_PROJECTID
    FROM PROJECT_DIM
   WHERE UPPER(PROJECT_NAME) LIKE 'WISCONSIN%';

  DELETE FROM DASH_MENU_RPT_ACCESS WHERE PROJECTID = V_PROJECTID;
  DELETE FROM DASH_ACTION_ACCESS WHERE PROJECTID = V_PROJECTID;
  DELETE FROM DASH_MENUS WHERE PROJECTID = V_PROJECTID;

  INSERT INTO DASH_MENUS
    (DB_MENUID,
     MENU_NAME,
     MENU_TYPE,
     MENU_SEQ,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (101, 'Reports', 'CUSTOM', 1, 'Reports', V_PROJECTID, SYSDATE);

  INSERT INTO DASH_MENUS
    (DB_MENUID,
     MENU_NAME,
     MENU_TYPE,
     MENU_SEQ,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (103, 'Resources', 'CUSTOM', 2, 'Resources', V_PROJECTID, SYSDATE);

  INSERT INTO DASH_MENUS
    (DB_MENUID,
     MENU_NAME,
     MENU_TYPE,
     MENU_SEQ,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (104,
     'Useful Links',
     'CUSTOM',
     3,
     'Useful Links',
     V_PROJECTID,
     SYSDATE);

  INSERT INTO DASH_MENUS
    (DB_MENUID,
     MENU_NAME,
     MENU_TYPE,
     MENU_SEQ,
     DESCRIPTION,
     PROJECTID,
     CREATED_DATE_TIME)
  VALUES
    (105, 'Manage', 'CUSTOM', 4, 'Manage', V_PROJECTID, SYSDATE);

  COMMIT;

END;
/
