@\DASH_CONTRACT_PROP_INSERT_WISC.sql;
@\DASH_MENU_INSERT_WISC.sql;
@\DASH_MESSAGE_TYPE_INSERT_WISC.sql;
@\DASH_REPORT_INSERT_WISC.sql;
@\DASH_REPORT_ACTION_INSERT_WISC.sql;
@\DASH_MESSAGES_INSERT_WISC.sql;