CREATE INDEX IDX_USERS_2 ON USERS (USERID, CUSTOMERID);
CREATE INDEX USERS_COMP_INDX_2 ON USERS (UPPER(USERNAME), CUSTOMERID);
CREATE INDEX IDX_USERNAME_USERS ON USERS (UPPER(USERNAME));

CREATE INDEX ORG_USERS_USERID_IDX ON ORG_USERS (USERID, ORG_NODEID); 

CREATE INDEX EDU_CENTER_DETAILS_INDX ON EDU_CENTER_DETAILS (CUSTOMERID, EDU_CENTERID, EDU_CENTER_NAME);

CREATE INDEX IDX_STUDENT_BIO_DIM_1 ON STUDENT_BIO_DIM (ORG_NODEID, STUDENT_BIO_ID);
CREATE INDEX IDX_STUDENT_BIO_DIM_2 ON STUDENT_BIO_DIM (ORG_NODEID);
CREATE INDEX IDX_STUDENT_BIO_DIM_3 ON STUDENT_BIO_DIM (CUSTOMERID, GRADEID, ORG_NODEID, ADMINID, GENDERID, EDU_CENTERID, STUDENT_BIO_ID);
CREATE INDEX IDX_STUDENT_BIO_DIM_4 ON STUDENT_BIO_DIM (TEST_ELEMENT_ID);

CREATE INDEX IDX_SUBTEST_SCORE_FACT_1 ON SUBTEST_SCORE_FACT (STUDENT_BIO_ID, SUBTESTID);
CREATE INDEX SUBTEST_SCORE_FACT_INDX ON SUBTEST_SCORE_FACT (FORMID, HSE, STATUS_CODE, STUDENT_BIO_ID, SUBTESTID);
CREATE INDEX SUBTEST_SCORE_FACT_INDX2 ON SUBTEST_SCORE_FACT (SUBTESTID, TEST_DATE, STUDENT_BIO_ID, CUST_PROD_ID, ASSESSMENTID, GENDERID, GRADEID, FORMID, ADMINID);
CREATE INDEX SUBTEST_SCORE_FACT_INDX_3 ON SUBTEST_SCORE_FACT (ORG_NODEID, ADMINID, ASSESSMENTID, GRADEID, FORMID, LEVELID, SUBTESTID, CUST_PROD_ID);

CREATE INDEX IDX_OBJECTIVE_SCORE_FACT_1 ON OBJECTIVE_SCORE_FACT (OBJECTIVEID);
CREATE INDEX IDX_OBJECTIVE_SCORE_FACT_2 ON OBJECTIVE_SCORE_FACT (STUDENT_BIO_ID, SUBTESTID, OBJECTIVEID);
CREATE INDEX IDX_OBJECTIVE_SCORE_FACT_3 ON OBJECTIVE_SCORE_FACT (SS, ORG_NODEID, ADMINID, CUST_PROD_ID, SUBTESTID, OBJECTIVEID);
CREATE INDEX IDX_OBJECTIVE_SCORE_FACT_4 ON OBJECTIVE_SCORE_FACT (ORG_NODEID, ADMINID, ASSESSMENTID, GRADEID, FORMID, LEVELID, SUBTESTID, CUST_PROD_ID);

CREATE INDEX IDX_ITEM_SCORE_FACT_1 ON ITEM_SCORE_FACT (STUDENT_BIO_ID, SUBTESTID, OBJECTIVEID, ITEMSETID);

CREATE INDEX DEMOGRAPHIC_INDX ON DEMOGRAPHIC (UPPER(DEMO_CODE), CUSTOMERID, DEMOID);

CREATE INDEX DEMOGRAPHIC_VALUES_INDX ON DEMOGRAPHIC_VALUES (DEMO_VALID, DEMO_VALUE_NAME);
CREATE INDEX DEMOGRAPHIC_VALUES_INDX_1 ON DEMOGRAPHIC_VALUES (DEMOID, DEMO_VALID, DEMO_VALUE_NAME, DEMO_VALUE_SEQ);
CREATE INDEX DEMOGRAPHIC_VALUES_INDX_2 ON DEMOGRAPHIC_VALUES (DEMO_VALUE_CODE, DEMOID, DEMO_VALID, DEMO_VALUE_NAME, DEMO_VALUE_SEQ);

CREATE INDEX IDX_STU_SUBTEST_DEMO_VALUES_1 ON STU_SUBTEST_DEMO_VALUES (STUDENT_BIO_ID, DEMOID);

CREATE INDEX IDX_STUDENT_DEMO_VALUES_1 ON STUDENT_DEMO_VALUES (STUDENT_BIO_ID, DEMOID);

CREATE UNIQUE INDEX PK_PWD_HINT_ANSWERS2 ON PWD_HINT_ANSWERS (USERID, PH_QUESTIONID);

create unique index IDX_ORGUSER_MAPPING_1 on ORGUSER_MAPPING (UPPER(USERNAME), LOWEST_NODEID);
create index IDX_ORGUSER_MAPPING_2 on ORGUSER_MAPPING (UPPER(USERNAME));
create index IDX_ORGUSER_MAPPING_3 on ORGUSER_MAPPING (USERNAME, LOWEST_NODEID, ADMINID);
create index IDX_ORGUSER_MAPPING_4 on ORGUSER_MAPPING (USERID, ORG_NODEID, CUSTOMERID);

create index IDX_ORGUSER_DETAILS_1 on ORGUSER_DETAILS (USERID, ORG_NODEID, CUSTOMERID, ADMINID);

create index IDX_ORGUSER_MAPP_SEARCH_3 on ORGUSER_MAPPING_SEARCH (USERID, ORG_NODEID, CUSTOMERID);
create index ORGUSER_MAPPING_SEARCH_INDX on ORGUSER_MAPPING_SEARCH (ORG_NODEID, ORG_NODE_LEVEL, UPPER(USERNAME), LOWEST_NODEID, NMBR_OF_ORGS);
CREATE INDEX IDX_ORG_LSTNODE_LINK_1 ON ORG_LSTNODE_LINK(ORG_LSTNODEID,ADMINID);
CREATE INDEX IDX_MV_SUB_OBJ_FORM_MAP_1 ON MV_SUB_OBJ_FORM_MAP(SUBTESTID,OBJECTIVEID,FORMID,LEVELID,ASSESSMENTID);



