--(remember to change the schema name for global schema) 
--Tables

CREATE OR REPLACE SYNONYM SCORE_TYPE_LOOKUP FOR prism_global.SCORE_TYPE_LOOKUP;
CREATE OR REPLACE SYNONYM PROJECT_DIM FOR prism_global.PROJECT_DIM;
CREATE OR REPLACE SYNONYM PWD_HINT_QUESTIONS FOR prism_global.PWD_HINT_QUESTIONS;
CREATE OR REPLACE SYNONYM ACTIVITY_TYPE FOR prism_global.ACTIVITY_TYPE;
--CREATE OR REPLACE SYNONYM ROLE FOR prism_global.ROLE;


-- Sequences

CREATE OR REPLACE SYNONYM SEQ_DASH_ACTION_ACCESS FOR prism_global.SEQ_DASH_ACTION_ACCESS;
CREATE OR REPLACE SYNONYM SEQ_DASH_CONTRACT_PROP FOR prism_global.SEQ_DASH_CONTRACT_PROP;
CREATE OR REPLACE SYNONYM SEQ_DASH_RPT_ACTION FOR prism_global.SEQ_DASH_RPT_ACTION;
CREATE OR REPLACE SYNONYM DB_REPORT_ID_SEQ FOR prism_global.DB_REPORT_ID_SEQ;
CREATE OR REPLACE SYNONYM DASH_MESSAGE_SEQ FOR prism_global.DASH_MESSAGE_SEQ;
CREATE OR REPLACE SYNONYM RPTMSGTYPE_SEQ FOR prism_global.RPTMSGTYPE_SEQ;
CREATE OR REPLACE SYNONYM NMN_LOOKUPID_SEQ FOR prism_global.NMN_LOOKUPID_SEQ;

-- TYPE

CREATE OR REPLACE SYNONYM DYN_ATTR_DTLS FOR prism_global.DYN_ATTR_DTLS;
/