--Global Schema
ALTER TABLE FTP_CONFIG ADD LAYOUT_TYPE VARCHAR2(10);
--TASC Schema
CREATE OR REPLACE VIEW FTP_CONFIG AS
SELECT FTPID,
       CUSTOMERID,
       FTP_NAME,
       HOST_NAME,
       FILE_PROTOCOL,
       USER_NAME,
       PASSWORD,
       FTP_LOCATION,
       FTP_MODE,
       ACTIVATION_STATUS,
       LAYOUT_TYPE,
       DATETIMESTAMP
  FROM PRISMGLOBAL.FTP_CONFIG
 WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM CUSTOMER_INFO);
 
alter type ORG_DETAILS_OBJ modify ATTRIBUTE (TEST_ELEMENT_ID VARCHAR2(50),last_name VARCHAR2(32),first_name VARCHAR2(32),middle_name VARCHAR2(32)) cascade;
-------------------------
--CHECK AND DROP CREATE ACCORDINGLY
CREATE OR REPLACE TYPE SUBOBJITM_SCR_DETAILS_OBJ AS OBJECT
(
  STUDENT_BIO_ID NUMBER ,
  SUBTESTID      NUMBER ,
  CUSTOMERID     NUMBER ,
  SUBTEST_NAME   VARCHAR2(32),
  SUBTEST_CODE   VARCHAR2(20) ,
  TEST_DATE      VARCHAR2(6),
  SCR_STR        VARCHAR2(182),
  OBJECTIVE_CODE VARCHAR2(20) ,
  OBJECTIVE_NAME VARCHAR2(35) ,
  SCORE_TYPE     CHAR(2),
  SCORE_VALUE    VARCHAR2(1),
  NT_ALL_ATTMPT  CHAR(1),
  ITEM_TYPE      VARCHAR2(3) ,
  ITEM_CODE      VARCHAR2(20) ,
  SCORE_VALUES   VARCHAR2(200),
  DRCDOCUMENT_ID NUMBER,
  TCASCHEDULEDATE DATE
);

CREATE OR REPLACE TYPE SUBOBJITM_SCR_DETAILS_TYP IS TABLE OF SUBOBJITM_SCR_DETAILS_OBJ
----------------