--istepscb(Istep New Blank Schema)

--TABLE
GRANT SELECT,REFERENCES,UPDATE,INSERT,DELETE ON PDF_REPORTS TO istepscb;
GRANT SELECT ON FTP_CONFIG TO istepscb;
GRANT SELECT ON ETL_JOBMASTER_CONFIG TO istepscb;
GRANT SELECT ON ETL_PROJECT_CONFIG TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_ACTION_ACCESS TO istepscb;
GRANT SELECT ON DASH_CONTRACT_PROP TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_RPT_ACTION TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON SCORE_TYPE_LOOKUP TO istepscb;
GRANT SELECT,REFERENCES ON ITEMSET_DIM TO istepscb;
GRANT SELECT ON PROJECT_DIM TO istepscb;
GRANT SELECT,INSERT,REFERENCES,DELETE ON CUSTOMER_INFO TO istepscb;
GRANT SELECT,REFERENCES ON ADMIN_DIM TO istepscb;
GRANT SELECT ON PRODUCT TO istepscb;
GRANT SELECT,INSERT,DELETE,REFERENCES ON CUST_PRODUCT_LINK TO istepscb;
GRANT SELECT,REFERENCES ON ASSESSMENT_DIM TO istepscb;
GRANT SELECT,REFERENCES ON GRADE_DIM TO istepscb;
GRANT SELECT,REFERENCES ON GENDER_DIM TO istepscb;
GRANT SELECT,REFERENCES ON LEVEL_DIM TO istepscb;
GRANT SELECT,REFERENCES ON FORM_DIM TO istepscb;
GRANT SELECT,REFERENCES ON READ_DIM TO istepscb;
GRANT SELECT,REFERENCES ON CONTENT_DIM TO istepscb;
GRANT SELECT,REFERENCES ON SUBTEST_DIM TO istepscb;
GRANT SELECT,REFERENCES ON OBJECTIVE_DIM TO istepscb;
GRANT SELECT,INSERT,DELETE,REFERENCES ON TEST_PROGRAM TO istepscb;
GRANT SELECT,INSERT,DELETE ON ORG_TP_STRUCTURE TO istepscb;
GRANT SELECT ON LEVEL_MAP TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE,REFERENCES ON SUBTEST_OBJECTIVE_MAP TO istepscb;
GRANT SELECT ON GRADE_LEVEL_MAP TO istepscb;
GRANT SELECT,REFERENCES ON ROLE TO istepscb;
--GRANT SELECT ON ROLE_CUSTOMER TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_REPORTS TO istepscb;
GRANT SELECT ON DASH_MENUS TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MENU_RPT_ACCESS TO istepscb;
GRANT SELECT,INSERT,DELETE ON DASH_MESSAGE_TYPE TO istepscb;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MESSAGES TO istepscb;
GRANT SELECT,REFERENCES ON PWD_HINT_QUESTIONS TO istepscb;
GRANT SELECT,REFERENCES ON CONDITION_CODES TO istepscb;
GRANT SELECT,INSERT,DELETE ON ORG_USER_DEFINE_LOOKUP TO istepscb;
GRANT SELECT ON NATL_MEAN_SS_LOOKUP TO istepscb;
GRANT SELECT ON NP_MEAN_NCE_LOOKUP TO istepscb;
GRANT SELECT ON NP_NCE_LOOKUP TO istepscb;
GRANT SELECT,REFERENCES ON ACTIVITY_TYPE TO istepscb;

-- Sequences

GRANT SELECT ON SEQ_DASH_ACTION_ACCESS TO istepscb;
GRANT SELECT ON SEQ_DASH_CONTRACT_PROP TO istepscb;
GRANT SELECT ON SEQ_DASH_RPT_ACTION TO istepscb;
GRANT SELECT ON DB_REPORT_ID_SEQ TO istepscb;
GRANT SELECT ON DASH_MESSAGE_SEQ TO istepscb;
GRANT SELECT ON RPTMSGTYPE_SEQ TO istepscb;
GRANT SELECT ON SEQ_SCORE_LKP_ID TO istepscb;
GRANT SELECT ON NMN_LOOKUPID_SEQ TO istepscb;

-- TYPE

GRANT ALL ON DYN_ATTR_DTLS TO istepscb;

------------------------------------------------------------------------------------------
--tasc(tasc New Blank Schema )

--TABLE
GRANT SELECT,REFERENCES,UPDATE,INSERT,DELETE ON PDF_REPORTS TO tasc;
GRANT SELECT ON FTP_CONFIG TO tasc;
GRANT SELECT ON ETL_JOBMASTER_CONFIG TO tasc;
GRANT SELECT ON ETL_PROJECT_CONFIG TO tasc;
GRANT SELECT ON TASC_LOOKUP_DATA_SWAP TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_ACTION_ACCESS TO tasc;
GRANT SELECT ON DASH_CONTRACT_PROP TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_RPT_ACTION TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON SCORE_TYPE_LOOKUP TO tasc;
GRANT SELECT,REFERENCES ON ITEMSET_DIM TO tasc;
GRANT SELECT ON PROJECT_DIM TO tasc;
GRANT SELECT,INSERT,REFERENCES,DELETE ON CUSTOMER_INFO TO tasc;
GRANT SELECT,REFERENCES ON ADMIN_DIM TO tasc;
GRANT SELECT ON PRODUCT TO tasc;
GRANT SELECT,INSERT,DELETE,REFERENCES ON CUST_PRODUCT_LINK TO tasc;
GRANT SELECT,REFERENCES ON ASSESSMENT_DIM TO tasc;
GRANT SELECT,REFERENCES ON GRADE_DIM TO tasc;
GRANT SELECT,REFERENCES ON GENDER_DIM TO tasc;
GRANT SELECT,REFERENCES ON LEVEL_DIM TO tasc;
GRANT SELECT,REFERENCES ON FORM_DIM TO tasc;
GRANT SELECT,REFERENCES ON READ_DIM TO tasc;
GRANT SELECT,REFERENCES ON CONTENT_DIM TO tasc;
GRANT SELECT,REFERENCES ON SUBTEST_DIM TO tasc;
GRANT SELECT,REFERENCES ON OBJECTIVE_DIM TO tasc;
GRANT SELECT,INSERT,DELETE,REFERENCES ON TEST_PROGRAM TO tasc;
GRANT SELECT,INSERT,DELETE ON ORG_TP_STRUCTURE TO tasc;
GRANT SELECT ON LEVEL_MAP TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE,REFERENCES ON SUBTEST_OBJECTIVE_MAP TO tasc;
GRANT SELECT ON GRADE_LEVEL_MAP TO tasc;
GRANT SELECT,REFERENCES ON ROLE TO tasc;
--GRANT SELECT ON ROLE_CUSTOMER TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_REPORTS TO tasc;
GRANT SELECT ON DASH_MENUS TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MENU_RPT_ACCESS TO tasc;
GRANT SELECT ON DASH_MESSAGE_TYPE TO tasc;
GRANT SELECT,UPDATE,INSERT,DELETE ON DASH_MESSAGES TO tasc;
GRANT SELECT,REFERENCES ON PWD_HINT_QUESTIONS TO tasc;
GRANT SELECT,REFERENCES ON CONDITION_CODES TO tasc;
GRANT SELECT,INSERT,DELETE ON ORG_USER_DEFINE_LOOKUP TO tasc;
GRANT SELECT ON NATL_MEAN_SS_LOOKUP TO tasc;
GRANT SELECT,INSERT,DELETE ON NP_MEAN_NCE_LOOKUP TO tasc;
GRANT SELECT ON NP_NCE_LOOKUP TO tasc;
GRANT SELECT,REFERENCES ON ACTIVITY_TYPE TO tasc;

-- Sequences

GRANT SELECT ON SEQ_DASH_ACTION_ACCESS TO tasc;
GRANT SELECT ON SEQ_DASH_CONTRACT_PROP TO tasc;
GRANT SELECT ON SEQ_DASH_RPT_ACTION TO tasc;
GRANT SELECT ON DB_REPORT_ID_SEQ TO tasc;
GRANT SELECT ON DASH_MESSAGE_SEQ TO tasc;
GRANT SELECT ON RPTMSGTYPE_SEQ TO tasc;
GRANT SELECT ON SEQ_SCORE_LKP_ID TO tasc;
GRANT SELECT ON NMN_LOOKUPID_SEQ TO tasc;

--Type

GRANT ALL ON DYN_ATTR_DTLS TO tasc;