package com.ctb.prism.login.transferobject;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.ctb.prism.core.constant.IApplicationConstants;

@Document
public class MFlatUserTO implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    private String _id;
	
    private String isFirstTimeLogin;

    private PwdHistory[] pwdHistory;

    private String customerCode;

    private String password;

    private OrgCategory orgCategory;

    private String isAutoGeneratedUser;

    private String salt;

    private String lastName;

    private String status;

    private String project_id;

    private String firstName;

    private HintAnswers[] hintAnswers;

    private String userType;

    private String isNewUser;

    private String displayName;

    private String signedUserAgrmt;

    private String phoneNum;

    private OrgUser orgUser;

    private String[] userRoles;

    private String middleName;

    private String email;

    private String updatedDate;

    private Address address;

    private String createdDate;

    
    public String get_id() {
		return _id;
	}


	public void set_id(String _id) {
		this._id = _id;
	}


	public String getIsFirstTimeLogin() {
		return isFirstTimeLogin;
	}


	public void setIsFirstTimeLogin(String isFirstTimeLogin) {
		this.isFirstTimeLogin = isFirstTimeLogin;
	}


	public PwdHistory[] getPwdHistory() {
		return pwdHistory;
	}


	public void setPwdHistory(PwdHistory[] pwdHistory) {
		this.pwdHistory = pwdHistory;
	}


	public String getCustomerCode() {
		return customerCode;
	}


	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public OrgCategory getOrgCategory() {
		return orgCategory;
	}


	public void setOrgCategory(OrgCategory orgCategory) {
		this.orgCategory = orgCategory;
	}


	public String getIsAutoGeneratedUser() {
		return isAutoGeneratedUser;
	}


	public void setIsAutoGeneratedUser(String isAutoGeneratedUser) {
		this.isAutoGeneratedUser = isAutoGeneratedUser;
	}


	public String getSalt() {
		return salt;
	}


	public void setSalt(String salt) {
		this.salt = salt;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	

	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getProject_id() {
		return project_id;
	}


	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}


	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public HintAnswers[] getHintAnswers() {
		return hintAnswers;
	}


	public void setHintAnswers(HintAnswers[] hintAnswers) {
		this.hintAnswers = hintAnswers;
	}


	public String getUserType() {
		return userType;
	}


	public void setUserType(String userType) {
		this.userType = userType;
	}


	public String getIsNewUser() {
		return isNewUser;
	}


	public void setIsNewUser(String isNewUser) {
		this.isNewUser = isNewUser;
	}


	public String getDisplayName() {
		return displayName;
	}


	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}


	public String getSignedUserAgrmt() {
		return signedUserAgrmt;
	}


	public void setSignedUserAgrmt(String signedUserAgrmt) {
		this.signedUserAgrmt = signedUserAgrmt;
	}


	public String getPhoneNum() {
		return phoneNum;
	}


	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}


	public OrgUser getOrgUser() {
		return orgUser;
	}


	public void setOrgUser(OrgUser orgUser) {
		this.orgUser = orgUser;
	}


	public String[] getUserRoles() {
		return userRoles;
	}


	public void setUserRoles(String[] userRoles) {
		this.userRoles = userRoles;
	}


	public String getMiddleName() {
		return middleName;
	}


	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getUpdatedDate() {
		return updatedDate;
	}


	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}


	public Address getAddress() {
		return address;
	}


	public void setAddress(Address address) {
		this.address = address;
	}


	public String getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}


	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	public boolean isActive() {
		return (IApplicationConstants.ACTIVE_FLAG.equals(getStatus()) || IApplicationConstants.SS_FLAG.equals(getStatus()))? true : false;
    }
   
	
}
