package com.ctb.prism.login.transferobject;

import java.sql.Timestamp;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.core.GrantedAuthority;

import com.ctb.prism.core.constant.IApplicationConstants;
import com.ctb.prism.core.transferobject.BaseTO;

@Document(collection = "User")
public class MUserTO extends BaseTO
{
	@Id
    private String _id;
	
    private String IsFirstTimeLogin;

    private PwdHistory[] PwdHistory;

    private String CustomerCode;

    private String Password;

    private OrgCategory OrgCategory;

    private String IsAutoGeneratedUser;

    private String Salt;

    private String LastName;
    private String lastName;

    private String IsActive;

    private String Project_id;

    private String FirstName;
    private String firstName;

    private HintAnswers[] HintAnswers;

    private String UserType;

    private String IsNewUser;

    private String DisplayName;
    private String displayName;

    private String SignedUserAgrmt;

    private String PhoneNum;

    private OrgUser[] OrgUser;

    private String[] UserRoles;

    private String MiddleName;

    private String Email;

    private String UpdatedDate;

    private Address Address;

    private String CreatedDate;

    public String getIsFirstTimeLogin ()
    {
        return IsFirstTimeLogin;
    }

    public void setIsFirstTimeLogin (String IsFirstTimeLogin)
    {
        this.IsFirstTimeLogin = IsFirstTimeLogin;
    }

    public PwdHistory[] getPwdHistory ()
    {
        return PwdHistory;
    }

    public void setPwdHistory (PwdHistory[] PwdHistory)
    {
        this.PwdHistory = PwdHistory;
    }

    public String getCustomerCode ()
    {
        return CustomerCode;
    }

    public void setCustomerCode (String CustomerCode)
    {
        this.CustomerCode = CustomerCode;
    }

    public String getPassword ()
    {
        return Password;
    }

    public void setPassword (String Password)
    {
        this.Password = Password;
    }

    public OrgCategory getOrgCategory ()
    {
        return OrgCategory;
    }

    public void setOrgCategory (OrgCategory OrgCategory)
    {
        this.OrgCategory = OrgCategory;
    }

    public String getIsAutoGeneratedUser ()
    {
        return IsAutoGeneratedUser;
    }

    public void setIsAutoGeneratedUser (String IsAutoGeneratedUser)
    {
        this.IsAutoGeneratedUser = IsAutoGeneratedUser;
    }

    public String getSalt ()
    {
        return Salt;
    }

    public void setSalt (String Salt)
    {
        this.Salt = Salt;
    }

    public String getLastName ()
    {
        return LastName;
    }

    public void setLastName (String LastName)
    {
        this.LastName = LastName;
        this.lastName = LastName;
    }

    public String get_id ()
    {
        return _id;
    }

    public void set_id (String _id)
    {
        this._id = _id;
    }

    public String getIsActive ()
    {
        return IsActive;
    }

    public void setIsActive (String IsActive)
    {
        this.IsActive = IsActive;
    }

    public String getProject_id ()
    {
        return Project_id;
    }

    public void setProject_id (String Project_id)
    {
        this.Project_id = Project_id;
    }

    public String getFirstName ()
    {
        return FirstName;
    }

    public void setFirstName (String FirstName)
    {
        this.FirstName = FirstName;
        this.firstName = FirstName;
    }

    public HintAnswers[] getHintAnswers ()
    {
        return HintAnswers;
    }

    public void setHintAnswers (HintAnswers[] HintAnswers)
    {
        this.HintAnswers = HintAnswers;
    }

    public String getUserType ()
    {
        return UserType;
    }

    public void setUserType (String UserType)
    {
        this.UserType = UserType;
    }

    public String getIsNewUser ()
    {
        return IsNewUser;
    }

    public void setIsNewUser (String IsNewUser)
    {
        this.IsNewUser = IsNewUser;
    }

    public String getDisplayName ()
    {
        return DisplayName;
    }

    public void setDisplayName (String DisplayName)
    {
        this.DisplayName = DisplayName;
        this.displayName = DisplayName;
    }

    public String getSignedUserAgrmt ()
    {
        return SignedUserAgrmt;
    }

    public void setSignedUserAgrmt (String SignedUserAgrmt)
    {
        this.SignedUserAgrmt = SignedUserAgrmt;
    }

    public String getPhoneNum ()
    {
        return PhoneNum;
    }

    public void setPhoneNum (String PhoneNum)
    {
        this.PhoneNum = PhoneNum;
    }

    public OrgUser[] getOrgUser ()
    {
        return OrgUser;
    }

    public void setOrgUser (OrgUser[] OrgUser)
    {
        this.OrgUser = OrgUser;
    }

    public String[] getUserRoles ()
    {
        return UserRoles;
    }

    public void setUserRoles (String[] UserRoles)
    {
        this.UserRoles = UserRoles;
    }

    public String getMiddleName ()
    {
        return MiddleName;
    }

    public void setMiddleName (String MiddleName)
    {
        this.MiddleName = MiddleName;
    }

    public String getEmail ()
    {
        return Email;
    }

    public void setEmail (String Email)
    {
        this.Email = Email;
    }

    public String getUpdatedDate ()
    {
        return UpdatedDate;
    }

    public void setUpdatedDate (String UpdatedDate)
    {
        this.UpdatedDate = UpdatedDate;
    }

    public Address getAddress ()
    {
        return Address;
    }

    public void setAddress (Address Address)
    {
        this.Address = Address;
    }

    public String getCreatedDate ()
    {
        return CreatedDate;
    }

    public void setCreatedDate (String CreatedDate)
    {
        this.CreatedDate = CreatedDate;
    }
    
    public boolean isActive() {
		return (IApplicationConstants.FLAG_Y.equals(getIsActive()))? true : false;
	}

    @Override
    public String toString()
    {
        return "ClassPojo [IsFirstTimeLogin = "+IsFirstTimeLogin+", PwdHistory = "+PwdHistory+", CustomerCode = "+CustomerCode+", Password = "+Password+", OrgCategory = "+OrgCategory+", IsAutoGeneratedUser = "+IsAutoGeneratedUser+", Salt = "+Salt+", LastName = "+LastName+", _id = "+_id+", IsActive = "+IsActive+", Project_id = "+Project_id+", FirstName = "+FirstName+", HintAnswers = "+HintAnswers+", UserType = "+UserType+", IsNewUser = "+IsNewUser+", DisplayName = "+DisplayName+", SignedUserAgrmt = "+SignedUserAgrmt+", PhoneNum = "+PhoneNum+", OrgUser = "+OrgUser+", UserRoles = "+UserRoles+", MiddleName = "+MiddleName+", Email = "+Email+", UpdatedDate = "+UpdatedDate+", Address = "+Address+", CreatedDate = "+CreatedDate+"]";
    }
}